### ISSUE TITLE
DynamicInputModel does not work with inputType:"file"

### ISSUE THREAD

**Issue by buhichan** [udos86/ng2-dynamic-forms#114]
After I choose the file to upload, I print out the FormGroup object, but there's nothing related to the file I chose.

**Comment by udos86** [comment]
@buhichan Thanks for your contribution. You're right. At the moment files are not connected to the `DynamicInputModel`. I'll try to solve this.

**Comment by udos86** [comment]
@buhichan Will probably resolved in RC.3 by adding a new property `files` to `DynamicInputModel`
