### ISSUE TITLE
Autocomplete with associated DataSource

### ISSUE THREAD

**Issue by Liza86** [udos86/ng2-dynamic-forms#116]
hi,
is there any plan to add an Input element with remote DataSource  ?

thanks
Liza

**Comment by udos86** [comment]
@Liza86 Thanks for your question. Could please specify your use case. What input information would you like to load from remote?

**Comment by Liza86** [comment]
I'm thinking to something like
 http://oferh.github.io/ng2-completer/
Remote Data case.

Is it possible to have such a kind of input field ?
Thanks

**Comment by udos86** [comment]
@Liza86 Sorry, I'm not planning on adding such a feature on my own but to support it as soon as Material 2 will bring out an autocomplete input. However you could already add that feature manually by dynamically setting the `list` property of any `DynamicInputModel`.

**Comment by Liza86** [comment]
ok, thanks

**Comment by rernens** [comment]
@udos86 

Hi Udo,

Material has now a fully working autocomplete that supports the async pipe.

While you are using the mat-autocomplete with your list option in ui-material, unless I am wrong, i don’t see a way of customizing this behavior.

One easy way of implementing this could be to add  the ability to set the [matAutocomplete] value of the input tag ( adding a listName property ? ) and give access to it in a custom template attached to the control.

But maybe have you thought to a clever way of implementing this.

**Comment by udos86** [comment]
@rernens Hi!

> While you are using the mat-autocomplete with your list option in ui-material, unless I am wrong, i don’t see a way of customizing this behavior.

What exactly would you like to customize?

> ...and give access to it in a custom template attached to the control.

I'm pretty sure this won't work as expected.

Material components rely totally on transclusion and there are heavy issues when trying to project wrapped or conditional markup.

Ever tried to transclude a  `ng-template` via `NgTemplateOutletDirective` into a Material component? 

I just won't work...

In my opinion they should overthink their concept and handle it more like Kendo UI.

**Comment by rernens** [comment]
@udos86 

Thanks for your reply.

In fact I was thinking, more broadly, about a way to specify in the model the optional parameters that the mat elements use ( ie startView="year"  or [mdDatepickerFilter]="myFilter" for DatePicker ) that your directives would apply to the relevant elements?

In the case of input with autocomplete, the ability to specify [matAutocomplete]="x" as part of the options would allow us then, I am assuming, to use your templating to add the necessary mat-autocomplete code :

```
<ng-template modelId="myInputWithMatAutocomplete">
 <mat-autocomplete #x="matAutocomplete">
   <mat-option *ngFor="let option of options" [value]="option">
      {{ option }}
   </mat-option>
 </mat-autocomplete>
</ng-template>

```
