### ISSUE TITLE
Removing module.id

### ISSUE THREAD

**Issue by enyachoke** [udos86/ng2-dynamic-forms#118]
Am using angular cli and am running into Uncaught TypeError: uri.match is not a function https://github.com/angular/angular/issues/10626

**Comment by udos86** [comment]
@enyachoke Shouldn't have anything to do with ng2 Dynamic Forms. Just use the bundle files provided  as described in [README.md](https://github.com/udos86/ng2-dynamic-forms#getting-started). Module ids are removed in there.

**Comment by udos86** [comment]
@enyachoke Nevertheless I will add a build step to remove module ids from single JS files

**Comment by udos86** [comment]
Will be fixed in next version tomorrow
