### ISSUE TITLE
More TAB, similar to the browser tabs, each TAB when a separate form

### ISSUE THREAD

**Issue by smile2014** [udos86/ng2-dynamic-forms#121]
Hello,udos86,can you help me, I want to do a click on the menu, add a new TAB, rather than as it is now click menu routing switch, the middle area is changed, how to implement

**Comment by udos86** [comment]
@smile2014 Have a look at these articles:

http://blog.thoughtram.io/angular/2015/04/09/developing-a-tabs-component-in-angular-2.html
http://juristr.com/blog/2016/02/learning-ng2-creating-tab-component/
https://dzone.com/articles/learning-angular-2-creating-a-tabs-component

What you would actually do is to use `ComponentFactoryResolver` to dynamically add a tab component at run time.

**Comment by smile2014** [comment]
@udos86  thank you
