### ISSUE TITLE
how to expose onChange/onBlur events to caller component(ie basic-example.component.)

### ISSUE THREAD

**Issue by rajeshpachar** [udos86/ng2-dynamic-forms#130]
I am looking for ways to expose change events to caller module(ex: basic-example.component). DynamicFormCustomComponent renders itself recursively for group/array components. what would be good way to expose blur/focus event from input component to caller component in case of group/array rendering.

Thanks

**Comment by udos86** [comment]
@rajeshpachar Thanks for your contribution! That's an interesting requirement. Could please explain your use case a bit more in detail? As you may have already seen you can bind to the `hasFocus` property of a `DynamicFormControlComponent` from the outside.

**Comment by rajeshpachar** [comment]
Thanks for the response. I am planning to write a json wrapper component which will take json and convert it dynamic form UI. Main page has dynamic form and side bar shows suggestion for input textbox whenever text box is in focus. 
dynamic form ui has nested structure, parent component -> dynamic-form-basic-control(L1) -> dynamic-form-basic-control(L2). We can't directly emit events from L2 to parent component. I believe angular2 doesn't natively support this. I was looking through web and found some proposals here:
http://stackoverflow.com/questions/34700438/global-events-in-angular-2
here 2 solutions are proposed: 
- Shared Application Model which is already supported in dynamic form through model binding 
- Shared Service. This can help to propagate any other event.

**Comment by udos86** [comment]
@rajeshpachar Alright, nice! I made a commit ccbc2db to solve your problem. You can now apply an `blur` and `focus` event binding from the outside. All event from nested inner `DynamicFormControlComponents` are also delegated to the outside. 

Please have a look and let me know if this helps you out.

**Comment by rajeshpachar** [comment]
@udos86 thanks for the prompt change .
This is great and I am getting events in parent component. This should help.

**Comment by udos86** [comment]
:+1: Will be released tonight
