### ISSUE TITLE
FormArray Within A FormGroup

### ISSUE THREAD

**Issue by Ellipizle** [udos86/ng2-dynamic-forms#139]
First of all i must commend you for this great library you have done.
I really appreciate your work and effort.

I am trying to create a formArray with a formGroup. from the samples i can guess the library is expecting the form array at the top level not within a formgroup.
i get an error `ORIGINAL EXCEPTION: Cannot find control with path: 'hh_member_names_repeat -> 0`,

I will be grateful if you can give me a hint on how i can hack this library to create a fromArray with a FormGroup.

**Comment by Ellipizle** [comment]
I found out my mistake after some digging, i was having multiple control with the same name.
the form array displays perfectly now. but, the template [add and remove button] are not displaying.

**Comment by udos86** [comment]
@Ellipizle Thanks for your nice message and your contribution. Please let me have look at it. This could be a bug. I will let you know as soon as possible.

**Comment by udos86** [comment]
@Ellipizle I confirm, this is a bug. Please give a couple of days to evaluate an appropriate solution. Thanks.

**Comment by udos86** [comment]
@Ellipizle Good news! I actually have found a solution to this. Have a look at 20bda4b. Fix will land in 1.0.5.

**Comment by Ellipizle** [comment]
sorry for not responding sooner, i have been off the radar for sometime now.
Wow! Nice. Thank you.
I will really like to contribute to this library, but i am still trying to wrap my head around angular 2 form module and given the fact that i am new to typescript/ javascript programming I bet I have alot to learn.
Thank you once again

**Comment by udos86** [comment]
@Ellipizle No problem, thanks for your nice message!
