### ISSUE TITLE
add support for specifying type:"number" or [default] type:"text" 

### ISSUE THREAD

**Issue by jchatkinson** [udos86/ng2-dynamic-forms#142]
Great library!

Right now, input controls default to type='text'.

It would be a nice addition to be able to specify type:'number' in the form model to override the default.

**Comment by jchatkinson** [comment]
Ah whoops, after looking closer, I see that I just had the wrong syntax, it should be inputType:'number'.

Perhaps it would be good to add this to the example

**Comment by udos86** [comment]
@jchatkinson Alright, no problem! You're right, the docs need some improvement!
