### ISSUE TITLE
add possibility to add validation messages to each individual input

### ISSUE THREAD

**Issue by JBusch** [udos86/ng2-dynamic-forms#154]
first of all, thank you so much for this great library! :) 

right now, if i understand everything correctly, it is not possible to add a validation message to an individual field. 

for example, i have a fieldgroup of name and passwort. the validation message is wrapped underneath the filedset.

is it possible to wrap the field unter let's say the input?

thanks and best regards

**Comment by DavyJohnes** [comment]
@JBusch, validation messages for each field will be avaialable for Bootstrap and Foundation soon. Take a look and this one: #153

**Comment by JBusch** [comment]
Would also be nice for basic html

**Comment by IvanZuev** [comment]
Feel free to implement it for basic html and create PR.

**Comment by udos86** [comment]
@JBusch Thanks for the nice message! I'll try to add it to the basic template as well.

**Comment by JBusch** [comment]
Thank You! :)
