### ISSUE TITLE
Form controls values are not updated

### ISSUE THREAD

**Issue by abdulhaq-e** [udos86/ng2-dynamic-forms#155]
Hello

I have a problem updating form control values. Using `valueUpdates`, I'm able to update the `value` property of the `DynamicFormModel`. This update however, is not reflected on the form control.

The piece of code responsible for this update is [L52-L57](https://github.com/udos86/ng2-dynamic-forms/blob/master/modules/core/src/component/dynamic-form-control.component.ts#L52-L57). What is happening in my case is that the subject is not pushing any values to the stream. For example, if I change those lines to:

```ts
if (this.model instanceof DynamicFormValueControlModel) {
    let model = <DynamicFormValueControlModel<any>> this.model;
    console.log("Do you see me?");
    model.valueUpdates.subscribe(val => console.log("Do you see me now?"))
    this.subscriptions.push(model.valueUpdates.subscribe(val => {
        console.log("What about now?")
        this.onModelValueUpdates(val)
    }));
}
```

The results: I can only see the first sentence in the log. The others do not appear because the subject has not emitted anything.

**Comment by udos86** [comment]
@abdulhaq-e I had quick look before work and in my example it's working. You need to update the value via `next` function of `Rx.Subject`:

`this.exampleModel.valueUpdates.next("Hello Hello");`

**Comment by abdulhaq-e** [comment]
I replicated the code in the sample app and it worked. However, the original issue still exists and I now know what it is.

This line `this.exampleModel.valueUpdates.next("My new value");` will have no effect if it's placed inside `ngOnit`. I've yet to figure out why.

**Comment by abdulhaq-e** [comment]
Okay, learned something now. The reason the value is not emitted is because the `DynamicFormControlComponent` has not finished initialising. By setting a time-out in `ngOnit` the form control value will change:

```ts
setTimeOut( () => this.exampleModel.valueUpdates.next("My new value"), 2000);
```

Now I'll have to figure how to do this programmatically. Probably using lifecycle hooks.

**Comment by abdulhaq-e** [comment]
```ts
import {AfterViewInit} from '@angular/core'

    // component defined here
    ngAfterViewInit() {
      this.exampleModel.valueUpdates.next("My new value")  
}
```

I always postponed reading about Angular 2 lifecycle hooks. I learned them the hard way.

Thanks.

**Comment by udos86** [comment]
@abdulhaq-e Alright, no problem! Thanks for the clarification.

**Comment by jmaheshTrimble** [comment]
Can i update id or any other properties of the control?

**Comment by udos86** [comment]
@jmaheshTrimble 

With the exception of `id` you can update any property you want.

But be careful when updating values and disabled state (see README).
