### ISSUE TITLE
[Question]Dynamic template for labels 

### ISSUE THREAD

**Issue by RomeroDiver** [udos86/ng2-dynamic-forms#157]
Hi,
First of all, thank you for this package - really helped us :)
As far as I can see, there are very limited things you can do to controls -e.g. we cannot extend labels templates for checkbox. And that was a problem for me, as I needed a list of images to be selected, which I implemented with checkboxes. My point is, there is no easy possibility to extend controls. For my particular case, I forked your repo and added ngStyle to the labels, if you want that functionality, I could create a PR. However, I was thinking about kind of transclusion parameters for labels, or even a possibility to create custom controls for us as developers and adding them to the forms. What do you think about it? 

Thanks for your time:)

**Comment by udos86** [comment]
@RomeroDiver Thanks for your message! You're right, the `label` property is limited to plain text so far. Making it accept HTML content would be a nice enhancement. If you'd like to contribute a feature like that, great!

**Comment by udos86** [comment]
@RomeroDiver Would `[innerHTML]` binding for labels be an appropriate solution to your problem?

**Comment by udos86** [comment]
@RomeroDiver Please have a look at 7c21332. Will arrive in 1.1.1.

**Comment by RomeroDiver** [comment]
Yes, `[innerHtml]` was also what I was thinking about. Also, is it possible to create my custom elements, by e.g. extending abstract formControl from this library?

**Comment by udos86** [comment]
@RomeroDiver You would have to extend either `DynamicFormValueControlModel`, `DynamicInputControlModel` or `DynamicOptionControlModel` depending on what kind of custom form control model you would like to add. 

But please remember that this would only create the dynamic model representation of an actual form control. 

If you would like to actually implement a custom form control, however, have look at this article: http://blog.thoughtram.io/angular/2016/07/27/custom-form-controls-in-angular-2.html

**Comment by RomeroDiver** [comment]
@udos86 Thank you, that's exactly what I needed!
