### ISSUE TITLE
Peer dependencies rxjs version differs from what angular2 requires.

### ISSUE THREAD

**Issue by DavyJohnes** [udos86/ng2-dynamic-forms#162]
Hi Udo!
ng2-dynamic-forms has peer dependency rxjs: "^5.0.0-rc.1", angular2 (2.1.1) at the same has peer dependency rxjs: "5.0.0-beta.12", It is ok while installing packages, npm warning can be just ignored, but ```npm shrinkwrap``` returns an error:
![2016-10-29_2258](https://cloud.githubusercontent.com/assets/6803001/19831419/37c947f6-9e2b-11e6-8b17-7e0c208c752b.png)

Is there any reason to use 5.0.0-rc.1?

**Comment by udos86** [comment]
@DavyJohnes Thanks for the hint! Guess, I was a bit hasty keeping all dependencies up to date to the latest version. Do you think there's a need for a patch in order to make it work with `npm shrinkwrap`?

**Comment by DavyJohnes** [comment]
@udos86 I'm almost sure yes. Since common one of common usecase is broken.

**Comment by udos86** [comment]
@DavyJohnes Ok! Does this only affect `rxjs` or any other dependency?

**Comment by DavyJohnes** [comment]
@udos86 I didn't noticed anything else, but I'd suggest to match peerDependencies with angular's ones.

**Comment by udos86** [comment]
@DavyJohnes Yep, good suggestion. My mistake!
