### ISSUE TITLE
How to use/include third party component?

### ISSUE THREAD

**Issue by sivamamidi-REISys** [udos86/ng2-dynamic-forms#167]
How to use third party component, for example : Here is the repository of table component, could you provide guidelines how to include this component?

https://github.com/ssuperczynski/ng2-easy-table

If not Is there any way we can build dynamic editable table?

**Comment by udos86** [comment]
@sivamamidi-REISys I'm afraid, I cannot see an editable data grid becoming a straightforward form control. Could please specify your use case?  [You would probably have to implement a custom form control](http://blog.thoughtram.io/angular/2016/07/27/custom-form-controls-in-angular-2.html) before integrating it into ng2 Dynamic Forms.

**Comment by sivamamidi-REISys** [comment]
we have excel kind of data entry form is to build, we are trying out to figure out what are the best options out there?

**Comment by JBusch** [comment]
same would apply for lets say a custom upload component or a datepicker right?

**Comment by udos86** [comment]
Basically yes, but an upload or datepicker component are typical form controls and would usually rely on one input field a complex data grid with searchable columns to just does not fit into the context of ng2 Dynamic Forms.
