### ISSUE TITLE
Setting checkboxes to true does not not check the check box

### ISSUE THREAD

**Issue by JBusch** [udos86/ng2-dynamic-forms#168]
hey,

if i check a checkbox with valueUpates.next(true), the value gets updated as expected. but the checkbox does not get checked. is it may be because [checked] is missing from <input type="checkbox">?

Also, is there a possibility to check check boxes depending on each other? like "check all"? i don't see how it is possible right now.

Thank you so much for your time!

**Comment by udos86** [comment]
@JBusch Thank you very much for your bug report. @netTrek has already opened a pull request concerning this issue.

**Comment by udos86** [comment]
@JBusch You're right, at the moment there is no simple function to check all checkboxes of a checkbox group. That would be a really nice little feature addition. I'll try to implement it within the next couple of days.

**Comment by JBusch** [comment]
You are the best, seriously. Thank you!!

**Comment by udos86** [comment]
@JBusch Please have a look at 93f39308ed3d73cff25adce877ba2777148f7ec6: `checkAll` and `uncheckAll` functions were added.
