### ISSUE TITLE
How can I enable/disable submit button?

### ISSUE THREAD

**Issue by psotelo** [udos86/ng2-dynamic-forms#171]
How can I enable/disable submit button when all the answers of my poll (dynamic form) are answered or checked?

thanks

**Comment by udos86** [comment]
@psotelo Ok, this question is not specific to ng2 Dynamic Forms but I'll give you an example anyway:

```
<form  [formGroup]="myForm" #formVar ="ngForm">

<!-- put all dynamic components here -->

<button type="submit" [disabled]="!formVar.form.valid">Submit</button>

</form>
```
