### ISSUE TITLE
Problem extracting checkbox value

### ISSUE THREAD

**Issue by psotelo** [udos86/ng2-dynamic-forms#172]
When I click over the generated checkboxes its internal value is always "false". This is de HTML code generated

`<input type="checkbox" ng-reflect-name="checkbox_54245" ng-reflect-dynamic-id="checkbox_54245" id="checkbox_54245" name="checkbox_54245" value="false" class="ng-valid ng-dirty ng-touched">`

why is happening this?

thank you

**Comment by udos86** [comment]
@psotelo You're absolutely right. This seems to be a bug in `DynamicCheckboxGroup` while everything is working fine with single `DynamicCheckboxModel`. I'll have to verify this. Thanks!

**Comment by udos86** [comment]
Ok, this is pretty strange. When updating the value of a checkbox of a `DynamicCheckboxGroupModel` programmatically the markup is correctly updated. At the moment At the moment I cannot see any wrong code in ng2 Dynamic Forms causing this.

**Comment by udos86** [comment]
To avoid this for the moment use a `DynamicFormGroupModel` instead of a `DynamicCheckboxGroupModel`. Nevertheless under the hood everything seems fine. Only the reflection in markup is not updated.

**Comment by JBusch** [comment]
I would have a look!

**Comment by udos86** [comment]
@JBusch That would be really cool!

**Comment by psotelo** [comment]
Thank you! I'm going to test it!
