### ISSUE TITLE
Bootstrap Form Layout: how to change "row" settings

### ISSUE THREAD

**Issue by crtormen** [udos86/ng2-dynamic-forms#173]
Hello.
I'm trying to organize my fields by rows and cols, but
looking in the examples and documentation, didn't find if it's possible.

So, for example, I want sometimes more than one field in the same row, 
On the other hand, in FormArray with more than one field, they are being aligned at the
same row, and I would want to put only one by row.

How could I do it?
Sorry if this already was explained somewhere, but I've searched in open and closed issues and in the example, but didn't find anything related.

And thank you for this amazing work, it's helping me a lot!

**Comment by udos86** [comment]
@crtormen Hi, this is where it get's a bit tricky. But here is a pretty straightforward solution that would do the job:

**1. A sample form model:**
```
export const MY_SAMPLE_MODEL = [

    new DynamicInputModel(
        {
            id: "firstName",
            placeholder: "first name"
        },
        {
            grid: {
                control: "col-sm-12"
            }
        }
    ),

    new DynamicInputModel(
        {
            id: "lastName",
            placeholder: "last name"
        },
        {
            grid: {
                control: "col-sm-12"
            }
        }
    ),

    new DynamicInputModel(
        {
            id: "street",
            placeholder: "street"
        },
        {
            grid: {
                control: "col-sm-9"
            }
        }
    ),

    new DynamicInputModel(
        {
            id: "streetNumber",
            placeholder: "street number"
        },
        {
            element: {},
            grid: {
                control: "col-sm-3"
            }
        }
    ),

    new DynamicInputModel(
        {
            id: "zipCode",
            placeholder: "zip code"
        },
        {
            grid: {
                control: "col-sm-3"
            }
        }
    ),

    new DynamicInputModel(
        {
            id: "city",
            placeholder: "city"
        },
        {
            grid: {
                control: "col-sm-9"
            }
        }
    )
];
```

**2.Binding in template:**

```
<form class="" [formGroup]="form">

<dynamic-form-bootstrap-control *ngFor="let controlModel of MY_SAMPLE_MODEL"
                                        [controlGroup]="form"
                                        [model]="controlModel">
</dynamic-form-bootstrap-control>

</form>
```

If you would like to explicitly work with `row` classes you should probably use `DynamicFormGroupModel`s. You also experiment with Bootstrap's `form-inline` class.

There might also be a way to achieve this by slicing your form model like this:
```
<form [formGroup]="form">

<div class="row">

<dynamic-form-bootstrap-control *ngFor="let controlModel of MY_SAMPLE_MODEL.slice(0,2)"
                                        [controlGroup]="form"
                                        [model]="controlModel">
</dynamic-form-bootstrap-control>

</div>

<div class="row">

<dynamic-form-bootstrap-control *ngFor="let controlModel of MY_SAMPLE_MODEL.slice(2,5)"
                                        [controlGroup]="form"
                                        [model]="controlModel">
</dynamic-form-bootstrap-control>

</div>

</form>
```

**Comment by crtormen** [comment]
Hi @udos86, thank you for your answer.
This second solution, slicing the form, is very good, cause gave me more flexibility.

I don't think the first solution is a good one, cause it isn't respecting maxLength.
So, even if I put maxLenght = 10, for example, and use col-sm-12 to complete my row, my field take the whole line. 

I don't know if this is a bug, or if I'm using it wrongly,
