### ISSUE TITLE
[Question] How to attribute events on inputs

### ISSUE THREAD

**Issue by Myo1030** [udos86/ng2-dynamic-forms#174]
Hi,
After multiple searches, I can't reproduce an onBlur (or equivalent) like my standard form. I start on Angular so I apologize in advance if there is already a simple way.

I wish to reproduce the equivalent of this (view : home.component.html) : 

```html
<form #stockMovementForm="ngForm" (ngSubmit)="onSubmit()" class="form-horizontal">
    <div class="form-group form-group-lg">
        <label for="codeArticle">Code article</label>
            <div class="col-sm-7">
                <input type="text" class="form-control"
                    id="codeArticle"
                    name="codeArticle"
                    [(ngModel)]="stockMovement.codeArticle"
                    #codeArticle="ngModel"
                    (change)="itemDetailValidateForm()">
            </div>
    </div>
    ...
</form>
```

My new form : 

```javascript
<form class="form-horizontal"
    [formGroup]="formGroupStockMovement"
    #stockMovementForm="ngForm"
    (ngSubmit)="onSubmit()">

    <dynamic-form-bootstrap-control
        class="form-group-lg"
        *ngFor="let controlModel of dynamicFormModel"
        [controlGroup]="formGroupStockMovement"
        [model]="controlModel"
        [hasErrorMessaging]="controlModel.hasErrorMessages">
    </dynamic-form-bootstrap-control>
</form>
```

My model looks like this (model : stockMovement.ts) :

```javascript
export const StockMovementFormModel = [
  new DynamicFormGroupModel({
    id: "stockMovementFormGroup",
    group: [
      new DynamicInputModel(
        {
          autoFocus: true,
          required: true,
          id: "codeArticle",
          label: "Code article",
          maxLength: 50,
          validators: [Validators.required],
          // (change): itemDetailValidateForm() <-- Equivalent ?
        },
        {
          element: {
            label: "col-sm-4 col-md-5 control-label"
          },
          grid: {
            control: "col-sm-7",
            errors: "col-sm-offset-3 col-sm-9",
            label: "col-sm-3"
          }
        }
      )
    ]
  }),
];
```
The form has several fields, and the event (change) is on 3 particular fields.

Thank you.

**Comment by udos86** [comment]
@Myo1030 Hi, thanks for trying out ng2 Dynamic Forms!  

If you would like to explicitly listen to the blur event, then you need an event binding on your dynamic form control like this:

```
    <dynamic-form-bootstrap-control
        class="form-group-lg"
        *ngFor="let controlModel of dynamicFormModel"
        [controlGroup]="formGroupStockMovement"
        [model]="controlModel"
        [hasErrorMessaging]="controlModel.hasErrorMessages"
        (blur)="onBlur($event)">
    </dynamic-form-bootstrap-control>
```

If you would like to listen to value changes then you can either bind to the change event:

```
    <dynamic-form-bootstrap-control
        class="form-group-lg"
        *ngFor="let controlModel of dynamicFormModel"
        [controlGroup]="formGroupStockMovement"
        [model]="controlModel"
        [hasErrorMessaging]="controlModel.hasErrorMessages"
        (change)="onChange($event)">
    </dynamic-form-bootstrap-control>
```

Or you could subscribe to `valuesUpdates` `Rx.Observable` of any `DynamicFormValueControlModel`:

`this.myInputModel.valueUpdates.subscribe(value => console.log(value));`

**Comment by Myo1030** [comment]
Thank you for your reply.
I've tried all of your proposals, but every time I have a new problem.

With onBlur: Works well but actually an onChange is better for what I need.

Witg onChange: Works well but I do not know why the event is launched 3 times, each time I change the value of an input : 
```html
<dynamic-form-bootstrap-control
    class="form-group-lg"
    *ngFor="let controlModel of stockDynamicFormModel"
    [controlGroup]="stockFormGroup"
    [model]="controlModel"
    [hasErrorMessaging]="controlModel.hasErrorMessages"
    (change)="onChange($event)">
    </dynamic-form-bootstrap-control>
```
```javascript
onChange(value)
{
    console.log(value.srcElement.id)
}
```
```console
codeArticle
codeArticle
codeArticle
ancienMagasin
ancienMagasin
ancienMagasin
codeArticle
codeArticle
```

ValueUpdate: I can not use your method. I used your bootstrap example


Nothing happens, no event.

**Comment by Myo1030** [comment]
Thank you for your reply.
I've tried all of your proposals, but every time I have a new problem.

With onBlur: Works well but actually an onChange is better for what I need.

With onChange: Works well but I do not know why the event is launched 3 times, each time I change the value of an input : 

home.component.html :
```html
<dynamic-form-bootstrap-control
    class="form-group-lg"
    *ngFor="let controlModel of stockDynamicFormModel"
    [controlGroup]="stockFormGroup"
    [model]="controlModel"
    [hasErrorMessaging]="controlModel.hasErrorMessages"
    (change)="onChange($event)">
</dynamic-form-bootstrap-control>
```

home.component.ts
```javascript
onChange(value)
{
    console.log(value.srcElement.id)
}
```

Chrome console log (I write 'test' in the first input 'codeArticle', then 'test' in the second input 'ancienMagasin', then 'test2' in the first input, finaly click out of the input):
```console
codeArticle
codeArticle
codeArticle
ancienMagasin
ancienMagasin
ancienMagasin
codeArticle
codeArticle
codeArticle
```

ValueUpdate: I can not use your method. I used your bootstrap example :

```javascript
import {Component, OnInit, ViewEncapsulation} from '@angular/core';
import {Http, URLSearchParams} from "@angular/http";
import {isString} from "util";
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/catch'

import {StockMovementFormModel, StockMovement} from "./stockMovement";
import {ToastsManager, Toast} from "ng2-toastr/ng2-toastr";

import {DynamicFormService, DynamicFormControlModel, DynamicInputModel, DynamicFormGroupModel} from "@ng2-dynamic-forms/core";
import {FormGroup} from "@angular/forms";

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
  encapsulation: ViewEncapsulation.None
})

export class HomeComponent implements OnInit
{
  stockDynamicFormModel: Array<DynamicFormControlModel> = StockMovementFormModel;
  stockFormGroup: FormGroup;

  exampleModel: DynamicInputModel;

  constructor (
    public toastr: ToastsManager,
    private http: Http,
    private dynamicFormService: DynamicFormService
  ) {
    //this.stockDynamicFormModel = StockMovementFormModel;
  }

  ngOnInit()
  {
    this.stockFormGroup = this.dynamicFormService.createFormGroup(this.stockDynamicFormModel);

    this.exampleModel = <DynamicInputModel> this.dynamicFormService.findById(
      "codeArticle", (<DynamicFormGroupModel> this.stockDynamicFormModel[0]).group);

    this.exampleModel.valueUpdates
      .subscribe(
      value => {
        console.log(value);
      },
      error => {
        console.log(error);
      },
      () => console.log('done')
    );
  }
}
```

Nothing happens, no return.

**Comment by udos86** [comment]
@Myo1030 Thanks for your feedback! It uncovered some flaws still existing in the code!

The `blur` event is thrown multiple times because you nested the input in a group model. I will enhance the event data object in order to provide the information which control caused the event in the next version!

I'm sorry for the mistake with `valueUpdates`. I answered you in a total hurry yesterday. Of course you need to use the `valueChanges` `Rx.Observable` on a `FormControl`. `valueUpdates` should only be used for sending new values at the moment:

```
this.exampleControl = <FormControl> this.form.get("bootstrapFormGroup1").get("bootstrapInput");

this.exampleControl.valueChanges.subscribe((value: string) => console.log(value));
```
Sorry again!

**Comment by udos86** [comment]
@Myo1030 Thanks again! This was valuable feedback to improve the quality of the lib as of the next version!

**Comment by Myo1030** [comment]
Hi @udos86,
Thank you for your answer, I understand now.

Your solution works very well, I will certainly use it for another functionality but that's not what I'm looking for immediatly.
In order to optimize, I need something close of the (change), an event when the value of an input is changed and the focus is lost.
The (blur) is very close to what I need (the event starts if the value of an input is not modified unfortunately). My problem is I can not assign by input, I am bound to put it to all the form (always in order to optimize).

Thank you.

**Comment by udos86** [comment]
@Myo1030 I completely refactored the event handling in `1.2.0` based on your issues. Please see the Changelog and the updated Bootstrap example.

Maybe a solution for your problem is to create an observable stream that combines the `blur`and `change`event?

**Comment by Myo1030** [comment]
Hi @udos86,

Thank you for this quick update, it works very well! 
This is exactly what I am looking for, it would be even better if I could initiate the event directly on the input.

What do you think about a possibility like this? : 
```javascript
export const StockMovementFormModel = [
  new DynamicFormGroupModel({
    id: "stockMovementFormGroup",
    group: [
      new DynamicInputModel(
        {
          autoFocus: true,
          required: true,
          id: "codeArticle",
          label: "Code article",
          maxLength: 50,
          validators: [Validators.required],
          event: {
            change: onChange(foo),
            blur: onBlur(foo),
            focus: onFocus(foo),
          }
        },
        {
          element: {
            label: "col-sm-4 col-md-5 control-label"
          },
          grid: {
            control: "col-sm-7",
            errors: "col-sm-offset-3 col-sm-9",
            label: "col-sm-3"
          }
        }
      )
    ]
  }),
];
```

But now, your update suits me very well, thank you again for your support (and sorry for my bad english :P )
