### ISSUE TITLE
Possibility to dynamically add and remove options from a select

### ISSUE THREAD

**Issue by JBusch** [udos86/ng2-dynamic-forms#180]
Hey,

it would be really nice if it was possible to add and remove options from a select. maybe somrthing similar to form arrays? 

best regards
johannes

**Comment by udos86** [comment]
@JBusch First of all, thanks for your activities here! You could already do that manually but there is definitely a need for a simple function to achieve this. This will probably be the next little feature to land in the lib. Maybe observable-based (see also #165).
