### ISSUE TITLE
possibility to insert "templates"

### ISSUE THREAD

**Issue by JBusch** [udos86/ng2-dynamic-forms#181]
Hey,

i would be awesome, it it was possible to include templates in the form model for example to add a button.

may be something like 
` new DynamicTextAreaModel({
        id: 'myid',
        label: 'mylabel',
        rows: 5
      }),
new DynamicTemplate ({
  id: myTemplate',
  templateUrl: ../../template.html
})
`

it would offer a lot flexibility i think!

best regards
johannes

**Comment by udos86** [comment]
@JBusch I totally understand the need of adding additional markup to the form, but the model should definitely not be polluted by some content of a total different concern. You wouldn't want to mix up strings and numbers in an array either...

At the moment you can already add markup via simple transclusion:
```
<dynamic-form-bootstrap-control *ngFor="let controlModel of dynamicFormModel"
                                                           [controlGroup]="form"
                                                           [model]="controlModel">

    <p *ngIf="controlModel.type === 'SELECT'">My transcluded content</p>

</dynamic-form-bootstrap-control>
```

For form arrays you can even attach a `template` tag as described in [`README.md`](https://github.com/udos86/ng2-dynamic-forms#form-arrays).

**Comment by JBusch** [comment]
Hey, yes this works. but if you use a group. the content gets transcluded in the end of the formgroup, not after the input for example

`<p *ngIf="controlModel.group[1].id === 'myCategories'">My transcluded content</p>`

**Comment by udos86** [comment]
@JBusch You're right, that's yet a flaw...
