### ISSUE TITLE
Possibility to add custom templates

### ISSUE THREAD

**Issue by JBusch** [udos86/ng2-dynamic-forms#182]
Hey,

i would be awesome, it it was possible to include templates in the form model for example to add a button.

may be something like 
` new DynamicTextAreaModel({
        id: 'myid',
        label: 'mylabel',
        rows: 5
      }),
new DynamicTemplate ({
  id: myTemplate',
  templateUrl: ../../template.html
})
`

it would offer a lot flexibility i think!

best regards
johannes

**Comment by philrowan-mtb** [comment]
Hi @JBusch, I had a similar thought but I think a different approach. Just wondering why this got closed so quickly? 
Thanks

**Comment by JBusch** [comment]
i added this by mistake, so i closed it. please have a look at #181
