### ISSUE TITLE
How to validate multiple DynamicCheckboxGroupModel against each other ?

### ISSUE THREAD

**Issue by johngrimsey** [udos86/ng2-dynamic-forms#188]
Hi there - this is a great library good job!

Please could you help to figure out how to validate one DynamicFormArrayModel  group by comparing with another group in the same array?

I have:
```
  new DynamicFormArrayModel({
    id:           'openingDays',
    initialCount: 1,
    createGroup:  createDaysGroup,
  })
```

and 

```
export const createDaysGroup = (): any => {
  return [
    new DynamicCheckboxGroupModel({
      id:        'days',
      legend:    'Days',
      validator: DaysValidator,
      group:     [
        new DynamicCheckboxModel({
          id:    'mon',
          label: 'Mon'
        }),
        new DynamicCheckboxModel({
          id:    'tue',
          label: 'Tue'
        }),
        new DynamicCheckboxModel({
          id:    'wed',
          label: 'Wed'
        }),
        new DynamicCheckboxModel({
          id:    'thu',
          label: 'Thu'
        }),
        new DynamicCheckboxModel({
          id:    'fri',
          label: 'Fri'
        }),
        new DynamicCheckboxModel({
          id:    'sat',
          label: 'Sat'
        }),
        new DynamicCheckboxModel({
          id:    'sun',
          label: 'Sun'
        }),
      ]
    }),
```

I can validate the values of one checkbox group via the `DaysValidator` function no problem but can't see how to output the message, or to access the values of another group (I need to compare them).

I have two questions I'd be grateful for you help on!

1) How to validate a group and display a message beneath that group? (I am outputting the controls in an ngFor loop at the moment, using basic-ui)
2) How to validate a group comparing values of another group in the same array?

Thanks :)

**Comment by johngrimsey** [comment]
Perhaps it'll be a case of subscribing to relevant `valueChanges` and working from there...

**Comment by udos86** [comment]
@johngrimsey Thanks again for your message!  I'll have a look at it as soon as I'll find a bit of free time.

**Comment by udos86** [comment]
@johngrimsey Sorry for the late answer. At the moment you would have to manually validate and compare array groups. Could be a nice feature for the future but I haven't thought about a good way to solve this so far.
