### ISSUE TITLE
How to instantiate dynamic forms completely through json

### ISSUE THREAD

**Issue by Darshan-popin** [udos86/ng2-dynamic-forms#192]
i was going through dynamic forms had a thought building the forms dynamically and storing it in a database ,.. and retrieve the same whenever it is necessary,. with that thought i was not able instantiate the dynamic classes when  the json is being retrieved ,.. any suggestion on how to do this ?? or could this be an enhancement ???

**Comment by udos86** [comment]
@Darshan-popin You can do that already. See the [README.md](https://github.com/udos86/ng2-dynamic-forms#json-export-and-import).

**Comment by Darshan-popin** [comment]
@udos86 thanks
