### ISSUE TITLE
onChange event delivers old value

### ISSUE THREAD

**Issue by JBusch** [udos86/ng2-dynamic-forms#193]
Hey,

its me again ;)

I think i found a bug. I'm listenign on events on a form with a select. The first time i choose something, the value emitted in the onChange is null, the second time i   ##choose something, the value is the first value and so on.

**Comment by JBusch** [comment]
After updating the bug is gone

**Comment by udos86** [comment]
@JBusch No problem. Appreciate your effort! 👍
