### ISSUE TITLE
Dependencies error

### ISSUE THREAD

**Issue by JBusch** [udos86/ng2-dynamic-forms#194]
Hey,

after upgrading to the newest version i'm getting 

> node_modules\@ng2-dynamic-forms\core\src\component\dynamic-form-control.component.ts:3:67 
Cannot find module '@angular/material'.

even though, i'm just using basic.

**Comment by JBusch** [comment]
Sorry, my bad, hat the wrong version in package.json

**Comment by JBusch** [comment]
well, i checked again, i now o think its a bug.

**Comment by udos86** [comment]
@JBusch Indeed, it is. Will deliver an update within the next hour.

**Comment by udos86** [comment]
@JBusch Thanks for tracking this so quickly. Made a bad rookie mistake, I guess. Pleas check out `1.2.4`

**Comment by JBusch** [comment]
No, thank you :)
