### ISSUE TITLE
onChange causes error when using with checkbox

### ISSUE THREAD

**Issue by JBusch** [udos86/ng2-dynamic-forms#197]
I'm now (v1.2.4) getting this error when listening on form changes and selecting a checkbox:

> Error in ./DynamicFormBasicComponent class DynamicFormBasicComponent - inline template:0:72 caused by: self.parentView.context.onChange is not a function

**Comment by udos86** [comment]
@JBusch Wow, I really messed it up yesterday. Thanks for the. I don't really know how this bug slipped through. I'll fix immediately.

**Comment by JBusch** [comment]
Yep, works like a charm now, thanks!
