### ISSUE TITLE
Serialization of validator functions that accept arguments

### ISSUE THREAD

**Issue by udos86** [udos86/ng2-dynamic-forms#200]
`Validators` that accept an argument like `Validators.maxLength` cannot be serialized at the moment.

**Comment by udos86** [comment]
Will probably introduce a breaking change to solve this.

**Comment by DavyJohnes** [comment]
Hi @udos86,
This is great improvement, however, it seems like there is not way to provide custom validators. By "custom validator" I mean a simple functions, which I previously just included in validators array. As far as I understand currently ng2-forms just picks validators function from @angular/forms/Validators, it means that there is no way to use custom validators.

**Comment by udos86** [comment]
@DavyJohnes 

Thanks! In order to use custom validators please provide them via `NG_VALIDATORS` at first (see http://blog.thoughtram.io/angular2/2015/11/23/multi-providers-in-angular-2.html). Then you can reference them by name as all built-ins.

**Comment by udos86** [comment]
@DavyJohnes Please have a look at 8ddf56c. These fix will allow you to reference any custom validators given that they're provided via `NG_VALIDATORS` or `NG_ASYNC_VALIDATORS`.

**Comment by DavyJohnes** [comment]
@udos86 thanks a lot, will try to use this new approach.

**Comment by udos86** [comment]
@DavyJohnes You're welcome! Thank you for letting me know about the bug.

**Comment by udos86** [comment]
@DavyJohnes I've added a little guide in the README.md as: https://github.com/udos86/ng2-dynamic-forms#custom-validators
