### ISSUE TITLE
Prefilling datetime-local local inputs does not update the filed

### ISSUE THREAD

**Issue by JBusch** [udos86/ng2-dynamic-forms#202]
Hey,

when i prefill(with valueUpdates.next()) a datetime-local filed with it's saved value, the value of the field gets updated, but the "frontend" of the filed gets not, it just displays the default placeholder as if the field was empty
 (tt.mm.jjj --.--).

Best regards
Johannes

**Comment by JBusch** [comment]
my bad again. it works with date.toISOString().slice(0,16)

Sorry for the inconveniences!

**Comment by udos86** [comment]
@JBusch Alright, no problem. Thanks for trying this out.
