### ISSUE TITLE
Feature request: Add hint output to ui-basic elements

### ISSUE THREAD

**Issue by johngrimsey** [udos86/ng2-dynamic-forms#203]
It would be great to be able to specify 'hint' and have that output text when using the ui-basic module.

**Comment by udos86** [comment]
@johngrimsey Thanks for the feature request! I'm going to include it in the next patch version `1.3.1`.

**Comment by johngrimsey** [comment]
Awesome! Do you think the rendered layout will be:

label
control
hint
error

**Comment by udos86** [comment]
@johngrimsey yes

**Comment by johngrimsey** [comment]
Thanks!
