### ISSUE TITLE
add min and max for dateinputs

### ISSUE THREAD

**Issue by JBusch** [udos86/ng2-dynamic-forms#206]
Wouldn't it be nice, if we could set min and max for date inputs? we could easily set them which would make a lot of validation obsolete imho.

**Comment by udos86** [comment]
@JBusch I would not like to add these properties to `DynamicInputModel` as this is not part of the HTML 5 standard. However I'm planning to introduce a `DynamicDatePickerModel` as soon as Material 2 does deliver a corresponding UI control. There, your proposal could make a nice addition. 

Thanks for your ideas!

**Comment by JBusch** [comment]
well, do i red it false then? https://www.w3.org/TR/html51/sec-forms.html#date-state-typedate

**Comment by udos86** [comment]
@JBusch Oh, you're right. I originally thought that min and max attributes would only apply to input type number. Nevertheless you can already set `min` and `max` properties for `DynamicInputModel`.

**Comment by JBusch** [comment]
> you can already set min and max properties for DynamicInputModel
well, those on the input model are numbers. we would need dates here though, right?

**Comment by udos86** [comment]
@JBusch Yep, I should extend the type to `number | date`. Still you can already give it a try (just ignore the TS transpiler error).

**Comment by udos86** [comment]
@JBusch I'm not sure. Shouldn't it be `number | string` (see http://www.w3schools.com/tags/att_input_min.asp)?

**Comment by JBusch** [comment]
Jap, valid date string is fine. i'll check it out.

**Comment by JBusch** [comment]
Yes, it already works just by setting the min attribute on the input model!

**Comment by JBusch** [comment]
well, min and max are only number right now, which throws an error:

```
export interface DynamicInputModelConfig extends DynamicInputControlModelConfig {
    accept?: string;
    inputType?: string;
    list?: Array<string>;
    max?: number;
    min?: number;
    multiple?: boolean;
    pattern?: string;
    step?: number;
}
export declare class DynamicInputModel extends DynamicInputControlModel<any> {
    accept: string | null;
    inputType: string;
    files: FileList | null;
    list: Array<string> | null;
    max: number | null;
    min: number | null;
    multiple: boolean | null;
    pattern: string | null;
    step: number | null;
    private listId;
    readonly type: string;
    constructor(config: DynamicInputModelConfig, cls?: ClsConfig);
}
```

**Comment by JBusch** [comment]
A DynamicDatePickerModel would be really nice btw. Type "date" is so sad right now :(

**Comment by udos86** [comment]
@JBusch types will be adjusted in the next patch version `1.3.2`
