### ISSUE TITLE
how to validate two fields depending on ech other?

### ISSUE THREAD

**Issue by JBusch** [udos86/ng2-dynamic-forms#207]
Hey,

Lets say i want to disable a field and show a error message depending on the value of an other field.

Is this possible?

Thank you and best regards
Johannes

**Comment by JBusch** [comment]
I found a way. One could pass a validator to a form group like so: 
```javascript
export function validateMyFields(key: string, key1 : string) {
  return (group: FormGroup): {[key: string]: any} => {
    let password = group.controls[key];
...
```

but that would require to have a formgroup in the form model since otherwise there is no place where one could pass the validator to the group, right?

**Comment by udos86** [comment]
@JBusch I don't know if it's exactly what you mean but there's already such a thing as [form control dependencies](https://github.com/udos86/ng2-dynamic-forms#related-form-controls)

**Comment by JBusch** [comment]
for example, i mean to validate a date input depending on an other date input and display an error message if the second date is before the first date. that would be possible with the current setup?

**Comment by udos86** [comment]
@JBusch No that's not possible with the current state of the implementation. But your proposal seems to be a very good approach to this.
