### ISSUE TITLE
Dyamic forms in a lazy loaded module

### ISSUE THREAD

**Issue by dakipro** [udos86/ng2-dynamic-forms#212]
Hi,
Great library, exactly what I was looking for. 
I fallowed the example from the main page, and it works fine in the modules/components loaded in the main module. If I however try to use it in a asynchronously loaded module, it says that 
> Can't bind to 'controlGroup' since it isn't a known property of 'dynamic-form-bootstrap-control'.

If I try to define dynamic-forms inside the loaded module I get the error 
> DynamicFormsCoreModule  should only be imported in the root NgModule of the application!

Same happens if I try to import it via "shared" module. 
I am using angular with angular-cli. Where and how should dynamic-forms be loaded in the project which has asynchronously loaded modules?

Thanks

**Comment by udos86** [comment]
@dakipro Thanks for your message and trying it out the library!

> DynamicFormsCoreModule should only be imported in the root NgModule of the application!

That means that you imported `DynamicFormsCoreModule` more than once. You should only import it`forRoot()` once in your application. 

Could you please show me the code of your app root NgModule and your lazy loaded feature NgModule?

**Comment by dakipro** [comment]
sure, app module is something like

import { CommonModule } from '@angular/common';
import { NgModule, isDevMode } from '@angular/core';
import { HttpModule, JsonpModule } from '@angular/http';
import {BrowserModule} from "@angular/platform-browser";
....

import {DynamicFormsCoreModule} from "@ng2-dynamic-forms/core";
import {DynamicFormsBootstrapUIModule} from "@ng2-dynamic-forms/ui-bootstrap";
.....

 imports: [
    CommonModule,
    HttpModule,
    SharedModule.forRoot(),

    MessagesModule, //primeNg module which works fine in lazy loaded module

    DynamicFormsCoreModule.forRoot(),
    DynamicFormsBootstrapUIModule,
    BrowserModule,
    ....

export class AppModule {
  constructor(private logger: Logger) {
    // if (isDevMode()) {
    //   console.info('To see debug logs enter: \'logger.level = logger.Level.DEBUG;\' in your browser console');
    // }
    this.logger.level = environment.logger.level;
  }
}




IT has some more modules and imports, providers etc. If you think it is relevant I can past the whole module

---------------------------------
Then the lazy module

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormsModule } from '@angular/forms';

import { ItemsRoutingModule } from './items-routing.module';
import { SharedModule } from '../shared/shared.module';


import { ItemsComponent } from './items.component';
import { ItemDetailComponent } from './item-detail/item-detail.component';

import { TreeModule } from 'angular2-tree-component';
import { MapToIterablePipe } from '../shared/map-to-iterable.pipe';



@NgModule({
  imports: [
    CommonModule,
    SharedModule,
    ItemsRoutingModule,

    ReactiveFormsModule,
    TreeModule,
    FormsModule

  ],
  declarations: [ItemsComponent, ItemDetailComponent, ItemListComponent, MapToIterablePipe, ItemEditComponent]
})
export class ItemsModule { }

**Comment by udos86** [comment]
As far as I can see you need to import `DynamicFormsBootstrapUIModule` into your lazy loaded module as well.

**Comment by dakipro** [comment]
I just tried that, but I am getting 
> DynamicFormsCoreModule should only be imported in the root NgModule of the application!

Which means it is already loaded in the root NgModule? I had similar "complaints" from the PrimeNg, but I think it was missing some module (I think it was "FormsModule" or something). 

I have that (and ReactiveFormsModule that might be required) in the common module

import { NgModule, ModuleWithProviders } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormsModule } from '@angular/forms';

import {
  MessagesModule,
  DropdownModule,
  ButtonModule
} from 'primeng/primeng';
import { SwiperModule } from 'angular2-useful-swiper';

import { IboxToolsComponent } from './common-components/ibox-tools.component';
import { FocusDirective } from './focus.directive';


@NgModule({
  imports: [
    CommonModule,
    MessagesModule,
    DropdownModule,
    ButtonModule,
    FormsModule,
    ReactiveFormsModule,

    SwiperModule

(same in Exports)

**Comment by udos86** [comment]
@dakipro Ok, thanks so far for your code. I'll check it out and let you know.

**Comment by dakipro** [comment]
thank you!
If I can help somehow, please let me know. I just noticed that I am not using the latest version of angular, I have     "@angular/common": "~2.0.0",

**Comment by udos86** [comment]
@dakipro Ok, I can confirm your problem and that this is likely a bug. At the moment reimport of `DynamicFormsCoreModule` is prevented as described in the [official documentation](https://angular.io/docs/ts/latest/guide/ngmodule.html#!#prevent-reimport). However it gets really trick here as all UI modules do import it itself. I'll try to deliver a bugfix as soon as possible!

**Comment by udos86** [comment]
@dakipro I've added a fix in development branch. I also added an async example in the demo application. Please have look at a6485ce. This chang will land in `1.3.3`.

Thanks for finding this out!
