### ISSUE TITLE
Create fields based on ajax/rest response

### ISSUE THREAD

**Issue by dakipro** [udos86/ng2-dynamic-forms#213]
Hi,
can we set fields after the form is initialized, with the data returned from the ajax/rest service?
F.eks. i have a model where customer can manually create fields needed for the form, f.eks. "purchase-date" and "is-sold" etc. So the form layout is unknown before data comes from server. 
Would this be solved when/if observable functionality comes?
Regards,
Dalibor

**Comment by JBusch** [comment]
It is already possible. You can just map over your resource and dynamically add the fileds to an model array which you then use for initialising your form.

**Comment by udos86** [comment]
@JBusch Thanks for helping out!
@dakipro Is waht @JBusch described what you're looking for?

**Comment by dakipro** [comment]
I would say yes. Not sure if this is the right way to do it, but what I quickly tried now was to initiate form with one array from the examples

this.formGroup = this.dynamicFormService.createFormGroup(ASYNC_EXAMPLE_MODEL); 
and then overwrite the form with another completely different array 
this.formGroup = this.dynamicFormService.createFormGroup(ASYNC_ANOTHER_EXAMPLE_MODEL);

And it worked fine. If I was just to change value of this.formModel with another array, error would be thrown complaining that "EditComponent - inline template:16:37 caused by: Cannot read property 'valueChanges' of null"
With calling the service and createFormGroup() after the change, new form was successfully built.

P.S. so far one of the best angular2 libraries, excellent documentation, clear examples, and not to mention the great support and speed of fixing issue. 
Keep up the great work!

**Comment by udos86** [comment]
@dakipro Thank you for your kind words. You gave yourself the correct answer! Please let me know if there's anything going wrong!

**Comment by alzdrak** [comment]
Sorry for opening this again, but this is exactly my scenario. I tried using your async example to load dynamic forms from a post request, but keep getting the error: 

> ERROR TypeError: Cannot read property 'valueChanges' of null

`DynamicFormControlModel[]` is obviously empty at first, until the async data is returned. So my question is, how do I create a form with an empty array? eg.

`this.formGroup = this.dynamicFormService.createFormGroup([]);`

**Comment by alzdrak** [comment]
Or rather do you have any realworld async examples that gets form layout from server request after the view has already been loaded, and then builds the form layout with that data? 

This also means that FormGroup cannot be initialized during ngOnInit or the constructor and only needs to be instantiated when the data is returned from the server. By not instantiating it in the constructor leaves me with this error:
> Uncaught (in promise): Error: formGroup expects a FormGroup instance.

**Comment by udos86** [comment]
@alzdrak 

I don't see any problems here. 

You just initialize your `FormGroup` as soon as your async operation is done:

`loadJSON().then(json => this.formGroup = this.formService.createFormGroup(this.formModel));`

Just place a `*ngIf="formrGroup"` directive your `<form>` and you're ready to go.

**Comment by alzdrak** [comment]
Wow thanks for the quick response!! That works getting rid of the error, however the view doesn't actually update. The controls are definitely added on the formGroup:

![image](https://user-images.githubusercontent.com/1562335/27355445-54588ad8-560b-11e7-95b1-c1f6834b1fd6.png)

They just don't update the actual view. Am I missing some sort of updateView() call or something?

Thanks again!

**Comment by alzdrak** [comment]
Wow thanks a lot! This led me to the right answer. Sometimes you just have to take a break and come back again to see your mistakes.
