### ISSUE TITLE
Unique ids for checkbox + label in dynamic groups

### ISSUE THREAD

**Issue by johngrimsey** [udos86/ng2-dynamic-forms#214]
Possible it's my incorrect usage...

I have a dynamic array of FormGroups each containing a DynamicCheckboxGroupModel. Each checkbox has an id (for day of the week).

When rendered click events on labels correctly activate the first element on the page with matching id which sometimes is the wrong element. My problem is that if I create unique ids I can't bind data to the form without quite a lot of work to match data to fields via dynamic ids.

We may need dynamically generated unique ids?

Thanks for all your work on this, really great library.

**Comment by udos86** [comment]
@johngrimsey Thanks for pushing the envelope :-)

I'm not sure if I do fully understand your problem. Could you please show some HTML and explain what you're trying to achieve?

Currently all element groups of an form array do not get an id as this would lead to invalid markup. That's why I originally added `DynamicIdDirective`.

**Comment by johngrimsey** [comment]
Sure!

<img width="417" alt="screen shot 2016-12-20 at 13 13 46" src="https://cloud.githubusercontent.com/assets/898591/21351777/51633768-c6b6-11e6-8991-6e4242963cbc.png">

In this example, clicking any of the _labels_ in the second group results in the corresponding checkbox of the _first_ group being selected rather than the checkbox next to the clicked label.

Is the `DynamicIdDirective` something I should be using in this case to prevent non-unique ids on the checkboxes?

**Comment by udos86** [comment]
@johngrimsey Ok thanks. Actually the focus behavior is fully controlled by the browser. There should be no need for you to use `DynamicIdDirective` as this is just an internal utility. Could you maybe post the corresponding markup?

**Comment by johngrimsey** [comment]
All the markup's coming from the `<dynamic-form-basic-control>` directive!  

The problem appears to be the checkboxes aren't receiving unique ids and so the first id matches in the DOM are those which are referenced by labels (adhering to the rule that an `id` attribute must be unique).

**Comment by udos86** [comment]
@johngrimsey Ok, I think do understand now. One solution could be to wrap all checkbox inputs in `ui-basic` in the `label` tag like it's done in `ui-bootstrap`.

**Comment by udos86** [comment]
@johngrimsey Yep, that should do it.

**Comment by johngrimsey** [comment]
Good plan, I was hoping that'd be the answer :)
