### ISSUE TITLE
Further customization of template/layout (individual field)

### ISSUE THREAD

**Issue by dakipro** [udos86/ng2-dynamic-forms#219]
Hello again,
how could one change template and render a bit different layout for fields, f.eks. having an additional div around the input, something like this

&lt;div class="form-group"
&lt; label class="col-sm-2 control-label">Description&lt;/label>
&lt;div class="col-sm-10">
&lt;input type="text" id="description" class="form-control" formControlName="description">
&lt;/div>
&lt;/div>

Perhaps by having option to inherit Dynamic*Modules and manipulating the html manually? 
Or maybe allowing some styling options like "LabelPrefix", "LabelSufix" and same for the input, where we could set some html manually?
Or perhaps having a custom component/html based on the libs file, that could be provided to the Dynamic*Modules as a replacement and/or template, something like
&lt;div id="#div1">
&lt;ul>
&lt;li>{{ label }}&lt;/li>
&lt;li> {{ input }}&lt;/li>
&lt;/ul>
&lt;/div>
Cheers!

**Comment by udos86** [comment]
@dakipro 

If you're looking for markup similar to the one you posted above, check out the `ui-bootstrap` package. It unobtrusively renders completely valid Bootstrap markup while giving you a lot of freedom for custom layouts (via CSS classes).  You can add `prefix` and `suffix` properties to your `DynamicInputModel`, too.

Furthermore you can use transclusion for adding markup after your form control. In form arrays you could even use `template` tags for adding additional elements (as shown in examples).
 
However further dynamic manipulation of markup is intentionally limited as this would make the library unnecessary complex. 

If you don't like any of the existing templates you could create your own, as last resort.

**Comment by udos86** [comment]
@dakipro Please have a look at new version `1.3.4`. Adding custom markup / templates has become a bit more powerful.
