### ISSUE TITLE
The select box does not display the first option

### ISSUE THREAD

**Issue by ht89** [udos86/ng2-dynamic-forms#220]
Hello @udos86, may I ask if there's a way to display the first option in the the select box or it is my fault? Thank you a lot for your help.

**Comment by udos86** [comment]
@ht89 Hi! You just need to set the `value` property correctly:

```
    new DynamicSelectModel<string>({

        id: "mySelect",
        options: [
            {
                label: "Option 1",
                value: "option-1",
            },
            {
                disabled: true,
                label: "Option 2",
                value: "option-2"
            },
            {
                label: "Option 3",
                value: "option-3"
            }
        ],
        value: "option-1"
    }),
```

**Comment by ht89** [comment]
Hello @udos86, thanks for your reply. But that does help. I think the reason is because I use bootstrap 4 instead of 3.

**Comment by udos86** [comment]
@ht89 Thanks for the kind words! I really haven't tried out Bootstrap 4 yet but I actually cannot think of reason why it shouldn't work there either.

**Comment by ht89** [comment]
@udos86 No worries :D

**Comment by ht89** [comment]
@udos86 actually your example does solve my problem. Thanks 👍  Not sure why it did not work the first time. It must be my mistake. At first, the select box displayed only the options retrieved from a DB and thus the select did not display the first option. Now it can after I added a static option.
