### ISSUE TITLE
Validation displayed without touching the fields

### ISSUE THREAD

**Issue by aluengo** [udos86/ng2-dynamic-forms#221]
Hello,

I'm creating a dynamic form using DynamicFormsCoreModule and DynamicFormsBootstrapUIModule.

For creating my DynamicFormGroupModel I'm using DynamicInputModel and including `validators: { required: null }` for every field. On my .html I'm adding the following code:

`<dynamic-form-bootstrap-control *ngFor="let controlModel of dynamicForm" 
  [controlGroup]="myForm" 
  [model]="controlModel"
  [hasErrorMessaging]="controlModel.hasErrorMessages">
</dynamic-form-bootstrap-control>`

The thing is that everything works OK but validation error is shown as soon as my page is loaded, without touching the fields. One I type in the error message disappears, but it's annoying it is displayed beforehand.

Is there anything I'm doing wrong?

Thx in advance!

**Comment by udos86** [comment]
@aluengo This is pretty weird, because actually this cannot happen.

Here ist the template code that controls wether the error messages are shown or not:
```
    <div *ngIf="hasErrorMessaging" class="has-error"
         [class.hidden]="!control.touched || hasFocus || isValid"
         [ngClass]="[model.cls.element.errors, model.cls.grid.errors]">

        <span *ngFor="let message of errorMessages" class="help-block">{{message}}</span>

    </div>
```

As you can see, as long as the control is not touched the CSS class `hidden` is applied. 

Have you included the Bootstrap stylesheet? If so, have you compared your code to Bootstrap example? There it's working as expected.

Thanks for trying out the library!

**Comment by aluengo** [comment]
Yes, I have included the CSS...I'm using Bootstrap 4.0.0-alpha.5. May be is that the issue?

I've reviewed the example many times and all I've done seems to be correct comparing to that one. That's why I'm lost and have decided to to write you.

Apart from that the library is great. Thank you!

**Comment by aluengo** [comment]
Hello again,

You were right, the reason must be the CSS. I've inspected the code and "hidden" class was applied. I've just defined a hidden class in my global CSS and now works great.

Thank you!!

**Comment by udos86** [comment]
@aluengo Great to hear! Thanks for your kind words! Merry X-mas to Madrid!
