### ISSUE TITLE
Pre-populating values to array group

### ISSUE THREAD

**Issue by dakipro** [udos86/ng2-dynamic-forms#225]
Hello again. I have one DynamicFormArrayModel containing two fields DynamicInputModel({ id: "fieldName", and DynamicSelectModel<string>({ id: "type" ... And it works fine when I initiate the form. What I want to achieve now is to prepopulate values for one model. 

F.eks. I have a category model that has two fields "name" and "type", one is text second is dropdown and 
I can have x number of them. I need to prepopulate them after I fetch them from the server. I tried to access the array template via this.arrayModel.addGroup and insertGroup(), but I noticed that they take only the number value. Is there any example on how to add new row in arrayModel with prepopulated values?
Do I need to create a new array "template", ie to re initialize the form once again? (and how to do that without creating different template then those two fields?)

I have a few more questions and suggestions, but I might be able to figure them out later once I figure out how  to manipulate values in arrayModel (f.eks. change order of elements).

Another issue is that I cannot run downloaded demo, but that could be due to my local node installation or something. 

This library saved me a lot of time manually creating logic, thank you for writing it!

**Comment by udos86** [comment]
@dakipro I'm not sure if I fully understood your problem. But here's what I guess would be a valid solution:

**1.** You should always manipulate a form array via `DynamicFormService`:

`this.formService.addFormArrayGroup(this.arrayControl, this.arrayModel);`

**2.** You can update the value of any control in a form array like you would  do it for any `DynamicFormValueControl` in general:

`this.arrayModel.get(1).group[0].valueUpdates.next("This is the next value");`

See documentation on [form arrays ](https://github.com/udos86/ng2-dynamic-forms#form-arrays)and [model value updates](https://github.com/udos86/ng2-dynamic-forms#model-bindings-and-control-references)

**Comment by dakipro** [comment]
Thanks,
I was trying what you mentioned but got stuck with either adding new arrays/fields or with updating existing form elements. 

What I am trying to do is populate one array dynamically with data from the server. I guess I should use Json Import?
[dynamic-forms.txt](https://github.com/udos86/ng2-dynamic-forms/files/676758/dynamic-forms.txt)

Attached is the relevant code, I really appreciate your time, I hope I am almost there with the solution

**Comment by udos86** [comment]
@dakipro Ok, from what I've seen your code looks pretty good.

In my opinion the error must be in here:
```
this.dynamicFormModel = this.drawDynamicFieldsFormTemplate();
this.dynamicFormGroup = this.dynamicFormService.createFormGroup(this.dynamicFormModel);

this.arrayControl = <FormArray>this.dynamicFormGroup.get("dynamicFields");
this.arrayModel = <DynamicFormArrayModel>this.dynamicFormService.findById("dynamicFields", this.dynamicFormModel);

//and then I update values with what I get from the server
this.arrayModel.get(0).group[0].valueUpdates.next("test"); // fieldName
this.arrayModel.get(0).group[1].valueUpdates.next("text"); // type
this.dynamicFormGroup = this.dynamicFormService.createFormGroup(this.dynamicFormModel);
```

You should obtain the `arrayControl` reference and  update the values **after** you created the `FormGroup`. At the point you're creating the `dynamicFormGroup` the second time, `arrayControl` references a `FormControl` that is not bound to the DOM anymore.

**Comment by dakipro** [comment]
the quote of code you pasted is "as-is" from the controller, after the FormGroup is created. And it works fine as written here. But once I add 

this.arrayModel.get(0).group[0].valueUpdates.next("test"); // fieldName
this.arrayModel.get(0).group[1].valueUpdates.next("text"); // type
this.dynamicFormGroup = this.dynamicFormService.createFormGroup(this.dynamicFormModel);

then I cannot add additional array items using this code

  insertItem(context: DynamicFormArrayModel, index: number) {
    this.dynamicFormService.insertFormArrayGroup(index, this.arrayControl, context);
  }

I get error 
Error in ./DynamicFormBootstrapComponent class DynamicFormBootstrapComponent - inline template:0:1240 caused by: Cannot find control with path: 'dynamicFields -> 1'

So I can have either data from the server, or option to dynamically add fields :)

I tried to set up plunker to isolate it but i failed, couldn't install ng2-dynamic-forms library

**Comment by dakipro** [comment]
Here is the visual part of what I am trying to achieve
![screenshot 2016-12-29 13 28 40](https://cloud.githubusercontent.com/assets/1586291/21543901/d1c58c06-cdca-11e6-8848-8557b969aec2.png)

Users can manually add "group" of fields and store them in database, then manipulate values

**Comment by udos86** [comment]
@dakipro That's what I meant:
```
this.arrayModel.get(0).group[0].valueUpdates.next("test"); // fieldName
this.arrayModel.get(0).group[1].valueUpdates.next("text"); // type
this.dynamicFormGroup = this.dynamicFormService.createFormGroup(this.dynamicFormModel)
```

You're creating another new `dynamicFormGroup` while your `arrayControl` still holds a reference to the old `FormControl`. You need to update your `arrayControl` reference after you created the `dynamicFormGroup` for the second time.

**Comment by dakipro** [comment]
Yaay, I understood it now  and it looks like it works as expected :)
So after getting the model from the server I basically need to do this

//initialize the form with "empty" fields
              this.dynamicFormModel = this.drawDynamicFieldsFormTemplate(null);
              this.dynamicFormGroup = this.dynamicFormService.createFormGroup(this.dynamicFormModel);

              this.arrayControl = <FormArray>this.dynamicFormGroup.get("dynamicFields");
              this.arrayModel = <DynamicFormArrayModel>this.dynamicFormService.findById("dynamicFields", this.dynamicFormModel);

              //populate the fields with data from the server, - I would loop trought all the array elements and then populate its fields
              this.arrayModel.get(0).group[0].valueUpdates.next("test");
              this.arrayModel.get(0).group[1].valueUpdates.next("text");
              this.dynamicFormGroup = this.dynamicFormService.createFormGroup(this.dynamicFormModel);

              this.arrayControl = <FormArray>this.dynamicFormGroup.get("dynamicFields");
              this.arrayModel = <DynamicFormArrayModel>this.dynamicFormService.findById("dynamicFields", this.dynamicFormModel);

**Comment by udos86** [comment]
@dakipro Yep, that's it. In fact, you only need to update `arrayControl` reference. `arrayModel` is still the same.

**Comment by udos86** [comment]
By the way: next lib version will contain a method to move elements of a form array up and down.

**Comment by dakipro** [comment]
that is awesome man, lib is really awesome (and the support as well :) )
Please open a paypal/donate button, you saved a lot of people a lot of time

**Comment by udos86** [comment]
@dakipro Thanks, no problem! I'll keep on doing this for free as long as my spare time allows.

**Comment by dakipro** [comment]
Hi @udos86 ,
after recent update of angular this doesn't compile 
this.arrayModel.get(0).group[0].valueUpdates.next("test"); // fieldName
it says that
[ts] Property 'valueUpdates' does not exist on type 'DynamicFormControlModel'.

I use it in code like this 

```
private populateDynamicFieldsFromTemplate(template){
  if(typeof template!=="undefined"){
    for (let i = 0; i < template.length; i++) {
      if(i > 0){
        this.dynamicFormService.insertFormArrayGroup(i, this.arrayControl, this.arrayModel);
      }
      this.arrayModel.get(i).group[0].valueUpdates.next(template[i].id);
       this.arrayModel.get(i).group[1].valueUpdates.next(template[i].name);
       this.arrayModel.get(i).group[2].valueUpdates.next(template[i].type);
    }
  }
}
```

When I console.log(this.arrayModel.get(i).group[0])  I get "DynamicInputModel" in console (and not "DynamicFormControlModel" as TS is implying. 
Is there update on how this should be used now?
Thanks!

**Comment by udos86** [comment]
@dakipro Thanks for your message! 

There has been a typings update to `DynamicFormArrayModel` in `1.3.17` which does accept now any `DynamicFormControlModel` and not only `DynamicFormValueControlModel` (see #289).

In order to use `valueUpdates` properly you need to cast you model...
