### ISSUE TITLE
example app is failing

### ISSUE THREAD

**Issue by willyhakim** [udos86/ng2-dynamic-forms#230]
I followed the instructions and downloaded the example. When I ran `npm run tsc` I got the following errors.
`example/app/app.component.e2e.spec.ts(4,9): error TS2304: Cannot find name 'browser'.
example/app/app.component.e2e.spec.ts(8,16): error TS2304: Cannot find name 'browser'.
example/app/app.module.ts(11,43): error TS2307: Cannot find module '@ng2-dynamic-forms/ui-kendo'.
example/app/basic/basic-example.component.e2e.spec.ts(9,9): error TS2304: Cannot find name 'browser'.
example/app/basic/basic-example.component.e2e.spec.ts(16,20): error TS2304: Cannot find name 'element'.
example/app/basic/basic-example.component.e2e.spec.ts(16,28): error TS2304: Cannot find name 'by'.
example/app/basic/basic-example.component.e2e.spec.ts(22,9): error TS2304: Cannot find name 'element'.
example/app/basic/basic-example.component.e2e.spec.ts(22,21): error TS2304: Cannot find name 'by'.
example/app/basic/basic-example.component.e2e.spec.ts(26,55): error TS2346: Supplied parameters do not match any signature of call target.
example/app/basic/basic-example.component.e2e.spec.ts(37,24): error TS2304: Cannot find name 'element'.
example/app/basic/basic-example.component.e2e.spec.ts(37,32): error TS2304: Cannot find name 'by'.
example/app/basic/basic-example.component.e2e.spec.ts(38,44): error TS2346: Supplied parameters do not match any signature of call target.
11:37:06 AM - Compilation complete. Watching for file changes.
`

Any idea what's happening?

**Comment by udos86** [comment]
@willyhakim The type errors occur because of missing types for Protractor API. Please ignore them  and run the app with `npm start`! Before please pull the latest commit 387f034.

**Comment by willyhakim** [comment]
You are simply awesome! Thanks for the quick fix

**Comment by udos86** [comment]
@willyhakim No problem, thanks!
