### ISSUE TITLE
Translated Labels

### ISSUE THREAD

**Issue by ht89** [udos86/ng2-dynamic-forms#235]
Hello @udos86, may I ask if there's a way to have translated labels for form fields? Thank you a lot.

**Comment by udos86** [comment]
@ht89 

At the moment I cannot say if this should be a concern of the library, at all.

However, you can try this:

Use Angular core [i18n](https://angular.io/docs/ts/latest/cookbook/i18n.html ) and add corresponding label markup

```
new DynamicInputModel({
    
    id: "myInput",
    label: "<h1 i18n>Hello i18n!</h1>"
})
```

**Comment by ht89** [comment]
Hi @udos86, 
I really appreciate your fast response. However, because I use ng2-translate, my workaround is to define <label> before <dynamic-form-bootstrap-control> in my html file. Anyway, I think your response will help others when they need translated labels. Kind regards.

**Comment by ht89** [comment]
Hi @udos86,
I'd like to let you know that your suggestion is still displayed as a string, so the text inside the tag still cannot be translated. I found it out when trying to translate a select option using your suggestion. Do you know what's wrong? Thanks so much.

**Comment by udos86** [comment]
@ht89 Thanks for the feedback! I guess I'll have to dive deeper into Angular's i18n feature to give you a solid explanation. 

I'm still wondering why they did not include a translation service like angular-translate did back then.
