### ISSUE TITLE
Question: MdInputContainer error..?

### ISSUE THREAD

**Issue by sadplace** [udos86/ng2-dynamic-forms#236]
Hi,
i am using angular 2.0.0 and material 2.0.0-alpha.9-3 and i follow your instruction and compare with you demo but i get this error:

ERROR in [default] ...\node_modules\@ng2-dynamic-forms\ui-material\src\dynamic-form-material.component.ts:3:21
Module '".../node_modules/@angular/material/index"' has no exported member 'MdInputContainer'.

Can you please help me? Is it the angular or material version?
Thanks

**Comment by udos86** [comment]
@sadplace Yep, please update to Angular Material beta.1.

**Comment by sadplace** [comment]
Thanks :)

**Comment by kbchandiran** [comment]
same error showing with Angular Material 2.0.0-beta.6
