### ISSUE TITLE
use of ng2-dynamic-forms in a generic manner?

### ISSUE THREAD

**Issue by gms1** [udos86/ng2-dynamic-forms#242]
Hi,

First of all thank you for this great module!

For a part of my application I need the possibility to build a form completely generically. 
The client should get the form structure from a backend plugin, together with a JSON object for the initial values. The modified JSON object should be sent back to the backend plugin.

The mapping of the form values to the properties of the JSON object could be set up via the 'id' field. E.g. a JSON pointer could be used as 'id' field.
So far this should not be a problem, but in case of an array form, this is probably not going to be that simple.

However, at the moment, there is no way to create generic buttons, such as to delete a row from an array form. This generic buttons would have to trigger events in the context of the respective array form and the current row

Do you consider this use case as within the scope of this module?	

At the moment I'm also wondering how the JSON import works with regard to the 'createGroup' function, or is this method obsolete if an 'originGroup' has been defined? Couldn't the 'originGroup' be defined in the first-place?

Regards
Guenter

**Comment by gms1** [comment]
Now I have finished the first version of my "GenericFormService" having the following functionality:

FindById (id: string, arrayIndex ?: number): DynamicFormControlModel | undefined
  which traverses the full ControlModel-tree to find the corresponding DynamicFormControlModel even if it resides inside nested DynamicForm(Group|Array)Models

initFormContent(content: any, pointerPrefix?: string);
getFormContent(content: any, pointerPrefix?: string);

  traverse the full ControlModel-tree and get/set the values from/to the JSON object,
  by using a JSON pointer as 'id' field for all ValueControlModels. Inside an array form, the ValueControlModels must provide a JSON  pointer having a marker to be replaced by the array index

I see this functionality is really not generic enough to be part of this library.

Regarding the buttons I talked above: I am planing to provide a handful templates for array1...arrayN on the client side, which can be addressed by the backend by using the corresponding array form IDs...

So although this was all more difficult than I hoped, I should now have a more than viable solution in a very short time. 
Many thanks, I am very happy to have found your module!

Guenter

The case can be closed, or perhaps serve as the basis for future extensions?

**Comment by udos86** [comment]
@gms1 Alright, thanks for your message! 

This would habe been the response to your initial post:

> 
> If you did not already have a look at the chapter on JSON import/export in [README.md](https://github.com/udos86/ng2-dynamic-forms#json-export-and-import), please do so. 
> 
> The library offers you simple helper functions to export a form model to JSON and to import a form model from JSON via `DynamicFormService`.   
> 
> You can find a sample implementation [here](https://github.com/udos86/ng2-dynamic-forms/blob/master/example/app/basic/basic-example.component.ts).
> 
> > Do you consider this use case as within the scope of this module?
> 
> Buttons for form array groups can be defined via custom templates as described in [README.md](https://github.com/udos86/ng2-dynamic-forms#form-arrays). 
> 
> In my opinion UI concerns and pure model information should not be mixed up in dynamic form model. This has been discussed [here](https://github.com/udos86/ng2-dynamic-forms/issues/181).
> 
> > At the moment I'm also wondering how the JSON import works with regard to the 'createGroup' function, or is this method obsolete if an 'originGroup' has been defined? Couldn't the 'originGroup' be defined in the first-place?
> 
> First of all: JSON import works even when adding form arrays! But you're right, there's a bit of redundancy flaw here. The `originGroup` property is internally created in order to provide correct JSON export/import functionality. This is one of the last corners of the library where I'll   
> 
>

**Comment by udos86** [comment]
@gms1 If you're planning to develop some helpful extension for the library I'd be happy to discuss them here.

**Comment by gms1** [comment]
I will use this package very intensively in the next months and would be glad if I can contribute.

But this use-case, where the client is not supposed to know anything about the form other than the (JSON) form definition and an anonymous object whose content should be 
filled and displayed in the form, is really very special.
My abuse of the 'id' field as a json-pointer is hackish but useful; introducing an additional json-pointer attribute would be redundant for this particular use-case and useless for all others.

If desired, and I have worked with this package for some time, I would like to prepare an example for this use-case, which could others help to get started

Guenter

**Comment by udos86** [comment]
@gms1 Great to hear! Alway interested in example using the library!

**Comment by Ellipizle** [comment]
@gms1 Your implementation (plunkr sample) will really be helpful. I am on the verge of doing something like that too.
