### ISSUE TITLE
Question: Example pointing to node_modules and now the example code

### ISSUE THREAD

**Issue by sadplace** [udos86/ng2-dynamic-forms#243]
Hi, Sorry to bother again,

First, thanks for this lib :) 
I am trying to run you example in my machine (angular2 + material) but the example is pointing to the "@ng2-dynamic-forms" (in node_modules folder) and not the code it self. Is there any place where i can change that?
I want to see how this works and if i can add custom components.

Thanks :)

**Comment by udos86** [comment]
@sadplace No problem! If you'd like to change the library code itself and test it, please run `npm run build` from the root of your project folder and wait for your browser window to reload automatically.

**Comment by sadplace** [comment]
ok thx, i'll try that :D

**Comment by sadplace** [comment]
I was able to put it running, thanks for that :)
I have 2 questions:
- in the input, the inputType does not seems to be working, i say a input is of type password and nothing happens,
- i try to add another control and i get an error "Unexpected token <". i think i need to add the component to the bundle, can you give me some hints ?

Thanks :)

**Comment by udos86** [comment]
@sadplace 

> in the input, the inputType does not seems to be working, i say a input is of type password and nothing happens

It seems to be working fine for me. The corresponding property is named `inputType`:

```
    new DynamicInputModel({

        id: "basicInput",
        inputType: "password",
        label: "Example Input",
        placeholder: "example input",
    })
```

> i try to add another control and i get an error "Unexpected token <". i think i need to add the component to the bundle, can you give me some hints ?

Can you describe a bit more in detail what you are doing? Adding a new type of `DynamicFormModel` always requires a corresponding component to be added to a UI template file.
