### ISSUE TITLE
[Question] How to implement semantic-ui

### ISSUE THREAD

**Issue by jamiemac87** [udos86/ng2-dynamic-forms#244]
We are using [semantic ui](http://semantic-ui.com/) on our project, and I was wondering what would be involved in creating a new semantic ui theme for the library? Or could this potentially be done using custom templates?

**Comment by udos86** [comment]
@jamiemac87 Nice question :-) I had already started working on a package for Semantic UI when I abandoned it in favor of Kendo UI. There's [this](https://github.com/vladotesanovic/ngSemantic) wrapper library for Angular 2 but I guess it's not an official version, isn't it? Using only the core library would not work as it heavily relies on jQuery. I'll sit down and give it another try. I assume that there'll be a `ui-semantic` package pretty soon :-)

**Comment by jamiemac87** [comment]
Thanks @udos86 It's not an official library but it does have implementations for the main input types we need for the project we are working on (input, checkbox, toggle, select etc). Is there a way we could approach the problem if using the wrapper library mentioned is not feasible?

I wouldn't mind chipping in and helping with development if it speeds things up

**Comment by udos86** [comment]
@jamiemac87 Alright, that's fine! I'll push a draft within the next couple of days. You can then review the template and example.

**Comment by udos86** [comment]
@jamiemac87 I'd like you to review my draft for a first version of `ui-semantic` in 9a34a2d. I realized that there are several flaws in `ng-semantic` which do pretty much limit the configuration options for all form elements.

**Comment by jamiemac87** [comment]
@udos86 what sort of limitations do you envisage? I'm not able to build/run the example on the development branch. I get the following error from `tsc`

`example/app/app.module.ts(15,46): error TS2307: Cannot find module '@ng2-dynamic-forms/ui-semantic'`

**Comment by udos86** [comment]
@jamiemac87 Please run `npm run build` before `npm run tsc` and `npm start` to build the `ui-semantic` package. There are limitations in configuring the form controls (label, placeholder, that's mostly it). Disabling form controls does not work dynamically. Some CSS classes do not work the way they used to in core Semantic UI. Please have a look. You probably got some improvements as an experienced user of Semantic UI.

**Comment by udos86** [comment]
@jamiemac87 I also can't get the radio group to work correctly. When choosing the value of the corresponding `FormControl` always is set to `true`instead of the actual string value.

**Comment by jamiemac87** [comment]
@udos86 from running the example there seem to be a few issues (checkboxes not checking, layout issues). I may have a go at implementing a solution without using the `ng-semantic` wrapper and see where I get to.

**Comment by udos86** [comment]
After some more experimenting this issue is closed until there's an official release of Semantic UI for Angular 2 or a more reliable library than ngSemantic.
