### ISSUE TITLE
Use to attr in html files

### ISSUE THREAD

**Issue by jainrohit4ever** [udos86/ng2-dynamic-forms#246]
Hi @udos86 ,

I am trying to read and understand the code to add some custom components. In some html components like input, native html5 attributes for input are used like attr.max, attr.min. Why do these not work directly without attr. And how does adding attr helps.

Thanks,
Rohit

**Comment by udos86** [comment]
@jainrohit4ever That's simply because Angular does not support all native input attributes as native properties. Have a look at the [official docs](https://angular.io/docs/ts/latest/guide/template-syntax.html#!#other-bindings) for further explanation.
