### ISSUE TITLE
template is throwing exception with array field

### ISSUE THREAD

**Issue by nomi-ramzan** [udos86/ng2-dynamic-forms#250]
I am trying to implement multi forms in different tabs. without template it is working fine. but when i am defining template it es throwing exception 

> ./DynamicFormBootstrapComponent class DynamicFormBootstrapComponent - inline template:0:1634 caused by: Expression has changed after it was checked. Previous value: 'undefined'. Current value: '[object Object]'.
[Plunker](http://plnkr.co/edit/nOiAbO?p=preview) of my usecase.
**Comment template to run this example without any error**

**Comment by udos86** [comment]
@nomi-ramzan Ok, this is a bit tricky. You can do the following to make it work:

```
export class NgbdTabsetSelectbyid implements OnInit {
    tabs: any[] = [
        {title: 'tab 1'}
        , {title: 'tab 2'}
    ]

    constructor(private formService: DynamicFormService, private changeDetectorRef: ChangeDetectorRef) {}

    ngOnInit() {
        for (var tab of this.tabs) {
            tab.formModel = [
                new DynamicCheckboxModel({id: "checkbox", label: "I do agree"}),
                new DynamicSelectModel({
                    id: "select",
                    label: "Example Select",
                    value: "option-3"
                    ,
                    options: [{label: "Option 1", value: "option-1",}, {
                        label: "Option 2",
                        value: "option-2"
                    }, {label: "Option 3", value: "option-3"}]
                }),
                new DynamicFormArrayModel({
                    id: "myFormArray",
                    initialCount: 5,
                    createGroup: () => {
                        return [new DynamicInputModel({id: "formArrayInput", label: "Form Array Input"})];
                    }
                })
            ];
            tab.formGroup = this.formService.createFormGroup(tab.formModel);
        }

        this.changeDetectorRef.detectChanges();
    }
}
```

**Comment by nomi-ramzan** [comment]
> this.changeDetectorRef.detectChanges();

Hi @udos86 thank you for your quick response. I tried this solution, also added in plunker but i am getting `this.changeDetectorRef`  **undefined** in `ngOnInit()` function.

**Comment by udos86** [comment]
@nomi-ramzan As shown above you need to import it from `@angular/core` and inject it into the constructor as a dependency!

`import { ChangeDetectorRef } from "@angular/core"`

`constructor(private formService: DynamicFormService, private changeDetectorRef: ChangeDetectorRef) {}`

**Comment by nomi-ramzan** [comment]
I also tried your solution even i called 

> this.changeDetectorRef.detectChanges();
on tab change event. Still making problem. 
You can check my plunker to see the exact problem when you will change tab specially.
I also post [question](http://stackoverflow.com/questions/41738877/how-can-i-use-template-in-tabs-loop-in-angular-2)  on stackoverflow.

**Comment by udos86** [comment]
@nomi-ramzan It perfectly solves your original exception concerning change detection. 

Your functions to add and remove items do not work because your expecting the wrong parameters:

```
<template modelId="myFormArray" let-context="context" let-index="index">
    <button type="button" (click)="removeItem(context, index)">Remove Item</button>
    <button type="button" (click)="addItem(context, index + 1)">Add Item</button>
</template>
```

`context` is a reference to the `DynamicFormArrayGroupModel` not to the `tab`.

```
  addItem(tab:any, context:any){
    this.formService.insertFormArrayGroup(0, tab.fGroup.get(context.id), context);
    // this.formService.addFormArrayGroup(this.arrayControl, this.arrayModel);
  }
```

**Comment by udos86** [comment]
@nomi-ramzan Ok, sorry, you're right. The problem's still there. I'll do some further investigation.

**Comment by thardy-pd** [comment]
The problem doesn't appear to have anything to do with tabsets because I get the problem with a simple FormGroup.  It seems to be any sort of template used with an array of fields...

```
let fields: Array<DynamicFormControlModel> = [
      new DynamicFormGroupModel({
        id: "email",
        group: [
          new DynamicInputModel({
            id: "emailAddress",
            label: "Email",
            required: true,
           errorMessages: {
              required: "{{label}} is required.",
            }
          }),
          new DynamicInputModel({
            id: "emailConfirm",
            label: "Please confirm email address",
            required: true,
            errorMessages: {
              required: "{{label}} is required."
            }
          })
        ]
      })
];
```

I then use a simple template straight from the documentation...

    ```
<template modelId="email" let-id="id">
      <p>Just some custom markup for {{ id }}</p>
    </template>
```

I then receive the following...
error_handler.js:50 EXCEPTION: Error in ./DynamicFormBootstrapComponent class DynamicFormBootstrapComponent - inline template:0:5447 caused by: Expression has changed after it was checked. Previous value: 'undefined'. Current value: '[object Object]'.

**Comment by udos86** [comment]
@thardy-pd I cannot verify this as this is exactly the same I'm doing in the [bootstrap example](https://github.com/udos86/ng2-dynamic-forms/tree/master/example/app/bootstrap) and it's working fine there.

**Comment by udos86** [comment]
Internally templates need to be assigned in `ngAfterViewInit` to support libraries' custom template directives. 

The error you describe is thrown only in DevMode when a binding has changed after initialization while Angular's change detection has not been triggered. It is a [very well known](https://github.com/angular/angular/issues/6005) issue in the meantime.

However, in all my examples and tests I could not detect any problems so far.

**Comment by nomi-ramzan** [comment]
Hi 
Is there any way to define `modelId` dynamically ? like in your [Example](https://github.com/udos86/ng2-dynamic-forms/blob/master/example/app/bootstrap/bootstrap-example.component.html#L12) you defined static modelId `bootstrapFormArray`

**Comment by Ahsanmughal** [comment]
@udos86  can you provide the example of  multi forms in different tabs.

**Comment by udos86** [comment]
@Ahsanmughal Just check the Plunker linked above by @nomi-ramzan . It seems to be working fine now.
