### ISSUE TITLE
DynamicFormArrayModel all groups reacting

### ISSUE THREAD

**Issue by kirjai** [udos86/ng2-dynamic-forms#251]
Very helpful library, thanks for creating and maintaining it <3 

I am currently struggling with `DynamicFormArrayModel` in my form. I have a very similar situation to what is described in the readme, where I have buttons to add or remove an input group for every group in the dynamic array. Managed to get it working without much problems, however all fields react at the same time.. What I mean by that is if my `initialCount` is `1` and then i add another group with a button and the same input group repeated, if i start typing into any input from the first group, the same changes appear in the second group and vice versa..

<img width="627" alt="screen shot 2017-01-18 at 1 42 07 pm" src="https://cloud.githubusercontent.com/assets/9858620/22066230/f1673f46-dd83-11e6-9a4d-987bb93a8147.png">

the `DynamicFormArrayModel` is generated like this:
```
const parseField = (field): DynamicFormArrayModel => {
    return new DynamicFormArrayModel({
      id: field.someProp,
      initialCount: 1,
      createGroup: () => parsedChildFields;
    })
  }
};
```
Where `parsedChildFields` is of type `Array<DynamicInputModel>` that's generated beforehand.

Anything in particular stands out to you, that i might be doing wrong, that would eliminate the problem described above?

**Comment by udos86** [comment]
@kirjai Thanks for your nice message! 

We can fix your problem pretty quick. At the moment you're constantly returning the same instances of form controls in `createGroup()` : `createGroup: () => parsedChildFields;`

Instead you need to return new instances:

```
return new DynamicFormArrayModel(
        {
            id: field.someProp,
            initialCount: 1,
            createGroup: () => {
                return [
                    new DynamicInputModel({
                        
                        id: "myInput"
                        label: "input",
                    }),
                    new DynamicCheckboxModel({

                        label: "check",
                        id: "myCheckbox"
                    })
                ];
            }
        })
```

**Comment by kirjai** [comment]
Of course you were totally right, thanks for your help!
