### ISSUE TITLE
Issue when re-exporting a form model when  aot is enabled 

### ISSUE THREAD

**Issue by mak92** [udos86/ng2-dynamic-forms#257]
Hi Udo,

great work with this library, I really enjoy using it!

I have a question regarding the form export. I have a form array which I can save successfully when it is created for the first time. I use the method described in your documentation. I am then able to restore the form correctly too. All fields are filled in correctly.

When I add another field to the restored form though and I attempt to save it, the new field is in the model, however, the value of the field is **null**. 

I have noticed this behaviour only when aot is enabled. When I disabled aot i can save the form as many times as needed without any issues. 

Am I doing something wrong?

**Comment by udos86** [comment]
@mak92 Hi, thanks for your kind words!

I must admit that I haven't really dived deep into AoT and your issue looks like a more complex one. I'll do my best to uncover probable bugs with AoT but I can't give you a profound response at this point.

**Comment by mak92** [comment]
Hi Udo,

Thanks for getting back to me so quickly. Looking forward to hearing from you.

**Comment by udos86** [comment]
@mak92 No problem! Could you maybe give me some clues on how did your AOT compilation? Did you use Webpack or Rollup for bundling? I've started right away with AOT optimization in  bd12a37.

Would really appreciate any your experience here!

**Comment by mak92** [comment]
Yeah well Webpack I suppose as I am using angular-cli. At the time I was using v1.0.0-beta.26 of the cli. And the build was successful when running ng build --prod --aot.

**Comment by udos86** [comment]
@mak92 Ok, great to hear! I actually was expecting the aot build to break with the library! Thanks for the information!

**Comment by mak92** [comment]
Hi Udo, 

I hope all is well, I have checked ever version you have uploaded since raising this issue and I wanted to let you know that this still occurs.

**Comment by udos86** [comment]
@mak92 Thanks for your message! I'm very sorry that I've not been able to fix this. My job keeps me busy at the moment. Concerning AoT I've been trying to get Rollup running for everybody in the first place but did not succeed yet (#267).

**Comment by gms1** [comment]
@udos86
I do not think that this issue is in any way related to the mentioned compilation error. My own aot build using Webpack works very well and also the @angular/cli based aot build seems to basically work.
It would be the responsibility of the Angular compiler to keep the functionality the same, regardles whether jit or  aot has been used to compile the static Angular components, but in this case the application seems to reacts differently.
And between the @angular/cli jit-build and the aot-build, there are other differences, which are even more suitable for such problems. I think in the first place about the use of uglifyjs...

@mak92
Can you provide a public repository that can be used to reproduce the problem?

**Comment by udos86** [comment]
@gms1 Thanks for your help :-) I lately had to deal a lot with AoT and I'm aware of most of it's capabilities and it's flaws. I only wanted to make clear that I mainly worked on getting Rollup bundling to work and did not have the time to explore @mak92's complex problem. A live sample would really help!

**Comment by mak92** [comment]
@gms1 Thanks for your input, that makes sense and thats what I thought too. 

@udos86 @gms1 When I have a little bit of time I will create a public repo to reproduce the issue. I will let you know when it's available. 

Thanks.

**Comment by mak92** [comment]
@udos86 I just upgraded my project to use 1.3.17 and this issue appears to be resolved now. From my side this issue can be closed now. Let me know what you think. 

FYI for anyone running into any issues, it works when using: 

@angular/cli 1.0.0-rc.2
@ng2-dynamic-forms/core 1.3.17

**Comment by udos86** [comment]
@mak92 Alright, great to hear! Maybe this could have also been an issue of CLI...
