### ISSUE TITLE
Difference between grid and element in ClsConfig interface

### ISSUE THREAD

**Issue by jainrohit4ever** [udos86/ng2-dynamic-forms#260]
Hi, 

ClsConfig has 2 Cls attributes, grid and element.
Observed for input model:
element.label and grid.label both define same property ie input box label's class.
 
what is the difference between them?

**Comment by udos86** [comment]
@jainrohit4ever Hi! `cls.element.label` will assign css classes directly to the `<label>` element. However when you're using a UI library that comes with a grid system, e.g. Bootstrap, css classes for placing the element in the grid need to be appended to the element's container. So `cls.grid.label` is for placing the `<label>` in the grid. Have a look at the Bootstrap example for practical use.
