### ISSUE TITLE
Add a button in front of an input

### ISSUE THREAD

**Issue by ShamsUlAzeem** [udos86/ng2-dynamic-forms#264]
Hi guys! Out of every angular 2 dynamic forms library, you guys have the most versatile one 👍 .

I have a query though... Can I add a button in front of an input field? I have attached an image as well. Please let me know if you can help :)
![capture](https://cloud.githubusercontent.com/assets/17789400/22673704/97f07b74-ecfd-11e6-9283-afa01a45e87c.PNG)

**Comment by udos86** [comment]
@ShamsUlAzeem Hi! Thanks for your nice message!

At the moment a custom content / template is rendered after the actual form control. You could use CSS (`float`, Flexbox `order`, etc.). to position it the way you'd like. But I'm also thinking about adding a property to `DynamicTemplateDirective` for positioning.

**Comment by udos86** [comment]
@ShamsUlAzeem I've got great news! From `1.3.13` on you will be able to define where your template is placed: `'START'` or `'END'`

**Comment by ShamsUlAzeem** [comment]
Omg @udos86 you're so freaking awesome man!!! Thank you thank you thank you :) Keep it up man!!!! Really this is a really helpful library :D
