### ISSUE TITLE
Dynamic ModelId

### ISSUE THREAD

**Issue by Ahsanmughal** [udos86/ng2-dynamic-forms#265]
Hi
Is there any way to define modelId dynamically ? like in your [Example ](https://github.com/udos86/ng2-dynamic-forms/blob/master/example/app/bootstrap/bootstrap-example.component.html#L12 )you defined static modelId bootstrapFormArray

**Comment by minuz** [comment]
The modelId can be a property within your class. The `template` can access the class properties and therefore, you should be able to change the id of it dynamically.

**Comment by Ahsanmughal** [comment]
@minuz  , @nomi-ramzan  can you please provide me code example.

**Comment by udos86** [comment]
@Ahsanmughal At the moment you cannot dynamically append `modelId` to a template. It needs to be set by the moment where `ngAfterViewInit` is called. That's the lifecycle callback that assigns a template to a Component.

**Comment by nomi-ramzan** [comment]
@udos86 But in case of mix schema of form like `DynamicFormArrayModel`  and some other or more then one defined [here](https://github.com/udos86/ng2-dynamic-forms/blob/master/example/app/bootstrap/bootstrap-example.model.ts#L214) ?

**Comment by udos86** [comment]
@nomi-ramzan 

When you set `modelId` to the id of a ` DynamicFormArrayModel` the template is automatically rendered for every array item. You can exactly see this feature in the Bootstrap example.

Instead of using `modelId` on a template you can also use `type` to reuse it for every form control element of the same type:
```
import { Directive, Input, TemplateRef } from "@angular/core";

@Directive({
    selector: "template[modelId]"
})

export class DynamicTemplateDirective {

    @Input() modelId: string;
    @Input() type: string | null = null;

    constructor(public templateRef: TemplateRef<any>) {}
}
```

**Comment by udos86** [comment]
@nomi-ramzan Could you please specify your use case and what you're trying to achieve?

**Comment by nomi-ramzan** [comment]
@udos86  See in this [Example](http://plnkr.co/edit/iMgMbA?p=preview) now there is no way to define a model like this ?

**Comment by udos86** [comment]
@Ahsanmughal Thanks for the Plunker! So in this example you'd like to reuse the template for the second `DynamicFormArrayModel` as well, am I right?

**Comment by nomi-ramzan** [comment]
@udos86 yes exactly you got it right.

**Comment by udos86** [comment]
@nomi-ramzan Alright! There is bug in the current version `1.3.12`. I will deliver a fix

From `1.3.12`you will be able to assign template by type:

```
<template type="ARRAY" let-context="context" let-index="index">

    <div class="col-sm-4">

        <button type="button" class="btn btn-danger rounded" (click)="remove(context, index)">&#10005;</button>
        <button type="button" class="btn btn-default rounded" (click)="move(context, index, -1)">&#9650;</button>
        <button type="button" class="btn btn-default rounded" (click)="move(context, index, 1)">&#9660;</button>
        <button type="button" class="btn btn-success rounded" (click)="insert(context, index + 1)">&#43;</button>

    </div>

</template>
```

That way you can easily reuse a template for multiple `DynamicFormArrayModel`s.

**Comment by nomi-ramzan** [comment]
Glad to know. Thank you

**Comment by udos86** [comment]
@nomi-ramzan You can now use it. The property i called `modelType`. Please see [README.md](https://github.com/udos86/ng2-dynamic-forms#custom-templates).

**Comment by nomi-ramzan** [comment]
Thank you. I tested it and its working amazingly fine.

**Comment by nomi-ramzan** [comment]
@udos86 I have one question what about if i have two array controls and i want to use different template for each control [Plunker](http://plnkr.co/edit/e1urxi?p=preview) to make it more clear.
I also added one idea to take template id or type for controller defined inside file `model.ts line 54, 55`

**Comment by udos86** [comment]
@nomi-ramzan You would bind `modelId` instead of `modelType` then. Also thanks for your idea! However I would not like to mix pure model information with UI.
