### ISSUE TITLE
demo site does not work

### ISSUE THREAD

**Issue by shermanwaiwai** [udos86/ng2-dynamic-forms#268]
please fix

**Comment by udos86** [comment]
@shermanwaiwai Thanks for the hint and sorry for the inconvenience! Demo site is running again!

**Comment by k20human** [comment]
Hi,

It seems that it doesn't work again :(

**Comment by udos86** [comment]
@k20human It does :-) 

The URL has changed: http://ng2-dynamic-forms.udos86.de/example/index.jit.html (I already updated README.md)

**Comment by k20human** [comment]
Ok, it was a browser cache problem on my side ... Sorry

Maybe you can add a spinner on page loading too ?

**Comment by udos86** [comment]
@k20human I definately shhould do that

**Comment by shermanwaiwai** [comment]
@udos86  
great work! thanks
