### ISSUE TITLE
A way to pass function to "when" condition instead of scalar

### ISSUE THREAD

**Issue by friendsofdevs** [udos86/ng2-dynamic-forms#274]
At the first let me say thank your for your project, it's really helpful thing.
Also have a question: is there a way to pass function to "when" condition in field configuration?
Now you have `when: [{id: "mySelect", value: "option-3"}]` and value is scalar. It would be nice if 'value' allows to use function in addition to scalar.

**Comment by udos86** [comment]
@friendsofdevs Thanks for your message!

The related form controls feature all in all is pretty limited at the moment. [I'm planning](https://github.com/udos86/ng2-dynamic-forms/issues/253) to do refactoring...
