### ISSUE TITLE
Primeng 'Chips' and 'SelectButton' field types

### ISSUE THREAD

**Issue by friendsofdevs** [udos86/ng2-dynamic-forms#275]
Is there a way to add Primeng Chips and SelectButton support to forms?

**Comment by udos86** [comment]
@friendsofdevs Hi! I'm planning to add support for Prime NG Chips as soon as possible. I'll also check for SelectButton.

**Comment by friendsofdevs** [comment]
Great! SelectButton almost the same as their Dropdown component.

By the way, do you think about something that allows to use custom fields with their own templates? I mean the way that allows an user to extend base class, define templates and code all functionality he needs?

**Comment by udos86** [comment]
@friendsofdevs ng2 Dynamic Forms only abstracts concrete form controls. If you'd like to add some custom component and / or model you're free to adjust the template file of the corresponding UI package for your use case. Remember, that this is not a UI component library.

**Comment by udos86** [comment]
@friendsofdevs Chips will be supported in `1.3.15`. SelectButton support is postponed.
