### ISSUE TITLE
Not able to build with AoT: @ng2-dynamic-forms/ui-bootstrap/src/dynamic-form-bootstrap.component.ts (15,15): Cannot find name 'module'.)

### ISSUE THREAD

**Issue by rahul-winner** [udos86/ng2-dynamic-forms#276]
I'm trying to use "ng2-dynamic-forms" in my project. My project is developed with Angular Cli. 
However, after adding this package to my project, I'm getting following error when building my project: 
`ERROR in [Project Path]/node_modules/@ng2-dynamic-forms/ui-bootstrap/src/dynamic-form-bootstrap.component.ts (15,15): Cannot find name 'module'.)`

The command I am using to build my project : **ng build --aot**
**Note:** It works fine if I don't build with AoT.

Here is the environment details [version of various components]
NodeJS : 6.9.0
Angular 2 : ^2.4.6
@angular/cli : ^1.0.0-beta.30
typescript :   ~2.0.3
ng2-dynamic-forms : 1.3.13

Also, I am able to resolve this issue by making some changes in "ui-bootstrap" module itself, though not sure how correct is that. 
I cloned the 'ng2-dynamic-forms' from GitHub and removed the "moduleId: module.id," from "dynamic-form-bootstrap.component.ts". And then get a local build of this project. This worked for me. 

Please let me know if above is the correct solution. Or if I'm doing anything not right. 
Kindly let me know if you need more information.

Thanks. Rahul

**Comment by udos86** [comment]
@rahul-winner Hi Raul!

In order to evaluate your issue I've created a new sample project via Angular CLI that's using ng2 Dynamic Forms. 

Bundling the app with `ng build --aot` is working flawless for me.

@mak92 also [has confirmed](https://github.com/udos86/ng2-dynamic-forms/issues/257) that the library can be used with AOT.

Did you exactly follow the steps explained in [Basic Usage Guide](https://github.com/udos86/ng2-dynamic-forms#basic-usage)?

**Comment by rahul-winner** [comment]
@udos86 Thanks for your response. 
I am hoping you must have used 'ui-bootstrap' as well.. Did you try with latest version of Angular CLI ?

Please note that when I removed 'moduleId: module.id' from a custom build then I could get AoT build fine.

**Comment by udos86** [comment]
@rahul-winner: Yes, builds without any errors!

`package.json`
```
{
  "name": "aot-demo",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^2.4.0",
    "@angular/compiler": "^2.4.0",
    "@angular/core": "^2.4.0",
    "@angular/forms": "^2.4.0",
    "@angular/http": "^2.4.0",
    "@angular/platform-browser": "^2.4.0",
    "@angular/platform-browser-dynamic": "^2.4.0",
    "@angular/router": "^3.4.0",
    "@ng2-dynamic-forms/core": "^1.3.13",
    "@ng2-dynamic-forms/ui-bootstrap": "^1.3.13",
    "core-js": "^2.4.1",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.7.2"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0-beta.31",
    "@angular/compiler-cli": "^2.4.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "protractor": "~5.1.0",
    "ts-node": "1.2.1",
    "tslint": "^4.3.0",
    "typescript": "~2.0.0"
  }
}
```

`app.module.ts`
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { ReactiveFormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { DynamicFormsCoreModule } from '@ng2-dynamic-forms/core';
import { DynamicFormsBootstrapUIModule } from '@ng2-dynamic-forms/ui-bootstrap';
import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    ReactiveFormsModule,
    DynamicFormsCoreModule.forRoot(),
    DynamicFormsBootstrapUIModule,
    HttpModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

`app.model.ts`
```
import {
    DynamicFormControlModel,
    DynamicCheckboxModel,
    DynamicInputModel,
    DynamicRadioGroupModel
} from "@ng2-dynamic-forms/core";

export const MY_DYNAMIC_FORM_MODEL: DynamicFormControlModel[] = [

    new DynamicInputModel({

        id: "exampleInput",
        label: "Example Input",
        maxLength: 42,
        placeholder: "example input"
    }),

    new DynamicRadioGroupModel<string>({

        id: "exampleRadioGroup",
        label: "Example Radio Group",
        options: [
            {
                label: "Option 1",
                value: "option-1",
            },
            {
                label: "Option 2",
                value: "option-2"
            },
            {
                label: "Option 3",
                value: "option-3"
            }
        ],
        value: "option-3"
    }),

    new DynamicCheckboxModel({

        id: "exampleCheckbox",
        label: "I do agree"
    })
];
```

`app.component.ts`
```
import { Component } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { MY_DYNAMIC_FORM_MODEL } from "./app.model";
import { DynamicFormControlModel, DynamicFormService } from "@ng2-dynamic-forms/core";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
    title = 'app works!';

    formModel: DynamicFormControlModel[] = MY_DYNAMIC_FORM_MODEL;
    formGroup: FormGroup;

    constructor(private formService: DynamicFormService) {}

    ngOnInit() {
        this.formGroup = this.formService.createFormGroup(this.formModel);
    }
}
```


`app.component.html`
```
<h1>
  {{title}}
</h1>

<form [formGroup]="formGroup">

    <dynamic-form-bootstrap-control *ngFor="let controlModel of formModel" 
                                    [controlGroup]="formGroup"
                                    [model]="controlModel"></dynamic-form-bootstrap-control>
</form>
```

**Comment by Fannon** [comment]
What exactly did you change/fix? I'm having the same problem here. Thanks!

**Comment by udos86** [comment]
@Fannon Well, I don't know! I'll regularly create new test projects with CLI but I never experienced this one. 

I'd have a look at the running project to evaluate this.

**Comment by Fannon** [comment]
@udos86: I might have figured it out:

Manually adding the [node type definitions](https://www.npmjs.com/package/@types/node) to my tsconfig fixed the problem for me:
```json
"types" : ["node"]
```

The problem was that the latest angular cli version (1.0.0-rc0) moved the typescript configs from `/` to `/src` which leads to a problem when looking for `/@types/` definitions within the `node_modules` folder (which seem to be only automatically searched/added when it is on the same directory level with the tsconfig file).

Best,
Simon

**Comment by udos86** [comment]
@Fannon Thanks very much for that information! 👍
