### ISSUE TITLE
Unable to set width of the control. Is this an issue?

### ISSUE THREAD

**Issue by mmommo** [udos86/ng2-dynamic-forms#277]
Please see code below.

`<dynamic-form-material-control *ngFor="let cm of controlModel"
                                   [controlGroup]="formGroup"
                                   [model]="cm"
                                    style="width:100%"></dynamic-form-material-control>`

No matter 100% or in px, it's no effect at all.

Is this an issue or is there another way of doing this? If there's another way, isn't inline is the most straight forward way?

Cheers!

**Comment by udos86** [comment]
@mmommo This behavior is not related to the library. Setting the `display` property of the control to `inline-block` will work.

**Comment by mmommo** [comment]
@udos86 thanks for the reply but it doesn't work. Please see code below.

`<form [formGroup]="formGroup">

    <dynamic-form-material-control *ngFor="let cm of controlModel"
                                   [controlGroup]="formGroup"
                                   [model]="cm"
                                    style="width:100%;display:inline-block"></dynamic-form-material-control>
    
    <md-input placeholder="testing" style="width:100%"></md-input>
</form>`

I couldn't find a way to get the input controls fill the container but with the last one, it fits perfectly. 

Thanks.
