### ISSUE TITLE
Add ng-bootstrap

### ISSUE THREAD

**Issue by sadiqhabib** [udos86/ng2-dynamic-forms#278]
Hi I am interested to add [ng-bootstrap](https://ng-bootstrap.github.io/#/home). 
I also tried as well to add it. I am really interested to contribute in this amazing project.

**Comment by udos86** [comment]
@sadiqhabib Thanks for your message!

If you'd like to contribute ng-bootstrap support you generally would have to add `ng-bootstrap` as an optional dependency and implement a new component and a new template to the `DynamicFormsBootstrapUIModule`. Please also see [CONTRIBUTION](https://github.com/udos86/ng2-dynamic-forms/blob/master/CONTRIBUTE.md) GUIDE.

**Comment by sadiqhabib** [comment]
I Created new branch according to  [CONTRIBUTION GUIDE](https://github.com/udos86/ng2-dynamic-forms/blob/master/CONTRIBUTE.md) now I am trying to import `ng-bootstrap` inside `ui-ngbootstrap` module. But now I am getting problem to lint this module.

```
ui-ngbootstrap/src/ui-ngbootstrap.module.ts[4, 27]: ' should be "
'lint:modules' errored after 2.07 s
Error in plugin 'gulp-tslint'
Message:
    Failed to lint: ui-ngbootstrap/src/ui-ngbootstrap.module.ts [4, 27]: ' should be ".
```
Can you please tell me where is the problem.
Thank you

**Comment by udos86** [comment]
@sadiqhabib Please don't add a new module. You better extend the current `ui-bootstrap` package by adding
* `DynamicFormNGBootstrapComponent`
* `DynamicFormsNGBootstrapUIModule`
* `ng-bootstrap` as optional dependency to `package.json`

Your lint error is self-explaining: you're using single quotes instead of double quotes.

**Comment by sadiqhabib** [comment]
@udos86 Thank you for guiding me. Now I added files as you defined above. But now I an getting problem to start example. it is related to template parsing but until now i did not edit any template. Can you please tell me what I am doing wrong. 
Thank you

**Comment by udos86** [comment]
@sadiqhabib Sorry, from afar it's impossible to tell what's wrong. Remember that after building the modules via `npm run build:modules` you also need to import your new NgModule into the `AppModule` in order to run it in the example.
