### ISSUE TITLE
Feature request: other types of input in DynamicFormArrayModel

### ISSUE THREAD

**Issue by bobby77** [udos86/ng2-dynamic-forms#279]
Dear all,
Thanks for this library, it's very useful and it's worth to be extended!

I would like to be able to use other types of fields than DynamicInputModel within a DynamicFormArrayModel.

Currently, the "createGroup" property within DynamicFormArrayModel({createGroup: ...}) needs to return an array of DynamicInputModel[].
Would it be difficult to change it to an array of DynamicFormValueControlModel[] ?

I would like to be able to use a select field within a form array.
Thanks a lot.

**Comment by bobby77** [comment]
I looked at the source code, and it is already possible !
Here is how to do it if someone has the same request: 

It is necessary to specify the type of value like this : DynamicSelectModel<number>
(It is actually not necessary when a select field is outside an array, so when I did a copy and paste I got an error)

Best regards.

```
new DynamicFormArrayModel({
        id: "array",
        label: 'my array',
        initialCount: 2,
        createGroup: () => {
                return [
                    new DynamicSelectModel<number>({
                        id: "select_field", label: "select", options : { ... }
                    }),
                    new DynamicInputModel({
                        id: "input_field",
                        label: "input"
                    }) 
                ]
})
```

**Comment by bobby77** [comment]
One last comment to complete this topic.
When the select field is nested inside a form array, I do not find a way to modify the options dynamically (the values within the select field are coming from a service).

When it is a simple field, it is possible to do this :+1: 
`
        this.selectModel = <DynamicSelectModel<number>> this.formService.findById("testSelect", this.formModel);
        this.selectModel.options = [{
                label: "Option A",
                value: "10",
            },{
                label: "Option B",
                value: "11",
            }
            ];
`

But when it is in a DynamicFormArrayModel, it is not possible to get access to the selectModel options, as all properties seem private.

Thanks if someone can help. 
Best regards

**Comment by udos86** [comment]
@bobby77 You can retrieve your `selectModel` pretty by using the `get` functions of `DynamicFormArrayModel` and `DynamicFormArrayGroupModel`:

`this.selectModel = this.formArrayModel.get(<index of group>).get(<index of selectModel) as DynamicSelectModel`
