### ISSUE TITLE
[Question] Custom template

### ISSUE THREAD

**Issue by minuz** [udos86/ng2-dynamic-forms#280]
Hi @udos86,

I've been trying to implement a custom template for Checkboxes as our theme requires a certain HTML semantic to work properly.
I tried to follow the examples from the guide but none of them seems to have had any effect when rendering the checkboxes. Is this feature implemented for ui-bootstrap?

In addition, I've noticed an extra div in all components. Is there a reason for this extra div?

**Comment by udos86** [comment]
@minuz custom templates are for adding custom content **before** or **after** a certain form control. Not for transforming the markup of the actual form control.

What do you exactly mean by? 

> I've noticed an extra div in all components

**Comment by minuz** [comment]
![2017-02-20_1652](https://cloud.githubusercontent.com/assets/818024/23188024/31f87070-f8e1-11e6-8eb1-50a85bb7f805.png)

**Comment by udos86** [comment]
@minuz The `div` container is essentially needed when you'd like to use Bootstrap's grid system. Just have a look at the [Bootstrap example](http://ng2-dynamic-forms.udos86.de/example/index.aot.html#/example-bootstrap) and you'll see what I mean. 

The template actually should work when you're using as described in the README guide. However there seems to be an issue when using `DynamicCheckboxGroupModel`. I'll verify it.

**Comment by udos86** [comment]
@minuz I can confirm that your issue has in deed uncovered a bug in how templates are set for nested components. This will arrive in `1.3.15` and make templates work for multi-nested form / checkbox groups. 

Thanks!

**Comment by minuz** [comment]
> @minuz The div container is essentially needed when you'd like to use Bootstrap's grid system. Just have a look at the Bootstrap example and you'll see what I mean.

I see! However, isn't the semantic inverted? 
Usually you have the column definition as:

``` HTML
<div class="col-sm-10">
     <div class="form-group">
           <label></label>
           <input />
     </div>
</div>
<div class="col-sm-2">
      // Some other code....
</div>
```
Atm, the output is:

``` HTML
<dynamic-form-bootstrap-control>
    <div class="form-group">
        <label class="control-label col-sm-3" for="bootstrapInput">Example Input</label>
        <div class="col-sm-9">
            <div class="input-group">
                <div class="input-group-addon">Prefix</div>
                <input class="form-control" id="bootstrapInput">
                <div class="input-group-addon">Suffix</div>
            </div>
            <span class="help-block">Just a sample help text</span>
        </div>
        <ul class="has-error col-sm-offset-3 col-sm-9 hidden">
            <li class="help-block">Example Input is required</li>
        </ul>
    </div>
</dynamic-form-bootstrap-control>
```

I guess that would allow an easier styling as within the grid layout, you still could split the label and the control into different column arrangements but relative to the main column setup.

Anyway...just a thought  ;)

**Comment by udos86** [comment]
@minuz 

In my opinion the current markup is fine 'cause it allows [horizontal forms ](http://getbootstrap.com/css/#forms-horizontal)while your solution does not. 

Furthermore you can still add grid styling to container by using it's corresponding property:
```
{
    grid: {
        container: "col-sm-3"
    }
}
```
