### ISSUE TITLE
DynamicSelectModule problem display when multiple is at false

### ISSUE THREAD

**Issue by dimq** [udos86/ng2-dynamic-forms#284]
Hi i've got a problem with primeng ui and the dropdown. 
When i remove the multiple option or i put it to false : 
```javascript
new DynamicSelectModel<string>(
        {
            id: "primeSelect",
            label: "Example Select",
            options: [
                {
                    label: "Option 1",
                    value: "option-1",
                },
                {
                    label: "Option 2",
                    value: "option-2"
                },
                {
                    label: "Option 3",
                    value: "option-3"
                }
            ]
        }
    )
```
 the dropdown style width is fixed to 30px : 
![dropdown-ui-problem-debug-console](https://cloud.githubusercontent.com/assets/5257119/23220682/0d0221fc-f923-11e6-8aeb-6df9bc32ecd3.jpg)

Which give me this example : 
![dropdown-ui-problem](https://cloud.githubusercontent.com/assets/5257119/23220565/b117a45c-f922-11e6-884a-e4330441e70b.jpg)
Is anyone have already had this problem because i don't seem to find it in the existing issues. Thanks !

**Comment by udos86** [comment]
@dimq Hi! I'm sorry, but I cannot verify this behavior in the [Prime NG example](https://github.com/udos86/ng2-dynamic-forms/tree/master/example/app/primeng).  Everything seems to be working fine there. 

Anyone else experiencing this problem?
