### ISSUE TITLE
DynamicCheckboxModel  relation bug

### ISSUE THREAD

**Issue by liorFaigenzon** [udos86/ng2-dynamic-forms#285]
relation make the disabled  not working.
`new DynamicCheckboxModel(
                            {
                                id: "checkboxGroup2",
                                label: "Checkbox 2",
                                value: false,
                                disabled:true,
                                relation: [
                                    {
                                        action: "DISABLE",
                                        connective: "OR",
                                        when: [
                                            {
                                                id: "bootstrapSelect",
                                                value: "option-1"
                                            },
                                            {
                                                id: "bootstrapSelect",
                                                value: "option-4",
                                            }
                                        ]
                                    }
                                ],
                               
                            },
                            {
                                grid: {
                                    control: "col-sm-12"
                                }
                            }
                        )
                    ]
                }`

**Comment by udos86** [comment]
@liorFaigenzon Ok, I'll check it!
