### ISSUE TITLE
Validation Messages in PrimeNG Form Groups

### ISSUE THREAD

**Issue by SGRob** [udos86/ng2-dynamic-forms#294]
Following the documentation it appears as though validation messages aren't working with PrimeNG form groups.

Switching to Bootstrap works as expected which makes me believe this is an issue with the PrimeNG implementation.

**Comment by udos86** [comment]
@SGRob Please have a look at the input control in [Prime NG sample](http://ng2-dynamic-forms.udos86.de/example/index.aot.html#/example-primeng). It's working fine there.

**Comment by SGRob** [comment]
@udos86 Thanks for the reply!

It looks like the controls in the [Prime NG sample](http://ng2-dynamic-forms.udos86.de/example/index.aot.html#/example-primeng) aren't contained within a DynamicFormGroupModel.

When using a DynamicFormGroupModel to group controls the validation messages work as expected with Bootstrap UI but not PrimeNG

**Comment by CBoroshok** [comment]
Having same issue.  This is critical.  Any chance of a fix?

**Comment by udos86** [comment]
@SGRob @CBoroshok Alright, I'll check it asap!

**Comment by udos86** [comment]
@SGRob @CBoroshok I can confirm, this is a bug! I will deliver a patch right away!
