### ISSUE TITLE
Issues on compilation (Webpack2) #bug

### ISSUE THREAD

**Issue by renatoaraujoc** [udos86/ng2-dynamic-forms#295]
Hello,

As soon as I compile my project, I recieve the following error:

> ERROR in xxx/project/node_modules/@ng2-dynamic-forms/core/src/service/dynamic-form.service.ts
> (66,54): error TS2339: Property 'name' does not exist on type 'ValidatorFn'.
> 
> ERROR in xxx/project/node_modules/@ng2-dynamic-forms/core/src/service/dynamic-form.service.ts
> (71,112): error TS2339: Property 'name' does not exist on type 'AsyncValidatorFn'.

I am using the following versions:
"@ng2-dynamic-forms/core": "1.3.16"
"@ng2-dynamic-forms/ui-bootstrap": "1.3.16"

Any ideas? Thank you!

**EDIT:** Falling back to version 1.3.0 fixes the issue. The issue starts happening on version 1.3.1+.

**Comment by udos86** [comment]
@renatoaraujoc Hi! I'm pretty sure this is not a library bug.

`Function.name` is a property that was added in ES2015. So you should provide typings for that in your `tsconfig.json` like so, for example:
```
    "lib": [
      "es2015",
      "dom"
    ],
```

**Comment by renatoaraujoc** [comment]
Hello @udos86!

Thank you very much for your response, adding the following lines in my tsconfig.json fixes my issue.

```
"lib": [
    "dom",
    "es6",
    "scripthost"
]
```

Thank you very much, no I'm running you latest version without a problem.
