### ISSUE TITLE
dropdown/select with "multiple:true" is not working

### ISSUE THREAD

**Issue by tariq-mahmood-nxb** [udos86/ng2-dynamic-forms#303]
I am trying to create a multiselect dropdown as following
let control = new DynamicSelectModel({
            multiple: true,
            id: "select-multiple",
            label: "Select Multiple"
        });

        let options = [];
        for (let choice of field.choices) {
            options.push(new DynamicFormOption({
                value: choice.value,
                label: choice.title
            }));
        }
        control.options = options;
But it doesn't change select box to multiselect, is that not supported?
I am using bootstrap ui

**Comment by udos86** [comment]
@tariq-mahmood-nxb That's intentional (see #187).

From a usability point of view it is recommended anyway to use checkbox groups instead of native multiple select (no one knows about holding down ctrl key)

**Comment by drkhannah** [comment]
is there multi select support for bootstrap in this lib yet? adding multiple: true to a select still doesn't seem to work in bootstrap
