### ISSUE TITLE
input type file giving error in firefox, after selecting file

### ISSUE THREAD

**Issue by tariq-mahmood-nxb** [udos86/ng2-dynamic-forms#304]
EXCEPTION: Error in ./DynamicFormBootstrapComponent class DynamicFormBootstrapComponent - inline template:91:16 caused by: $event.srcElement is undefined
vendor.bundle.js (line 59916)
ORIGINAL EXCEPTION: $event.srcElement is undefined
vendor.bundle.js (line 59918)
ORIGINAL STACKTRACE:
vendor.bundle.js (line 59921)
DynamicFormControlComponent.prototype.onValueChange@http://localhost:4200/vendor.bundle.js:98436:21
anonymous/View_DynamicFormBootstrapComponent13.prototype.handleEvent_4@/DynamicFormsBootstrapUIModule/DynamicFormBootstrapComponent/component.ngfactory.js:1367:21
DebugAppView.prototype.eventHandler/<@http://localhost:4200/vendor.bundle.js:93247:24
decoratePreventDefault/<@http://localhost:4200/vendor.bundle.js:46582:53
ZoneDelegate.prototype.invokeTask@http://localhost:4200/polyfills.bundle.js:6440:17
NgZone.prototype.forkInnerZoneWithAngularBehavior/this.inner<.onInvokeTask@http://localhost:4200/vendor.bundle.js:31103:28
ZoneDelegate.prototype.invokeTask@http://localhost:4200/polyfills.bundle.js:6439:17
Zone.prototype.runTask@http://localhost:4200/polyfills.bundle.js:6239:28
ZoneTask/this.invoke@http://localhost:4200/polyfills.bundle.js:6493:28
vendor.bundle.js (line 59922)
ERROR CONTEXT:
vendor.bundle.js (line 59925)
[object Object]
vendor.bundle.js (line 59926)
Error: Error in ./DynamicFormBootstrapComponent class DynamicFormBootstrapComponent - inline template:91:16 caused by: $event.srcElement is undefined

**Comment by udos86** [comment]
@tariq-mahmood-nxb 

Thanks for reporting this. Could likely be a bug. I'll examine this.

**Comment by udos86** [comment]
@tariq-mahmood-nxb  There'll be a bugfix for this in `1.4.7`
