### ISSUE TITLE
Edit control issue?

### ISSUE THREAD

**Issue by stevehoper** [udos86/ng2-dynamic-forms#306]
Hi, I was trying to add/edit new dynamic control model into formGroup not previously defined with in the formModel. I manage to add controls with addFormGroupControl service, but how to add new DynamicFormGroupModel to formModel and edit a specific control's properties and options within group array, is there a service function to do that?
Thanks much.

**Comment by udos86** [comment]
@stevehoper Hi! 

So you're trying to add a `DynamicFormGroupModel` via `addFormGroupControl` and it does not work as expected, right?

I'll have to examine this. Could be a bug.

**Comment by stevehoper** [comment]
Thanks for the reply.
I am trying to have formGroups (type: DynamicFormGroupModel) within formModel array, and formControls within formGroup structure. It seems to be OK for me to push group into formModel and add controls into group[], but after new formGroup created, it's giving error when adding new controls
(Cannot read property 'valueChanges' of null).

I am not sure this is the correct way for me to add **formGroup**/formControl into the formModel like this or is there other service I should use when there is a change happen to formModel?

//add control into group[]
let exampleControl = this.formService.findById(selectedControlId, this.customFormModels) as DynamicFormGroupModel;
let groupIndex=this.formModel.findIndex(formGroup=>formGroup.id===this.selectedGroupId);
this.formService.addFormGroupControl(this.formGroup.get(this.selectedGroupId) as FormGroup,this.formModel[groupIndex],exampleControl);
//add control end

//add formGroup into formModel
      let formGroup=new DynamicFormGroupModel({
        id: "bootstrapFormGroup2",
        legend: `${newGroupName}`,
        group: []
    });
    this.formModel.push(formGroup);
    // or new array
    // let newGroupArray=this.formModel.concat(formGroup);
    // this.formModel=newGroupArray;
    this.formGroup = this.formService.createFormGroup(this.formModel);

![image](https://cloud.githubusercontent.com/assets/26602696/24328557/74c6fc54-11ba-11e7-9352-bf4e42646ef4.png)

**Comment by udos86** [comment]
@stevehoper Ok, I think you're almost on the right track...

Let's say this is our form model:
```
formModel: DynamicFormControlModel[] = [

    new DynamicFormGroupModel({

        id: "nestedFormGroup",
        legend: "Nested Form Group 1",
        group: []
];

// ...

this.formGroup = this.formService.createFormGroup(this.formModel);
```

Now how to add some new form item to the nested `DynamicFormGroupModel` on the fly?
```
let nestedFormGroup = this.formGroup.controls["nestedFormGroup"] as FormGroup;
let nestedFormGroupModel = formModel[0] as DynamicFormGroupModel;
let newModel = new DynamicInputModel({id: "newInput"});

this.formService.addFormGroupControl(nestedFormGroup, nestedFormGroupModel, newModel);
```

`DynamicFormService` takes care of adding the `DynamicFormControlModel` as well as the `FormControl`.

**Comment by stevehoper** [comment]
Thanks, it makes sense.
After testing for a while, I think I can narrow down the issue.
It works OK with single DynamicFormGroupModel (let's say group1) in formModel.
If I continue to add new group (group2) to the formModel, adding new controls to new group is fine but, switch back to group1, adding controls ( types previously **_not_** exist in group1) to group1 raises up the Cannot read property 'valueChanges' of null problem. It may have something to do with the newInstance related actions when adding controls to existing group.

**Comment by udos86** [comment]
@stevehoper Ok, thanks. I'll check it within the next days...

**Comment by stevehoper** [comment]
Same ''valueChanges' of nulI error if try to set a different id to each new DynamicControl to be added to group, when two or more groups are in formModel.

let newControlModel = new DynamicInputModel({id: this.newGuid()});
this.formService.addFormGroupControl(nestedFormGroup, nestedFormGroupModel, newControlModel);//<--error

**Comment by stevehoper** [comment]
Hi, 
In DynamicFormControlComponent, it's looking for existing controls in the group based on model.id which is null if new id or control is added. Can we update the line to get but if null create new FormControl based on model passed in? 
Thanks

this.control = this.group.get(this.model.id) as FormControl;

model: DynamicFormControlModel;
ngOnInit(): void {
     ...
        # this.control = this.group.get(this.model.id) as FormControl;
        this.type = this.getFormControlType();

        this.subscriptions.push(this.control.valueChanges.subscribe(this.onControlValueChanges.bind(this)));//null
this.subscriptions.push(this.model.disabledUpdates.subscribe(this.onModelDisabledUpdates.bind(this)));

**Comment by udos86** [comment]
@stevehoper Sorry for the delay but I've been sick and busy during the last two weeks. 

I now can verify this as a highly probable bug and try to deliver a fix.

**Comment by udos86** [comment]
@stevehoper After checking it again, I'm not sure anymore that is a bug.

According to your message the following code snippet should throw an exception but it's actually working perfectly fine in my sample application:

```
export const FORM_MODEL = [

    new DynamicFormGroupModel({

        id: "bootstrapFormGroup1",
        group: [/*...*/]
    }),

    new DynamicFormGroupModel({

        id: "bootstrapFormGroup2",
        group: [/*...*/]
    })
];


// ...

this.formService.addFormGroupControl(
    this.formGroup,
    this.formModel,
    new DynamicFormGroupModel({
        id: "bootstrapFormGroup3",
        group: []
    })
);

this.formService.addFormGroupControl(
    this.formGroup.get("bootstrapFormGroup3") as FormGroup,
    this.formModel[2] as DynamicFormGroupModel,
    new DynamicInputModel({id: "newInput"})
);
```

Please make sure that your are calling `addFormGroupControl` with correct references.

**Comment by stevehoper** [comment]
I think you are right. The issue was caused by wrong reference of formGroup.
After I updated all adding actions with addFromGroupControl, it works fine.
I am using it together with Redux, may have more feedback later.
Thanks much.

**Comment by stevehoper** [comment]
By the way, is there a way to change order of controls within a group since it is not used along with ng-template, so I believe no context is available.

**Comment by udos86** [comment]
@stevehoper 

At the moment there's a `move` function only for form arrays. I'll try to add a corresponding method for form groups as well.

Besides I'd really appreciate your Redux expertise! Could you maybe show a little sample on how to implement Redux with ng2 Dynamic Forms correctly? That'd be great!

**Comment by stevehoper** [comment]
Sure, right now it's under development.
Once it's functional, I will create a sample project for it.
