### ISSUE TITLE
Custom Validator

### ISSUE THREAD

**Issue by fhammami** [udos86/ng2-dynamic-forms#307]
Hello,
A great work !
just a question please : Is there a way to send parameters with custom validator when creating dynamic control ?
I am using material.

Also in a form array which is in form group validation does not work for me.
Also minLength & maxLength even for control in just form group.
REGARDS.

**Comment by udos86** [comment]
@fhammami Hi! Thanks for your issue!

> Is there a way to send parameters with custom validator when creating dynamic control ?

Yes, there should be:

```
new DynamicInputModel({

    id: "myInput",
    label: "My Input",
    validators: {
        myCustomValidator: 5
    }
})
```

> Also in a form array which is in form group validation does not work for me.
> Also minLength & maxLength even for control in just form group.

Could you provide a code sample, please?

**Comment by fhammami** [comment]
Thanks a lot for your response.
Indeed I try this but it does not work for me : I explain the case : I have a model that I want to pass it as parameter and it's ok; **the problem that if i change the value of the  dynamic input the method does not fire anymore :( My example** : 
var model = new DynamicInputModel({
                              id: 123,
                              placeholder: name,
                              value: 5
                            });
model.validators= {
                                checkValue: model
                              }
the provider in appmodule : 
 { provide: NG_VALIDATORS, useValue: checkValue, multi: true }
the method : 
function checkValue(c: any) {
  return !isNullOrUndefined(c.value) && c.value.length < c.value ? null :{
      checkLength: {
        valid: false
      }
    };
}

**Comment by udos86** [comment]
@fhammami Ok, there's some major misconception here...

There's no connection between a model and validator whatsoever. A validator function always validates values based on a `FormControl`. 

You only need to pass a parameter to a validator wrapper function when a validator needs to be made more concrete, i.e. `minLength` or `maxLength`.

In your case should refactor your function and apply without a parameter:

```
function checkValue(c: FormControl) {
    return !isNullOrUndefined(c.value) && c.value.length < c.value ? null :{
        checkValue: {
            valid: false
        }
};
```

```
var model = new DynamicInputModel({
    id: 123,
    placeholder: "name",
    value: 5,
    validators: {
        checkValue: null
    }
});
```

**Comment by fhammami** [comment]
for the maxlength and minlength : 
I can't personnalise my error message :control.hasError('maxLength') does not work for me.

THANKS A LOT.

**Comment by fhammami** [comment]
Sorry I didn't get your last answer :( i am new in angular.
Pleeeeeeeease can you explain more (for example i have an upload file and i want to check the size) how can i deal with that.

REGARDS.

**Comment by udos86** [comment]
@fhammami 

Sorry, if you're new to Angular then start at [angular.io](https://angular.io/docs/ts/latest/) and read all it's docs first. 

I can't provide free support for basic Angular issues.

**Comment by fhammami** [comment]
OK.Thanks.
