### ISSUE TITLE
Getting issue after upgrade to angular4 !

### ISSUE THREAD

**Issue by aurimukas** [udos86/ng2-dynamic-forms#310]
Hey,

After ng-cli and angular upgrade started to get an error:

`ERROR in node_modules/@ng2-dynamic-forms/core/src/service/dynamic-form.service.ts (108,13): Argument of type 'ValidatorFn' is not assignable to parameter of type 'AsyncValidatorFn'.
  Type 'ValidationErrors' is not assignable to type 'Promise<ValidationErrors> | Observable<ValidationErrors>'.
    Type 'ValidationErrors' is not assignable to type 'Observable<ValidationErrors>'.
      Property '_isScalar' is missing in type 'ValidationErrors'.
node_modules/@ng2-dynamic-forms/core/src/service/dynamic-form.service.ts (145,45): Argument of type 'ValidatorFn[] | AsyncValidatorFn[]' is not assignable to parameter of type 'AsyncValidatorFn[]'.
  Type 'ValidatorFn[]' is not assignable to type 'AsyncValidatorFn[]'.
    Type 'ValidatorFn' is not assignable to type 'AsyncValidatorFn'.`

anyone got the same problem?

**Comment by udos86** [comment]
@aurimukas Hi! Did you also update to the newest lib version `1.4.0`?

**Comment by aurimukas** [comment]
Yes I did!

**Comment by udos86** [comment]
@aurimukas 

Ok, I cannot verify this as a bug cause I definitely fixed those typing complaints for `1.4.0`. 

I also just checked again with latest `@angular/cli 1.0.0` and it builds without errors.

Did you also update your TypeScript?

**Comment by aurimukas** [comment]
@udos86 
See my package file:
{
  "angular-cli": {},
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.0.0",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/platform-server": "^4.0.0",
    "@angular/router": "^4.0.0",
    "@ng2-dynamic-forms/core": "1.4.0",
    "@ng2-dynamic-forms/ui-bootstrap": "1.4.0",
    "bootstrap": "4.0.0-alpha.6",
    "core-js": "2.4.1",
    "ng2-bootstrap": "1.4.2",
    "ng2-webstorage": "1.5.1",
    "ngx-toastr": "5.0.5",
    "rxjs": "5.2.0",
    "typescript": "2.2.1",
    "zone.js": "^0.8.5"
  },
  "devDependencies": {
    "@angular/cli": "^1.0.0",
    "@angular/compiler-cli": "4.0.0",
    "@types/jasmine": "2.5.46",
    "@types/node": "~7.0.11",
    "@types/socket.io-client": "^1.4.29",
    "codelyzer": "~3.0.0-beta.4",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.5.0",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.0.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.1",
    "ts-node": "~3.0.2",
    "tslint": "~4.5.1",
    "typescript": "~2.2.1"
  }
}

**Comment by udos86** [comment]
@aurimukas Ok, I'd propose a clean reinstall of your node modules:

1. Manually delete your node_modules folder
2. Clean your npm cache: `npm cache clean`
3. Reinstall all npm dependencies: `npm install`

When working with the latests version this typings error should definitely disappear.

**Comment by aurimukas** [comment]
@udos86 THANK YOU!!
You were right! I'm a bit surprised because I've done this step already before..

Anyway.. thank you for your reactivity!!
