### ISSUE TITLE
Can't bind to 'ngTemplateOutletContext'

### ISSUE THREAD

**Issue by nunogrocha** [udos86/ng2-dynamic-forms#312]
Hi, I imported the modules to my main app.module and straight away, I got the following error:

```
Unhandled Promise rejection: Template parse errors:
Can't bind to 'ngTemplateOutletContext' since it isn't a known property of 'ng-template'.
1. If 'ng-template' is an Angular component and it has 'ngTemplateOutletContext' input, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("te *ngIf="hasStartTemplate && type !== 1"
              [ngTemplateOutlet]="template"
              [ERROR ->][ngTemplateOutletContext]="model"></ng-template>
```

I tried to use the code from the readme examples without being able to solve the error.

I'm running angular-cli 1.0.0-rc.2, @angular 2.4.0, and tried it with @ng-bootstrap/ng-bootstrap 1.0.0-alpha.22 and primeng 2.0.4.

How can I fix this?

Thank you!

**Comment by udos86** [comment]
@nunogrocha Please update to Angular 4!

**Comment by nunogrocha** [comment]
Thanks! Missed that unmet dependency
