### ISSUE TITLE
Uncaught TypeError: Cannot read property 'core' of undefined

### ISSUE THREAD

**Issue by pirauvladislav** [udos86/ng2-dynamic-forms#313]
Hi, I am new in angular and I try to use your control but after I added  scripts
 `      "scripts": [
          ...
          "../node_modules/@ng2-dynamic-forms/core/bundles/core.umd.js",
          "../node_modules/@ng2-dynamic-forms/ui-bootstrap/bundles/ui-bootstrap.umd.js"
      ],`

in `.angular-cli.json` I am getting an error  `Uncaught TypeError: Cannot read property 'core' of undefined`

![capture](https://cloud.githubusercontent.com/assets/26765940/24452635/d198cd66-148c-11e7-8ed4-adbf78cffc0d.PNG)

It seems the problem is here 

![capture1](https://cloud.githubusercontent.com/assets/26765940/24452723/3ee1dc14-148d-11e7-929c-02850505d2d6.PNG)

This error does not crash the application. 
Can you help me with this error?   
Thanks much.

PS : I am using Angular 4 and ng2-dynamic-forms v1.4.0.0

**Comment by udos86** [comment]
@pirauvladislav 

You don't need to add anything to `angular-cli.json` when using CLI. 

Just import the library as described by [README.md ](https://github.com/udos86/ng2-dynamic-forms/blob/master/README.md).
