### ISSUE TITLE
Any possibility of using two ui frameworks together

### ISSUE THREAD

**Issue by naveedahmed1** [udos86/ng2-dynamic-forms#317]
What if we need a form with bootstrap ui and some control e.g. for example checkbox, radio, slide toggle from Material? Currently it doesn't seem to be an option. 

I also am not sure if such feature is added what impact it would have on the final bundle size and performance?

Another thing, currently rich text area isn't supported, what about adding its support through libraries like ng2-ckeditor?

**Comment by udos86** [comment]
@naveedahmed1 

> Currently it doesn't seem to be an option
Why not? I cannot see any limitation here...

**Comment by kwoxford** [comment]
What about rich text for Material? CKEditor already has an Angular component.
