### ISSUE TITLE
Datepicker Date Format

### ISSUE THREAD

**Issue by SGRob** [udos86/ng2-dynamic-forms#318]
Hi,

It would be great if we could specify our own date format for the date picker component. Are there any plans to implement such a feature?

I'm using PrimeNG which has a dateFormat attribute which isn't currently exposed by ng2 dynamic forms

Thanks!

**Comment by udos86** [comment]
@SGRob Hi! Thanks for your message!

Indeed, there are plans to include this in the next patch version.

**Comment by phgachoud** [comment]
I'm actually encounter difficulties to implement the date inputType with formats on creation and update, is there any documentation/examples about that?
