### ISSUE TITLE
Custom Validator Parameters

### ISSUE THREAD

**Issue by PaulH1** [udos86/ng2-dynamic-forms#321]
Thank you for a great project.   Please could you let me know if it is possible to pass a parameter into a Custom Validator?  The example shown for the testValidator function is set to null as per the built-in required validator.  Is it possible to pass a value to the testValidator function as per the built-in minLength validator e.g. testValidator: 3.  How could the testValidator function be modified to accept a param?

**Comment by udos86** [comment]
@PaulH1 Hi! Thanks for your message!

This should be absolutely possible:
```
validators: {
    required: null,
    minLength: 3,
    myCustomValidator: 42
}
```

**Comment by PaulH1** [comment]
Thank you @udos86 for pointing me in the right direction.  I've implemented a custom validator by following the Angular pattern.  The function below can now accept the parameter defined in the model e.g.:
`validators: {
     required: null,
     minNumber: 1
}`

`export function minNumber(minNumber: number): ValidatorFn {
    return (control: AbstractControl): ValidationErrors | null => {

        console.log("minNumber: control.value = " + control.value + ", minNumber = " + minNumber.toString());

        if (isEmptyInputValue(control.value)) {
            return null;  // don't validate empty values to allow optional controls            
        }

        var num = +control.value;
        if (isNaN(num)) {
            return { 'minNumber': { 'requiredMinNumber': minNumber, 'actualMinNumber': num } };
        }  

        const length: number = control.value ? control.value.length : 0;
        return num < minNumber ?
            { 'minNumber': { 'requiredMinNumber': minNumber, 'actualMinNumber': num } } :
            null;
    };
}`

**Comment by udos86** [comment]
@PaulH1 Great work! Congrats!
