### ISSUE TITLE
dynamically adding ng-template

### ISSUE THREAD

**Issue by hpn1975** [udos86/ng2-dynamic-forms#323]
First of all I want to congratulate you on building this awesome timesaver module... Thank you.
This is not an issue but a request to see if you can allow for adding ng-template dynamically.  I can easily add an element after dynamic-form-bootstrap-control but I think it will be great if we can have ng-template defined as dynamic component to be inserted as part of the dynamicformcontrolmodel.
Or may be you can help me with your suggestion as to how I can implement it as I am quite new to this.

**Comment by udos86** [comment]
@hpn1975 Hi! Thanks for your kind words!

There have been a couple discussions on this. In my opinion the current solution already pushes the envelope. Besides I would not like to mix up pure model and additional UI information.

What exactly would you like to achieve with such a dynamic component template?

**Comment by hpn1975** [comment]
The use case is simple:
Based on the user inputs on the form (for example: user selecting multiple checkboxes in questionnaire), I want to present them with different action buttons to perform different functions.  I understand that I can do this by just coding in all buttons and using the userselections to show and hide the buttons.  

To your point, it does pushes it a bit but it will also allow me to put custom templating in an array and genereate formgroups on the fly.
It is already a great module... and works great.  I just thought my request to be a next logical extension.... however, if you have already discussed it then please feel free to close this.

**Comment by udos86** [comment]
@hpn1975 Alright, could you please give me an idea of how you'd like to declare such a use case directly on a `DynamicFormControlModel`?

**Comment by hpn1975** [comment]
Based on documentation, the idea of a custom template is providing additional mark up to the form control.  However, in Angular, it can be just another component.  So, for me it will be an Optional Array of Components.
Now, it will be developers responsibility to ensure he is importing/registering these components as part of the App Module.
This will open up a world of possibility in terms of adding interesting components to a form (like an stop clock timing your delay in entering data etc).
I have not studied your module in detail so I am not sure how the events will be emitted and control in such scenario.

As I said, I am new to Angular so pardon my newbie enthusiasm and mistakes.

**Comment by udos86** [comment]
@hpn1975 

There are some interest thoughts in your message. But can't you already achieve this with current state of impementation?

```
<ng-template modelId="myInputModel">
    <my-stop-clock></my-stop-clock>
</ng-template> 
```

I assume you're looking for a way to define that on the model itself, right?

**Comment by hpn1975** [comment]
You are right... Looking to drive it via Model.  Like putting in  some custom highlight... timers etc.

**Comment by udos86** [comment]
@hpn1975 Thank you for being creative and contributing your idea!

I think such a feature could be implemented by using a [dynamic component loader](https://angular.io/docs/ts/latest/cookbook/dynamic-component-loader.html).

For the moment I'd like to close that issue as this is a very advanced feature. 

At first I'd like to deliver full and stable support for all UI libraries, especially Kendo and Material.
