### ISSUE TITLE
Disabled models cause problem

### ISSUE THREAD

**Issue by ferdaousharmel** [udos86/ng2-dynamic-forms#330]
Hello udos86,

Please I have two questions regarding disabling models :
1- If i have for example disabled and required DynamicInputModel, the control.hasError('required') does not work.
2- If i have for example disabled DynamicInputModel,the form is always invalid (a way to solve this problem please ?)

REGARDS.

**Comment by udos86** [comment]
@ferdaousharmel 

1) When a form control is disabled it is not part of the form anymore
2) I cannot verify this! I'd need a sample code for this!

Please have a look at [README.md](https://github.com/udos86/ng2-dynamic-forms/blob/master/README.md#disabling-and-enabling-form-controls), too.

**Comment by arjunshankar** [comment]
I have run into a similar scenario. I have a field which is conditionally required.
Scenario 1: I show the field. User inputs the value. I submit the form.
Scenario 2: The field is not required. I disable the field using _this.inputModel.disabledUpdates.next(true);"_

In scenario 2, the form field is hidden. But on submitting the form, this particular form field shows up as invalid.
