### ISSUE TITLE
Add Css class to dynamic model

### ISSUE THREAD

**Issue by ferdaousharmel** [udos86/ng2-dynamic-forms#331]
Hello udos86,

Please Can I add a CssClass to a dynamic model ?

REGARDS.

**Comment by udos86** [comment]
@ferdaousharmel This is documented in detail in [`README.md`](https://github.com/udos86/ng2-dynamic-forms#form-layouts)

**Comment by mgelain** [comment]
I have the same problem but I cannot understand the documentation. What are element and grid contexts? 
element: {
            label: "control-label"
        },
        grid: {
            control: "col-sm-9",
            label: "col-sm-3"
        }
I don't use bootstrap, I'm on material design and I need to change the width of the DynamicInputModel control. Any help is really appreciated!
