### ISSUE TITLE
Seemly, width of control was fixed in materialize

### ISSUE THREAD

**Issue by huynv86** [udos86/ng2-dynamic-forms#332]
I searched solution for this issue but I cannot expand control width to 100% of row. I attached codes and screenshot: 
`<dynamic-form-material-control *ngFor="let controlModel of formModel" 
				                                    [group]="formGroup"
				                                    [model]="controlModel"></dynamic-form-material-control>`
And controls
`export const MY_DYNAMIC_FORM_MODEL: DynamicFormControlModel[] = [
    new DynamicInputModel({
        id: "nameInput",
        placeholder: "Tên Sản Phẩm (là tên đầy đủ của sản phẩm, dài tối đa 200 ký tự)",
        maxLength: 200,
        validators: {
            required: null,
            minLength: 3
        }
    }),
    new DynamicInputModel({

        id: "SKUInput",
        maxLength: 150,
        placeholder: "SKU ví dụ xe-day-zaracos-cooper-555",
        validators: {
            required: null,
            minLength: 3
        }        
    }),
    new DynamicInputModel({

        id: "unitInput",
        placeholder: "Đơn Vị",
        maxLength: 20,
        list: ["Chiếc", "Đôi", "Bộ"],
        validators: {
            required: null,
            minLength: 3
        }
    }),  
    new DynamicInputModel({

        id: "priceInput",
        placeholder: "Giá VNĐ",
        validators: {
            required: null,
            pattern: "[1-9][0-9]{1,7}"
        }
    }),   
    new DynamicInputModel({

        id: "weightInput",
        placeholder: "Trọng Lượng (gam)",
        validators: {
            required: null,
            pattern: "[1-9][0-9]{1,6}"
        }
    }),   
];`
![screen shot 2017-04-16 at 00 04 54](https://cloud.githubusercontent.com/assets/747614/25065329/6436d1e6-2238-11e7-93c5-9c363ed2df2a.png)

**Comment by udos86** [comment]
@huynv86 use custom CSS classes as described in [README.md](https://github.com/udos86/ng2-dynamic-forms/blob/master/README.md#form-layouts)
