### ISSUE TITLE
how to add attribute type="number" for control input

### ISSUE THREAD

**Issue by huynv86** [udos86/ng2-dynamic-forms#334]
`    <input class="form-control" type="number" [(ngModel)]="bedrooms" name="bedrooms" required>
`
also, I need add style="width:100%" that look like this:
`<md-input-container class="mat-input-container ng-dirty ng-valid ng-touched" style="width:100%;">`
thank you so much

**Comment by udos86** [comment]
@huynv86 

1) use `inputType` property on `DynamicInputModel`
2) use custom CSS classes as describe in [README.md](https://github.com/udos86/ng2-dynamic-forms/blob/master/README.md#form-layouts)

**Comment by huynv86** [comment]
Please dont close my issues.
1. I used `inputType: "number"` and it works well BUT `this.formGroup.value` still returns string type like this `{bedrooms: "3"}`. I expect it will return number type like this `{bedrooms: 3}`
2. README.md only mentions Bootstrap, not Materialize. I know they have something are the same but it very hard to perform

**Comment by kdziurdz** [comment]
Hi there.

The issue should be reopened. Lets see why:
1. You have custom validator which only accepts number. example:


```
export function lessThanTenValidator(control: FormControl) {

  if (!control.value {
    return null;
  }
  if (typeof control.value !== 'number') {
    return {lessThanTenValidator: true};
  }
   if ( control.value >= 10 ) {
    return {lessThanTenValidator: true};
  }
 
  return null;
}
```

In regular Angular reactive forms, value of given FormControl is always number only if  the input has attribute `type="number"`

If i try to use my validator with ng2-dynamic-forms it's always called with value of type string which makes my validation fail.

Yes, i set `inputType` to `number`

BTW. Great lib, awesome job! :)

**Comment by udos86** [comment]
@kdziurdz Hi there!

Could you please tell which UI package you are using?

> BTW. Great lib, awesome job! :)

Thank you very much!

**Comment by udos86** [comment]
@kdziurdz Alright! Thanks for letting me know!

**Comment by keatkeat87** [comment]
issue closed ?
fixed ?

**Comment by neil-coutinho** [comment]
@udos86  any update on this issue? @kdziurdz ?
type = number always returns a string

**Comment by bobingham** [comment]
@udos86 - any update yet?

**Comment by cerino-ligutom** [comment]
Any update on this issue? Still present on Angular 8.2.13

**Comment by jocdominguez** [comment]
Please, i have same problem, please your support
