### ISSUE TITLE
checking if its possible...

### ISSUE THREAD

**Issue by hpn1975** [udos86/ng2-dynamic-forms#343]
I know, that I can update the values using valueupdates.  However, is it possible to directly update the FormControl using setvalue and get the updated value refreshed on the screen.  Or if there is a service where I can just pass the array of updated formcontrol values and the model is refreshed.
Looking for an easier way instead of doing a findbyid and doing a valueupdate.

Thanks

**Comment by udos86** [comment]
@hpn1975 

> However, is it possible to directly update the FormControl using setvalue and get the updated value refreshed on the screen

Yes, sure...

> Or if there is a service where I can just pass the array of updated formcontrol values and the model is refreshed.

No, sorry...

**Comment by hpn1975** [comment]
Thanks for answering and your time..
