### ISSUE TITLE
Problem subscribe in add FormModel and FormGroup

### ISSUE THREAD

**Issue by rodolfocop** [udos86/ng2-dynamic-forms#344]
Hi, first of all I would like to congratulate you for the component.

I'm having a usage problem in the following situation.

I have a query that returns me Observable<ItemXpto>, but when I perform the subscribe from that Observable and add it to my formModel and formGroup, my screen goes white as if it were nothing inside.

Ex does not work:

`observable.subscribe ((itemObservable) => {
 this.title = 'Test';
 this.formModel = itemObservable;
 this.formGroup = this.formService.createFormGroup (itemObservable);
});`

Ex works:

`this.title = 'Test';
This.formModel = itemXpto;
This.formGroup = this.formService.createFormGroup (itemXpto);
`

Has anyone ever experienced this?

**Comment by rodolfocop** [comment]
Hi, I solved this problem. 

I changed

public formModel: DynamicFormControlModel[] = null;

To
public formModel: Observable<DynamicFormControlModel[]>;

And add this ChangeDetectorRef in my constructor, within my method that is subscribe add markForCheck  from ChangeDetectorRef

**Comment by udos86** [comment]
@rodolfocop Thanks for your kind words and thumbs up for solving your problem!
