### ISSUE TITLE
Separate source files from .js files in node modules

### ISSUE THREAD

**Issue by brunoAltinet** [udos86/ng2-dynamic-forms#345]
The current published modules make the typescript compile it every time the app gets compiled because the emitted js files are in the same folder as .ts files.
Ts files should be in separate folder (eg. src) and js should be in build folder.

Additionally, it's impossible to use this library with noImplicityAny:true, because ts complains about errors in the module. See
https://github.com/Microsoft/TypeScript/issues/14787

It's just a matter of building the module correctly so i'm not sure if a PR would help

**Comment by udos86** [comment]
@brunoAltinet 

Ok I'll get rid of all `noImplicitAny` errors that are still left over. 

And In the next patch version I'm going to deliver only `*.d.ts` files.

**Comment by brunoAltinet** [comment]
Cool, thanks for a great job!

**Comment by udos86** [comment]
@brunoAltinet 

So far I've removed all `NoImplicitAny` errors from the library code. 

But I will keep on publishing the `.ts` files in npm packages as this essential for debugging.

> The current published modules make the typescript compile it every time the app gets compiled because the emitted js files are in the same folder as .ts files.
> Ts files should be in separate folder (eg. src) and js should be in build folder.

I cannot verify this as the `@ng2-dynamic-forms` and `node_modules` folder are excluded from transpiling in `tsconfig.json`.

**Comment by brunoAltinet** [comment]
@udos86 Yea, but they still do get compiled because excluding doesn't help if the referenced library/folder has .ts files in the same location as the emitted .js files. A good test would be to make a test project with an older build (with noimplicitany issue) referenced in node_modules, and exclude folder set. Typescript will ignore the exclusion because it's able to find .ts files in the referenced location, and it treats .ts files as a source of truth, and consequently it throws an error.
But it's a small library, and I appreciate the effort, so this will do:) Cheers!
