### ISSUE TITLE
Bind data values to model

### ISSUE THREAD

**Issue by StickNitro** [udos86/ng2-dynamic-forms#349]
How does one go about binding data values from an Entity to a Model, my scenario is that I have a model stored in a database as JSON and an entity loaded from the database.  I use ```this.formService.fromJSON(formJson)``` to create the instance of ```formModel``` so how does one go about binding the data of an entity to the model?

**Comment by udos86** [comment]
@StickNitro Thanks for your question!

In your case you would have to manually connect your entity.

For example, if you like to set a concrete value on your model, you'd use `valueUpdates` as described in [README.md](https://github.com/udos86/ng2-dynamic-forms#value-updates)

Other model properties can be updated directly.
