### ISSUE TITLE
Bootstrap Form Layout : class on formGoup : Grid and Row

### ISSUE THREAD

**Issue by jogelin** [udos86/ng2-dynamic-forms#350]
Hello,

What do you think about having the possibility to specify a class on the group element ?

If I want to use the grid system, I have to specify the class for both control and label:
```
...
        {
            grid: {
                control: 'col-sm-6',
                label: 'col-sm-6'
            }
        }
```

Is there a way to work on a group ?

```
<div class="col-sm-6 form-group">
    <label for="inputCompany">COMPANY</label>
    <input type="text" class="form-control" id="inputCompany" placeholder="Enter company" formControlName="company">
</div>
```
It could be:
```
...
        {
            grid: {
                group: 'col-sm-6'
            }
        }
```

I really appreciate your library. Especially because you are taking care of the form layout which is not easy when we talk about dynamic forms.

I think it could be good also to specify the row class (I already read #173 and the second solution is ok but it's a lot of code if we have many lines)

**Comment by udos86** [comment]
@jogelin

> I really appreciate your library. Especially because you are taking care of the form layout which is not easy when we talk about dynamic forms.

Thank you very much! Although a dynamic forms approach always limits your layouts in some way it's a major concern of mine to provide as much freedom as possible.

Concerning your issue I think you can already achieve this by using the `container` property in the `grid` object:

```
{
    grid: {
        container: "col-sm-9"
    }
}
```

Always appreciate someone's Bootstrap expertise here!

**Comment by udos86** [comment]
@jogelin

By the way, [here's](https://github.com/udos86/angular-forms-workshop/blob/master/src/app/sample-dynamic-forms/sample-dynamic-forms.model.ts) sample model on horizontal Bootstrap forms that also contains a group of two form controls inlined in a row.

**Comment by jogelin** [comment]
Indeed, container works to apply a style to the form-group. 

Just the name was not clear for me because "container" is also used in bootstrap grid to specify the breaking points in a responsive design.

For the "row" subject, it's important to specify the row class because bootstrap is using the negative padding which is corrected by the col class:

```
.row {
    margin-right: -15px;
    margin-left: -15px;
}

.col ....... {
    padding-right: 15px;
    padding-left: 15px;
}
```
If you use only the col class, you will add paddings that you don't want.

I tried a way by using groups and doing something like:
```
<div class="row" *ngFor="let groupModel of formModel">
    <dynamic-form-ng-bootstrap-control *ngFor="let controlModel of groupModel.group"
                                       [group]="formGroup"
                                       [model]="controlModel"
                                       [hasErrorMessaging]="controlModel.hasErrorMessages"></dynamic-form-ng-bootstrap-control>
</div>
```
But it fails on the dynamic-form-ng-bootstrap-control component  with:
```
ERROR TypeError: Cannot read property 'valueChanges' of null
    at DynamicFormNGBootstrapComponent.DynamicFormControlComponent.ngOnInit (core.es.js:1198)
    at checkAndUpdateDirectiveInline (core.es5.js:10705)
    at checkAndUpdateNodeInline (core.es5.js:12084)
    at checkAndUpdateNode (core.es5.js:12052)
    at debugCheckAndUpdateNode (core.es5.js:12681)
    at debugCheckDirectivesFn (core.es5.js:12622)
```

My other way for now is to create an array of DynamicFormGroupModel[] in my formModel that can be used in the template and flattenize it when I need to `createFormGroup`

**Comment by jogelin** [comment]
@udos86 
When I use the row class, the grid config on a control is not enough. You have to apply a col class on the dynamic-form-ng-bootstrap-control component to make it works. In my case, the structure of the generated dom is:
```
<form ... >
    ....
<div class="row">
    <dynamic-form-ng-bootstrap-control ...>
        <div class="form-group">
            <label>...</label>
            <input class="form-control" />
        </div>
    </dynamic-form-ng-bootstrap-control>
</div>
    ....
</form>
```

After some hacks, my reflexion is that the grid design approach is maybe in the wrong way. We should not apply a layout on a control. The layout should be specified on top of the controls and arrange them on the grid. In this way, the grid specifications could be extracted from the controls configurations. Then we can define controls and re-use them in many dynamic forms using different grid.

**My current (and ugly) approach:** https://plnkr.co/edit/rG9XLGZKfsxB0QZtkFoq?p=preview

For example, the layout could be specified when we do `this.formService.createFormGroup(this.formModel, this.formGrid)`

What do you think ?

**Comment by udos86** [comment]
@jogelin First of all THANKS for all your thoughts and providing sample code!

I can understand your point here. Making the grid configuration UI-agnostic would be a great thing to have. On the other side it would make the template logic much more complex than it is at the moment. Another scenario that still is a bit unclear to me  when someon would like to mix a grid system of a lib like Bootstrap with a different UI lib like Material.

Concerning your sample I still think you could have achieved this by using a model structure [like this](https://github.com/udos86/angular-forms-workshop/blob/master/src/app/sample-dynamic-forms/sample-dynamic-forms.model.ts). Am I wrong?

**Comment by jogelin** [comment]
@udos86 
My thinking is not to make the grid configuration UI agnostic, but splitting the grid configuration from  the components configuration. It exists also in the material library: 

* [Material](https://material.angular.io/components/component/grid-list)
* ...

Like you did for the component, you could do it for the layout configurations. Create abstract class for the layout configurations and put the implementations in each library.

But I can understand that it's not the point of this library.

Concerning the rows, yes I can do it in your way but it is not the way of bootstrap with class "row". You will have extra paddings with your solution....

**Comment by udos86** [comment]
@jogelin 

> But I can understand that it's not the point of this library.

I really like your approach and I'll keep it in mind for further refactorings.

> Concerning the rows, yes I can do it in your way but it is not the way of bootstrap with class "row". You will have extra paddings with your solution....

I respectfully disagree ;-)

Please have a look at this [live demo ](http://ng2-dynamic-forms.udos86.de/workshop/sample-dynamic-forms). It's the same form with three different approaches (template-driven, model-driven and  dynamic). It uses the Bootstrap grid as officially described [here](http://getbootstrap.com/css/#forms-horizontal).

But I may be wrong...

**Comment by jogelin** [comment]
@udos86 

Thank you !

Ok I understand now, you are talking about bootstrap v3, I am talking about bootstrap v4... You can see in the documentation that for [column sizing in forms](https://v4-alpha.getbootstrap.com/components/forms/#column-sizing), they use `row`

Maybe you should precise in the README that you are using bootstrap v3. 

May I advise to use bootstrap v4 ? I think that if people are using bootstrap with Angular v2+, they use bootstrap v4....

**Comment by udos86** [comment]
@jogelin Alright, just a misunderstanding :-)

> May I advise to use bootstrap v4 ? I think that if people are using bootstrap with Angular v2+, they use bootstrap v4....

I don't know, I mean, as long as Bootstrap 4 is still in alpha I would not want to update the `ui-bootstrap` package. It's development progress seems pretty slow to me at the moment.

**Comment by jogelin** [comment]
@udos86 I could agree for ui-bootstrap but ng-bootstrap is using bootstrap 4 so maybe ui-ng-bootstrap should use the bootstrap 4 rules.

**Comment by udos86** [comment]
@jogelin 

> so maybe ui-ng-bootstrap should use the bootstrap 4 rules

I thought it' already doing so ;-) Maybe there are still some flaws but ui-ng-bootstrap is definately using Bootstrap 4.
