### ISSUE TITLE
NG Bootstrap UI not implementing RadioGroup

### ISSUE THREAD

**Issue by jogelin** [udos86/ng2-dynamic-forms#351]
Hello,

I discovered that the RadioGroup of `NG Bootstrap UI` is the same one as the `Bootstrap UI`. 

`NG Bootstrap UI` proposes its own implementation: [NgbRadioGroup](https://ng-bootstrap.github.io/#/components/buttons)

Is there any reasons that you didn't use this one in `NG Bootstrap UI`?

Do you accept PR ?

**Comment by udos86** [comment]
@jogelin Thanks for pointing that out!

I'll introduce it in the next patch version.
