### ISSUE TITLE
NG Bootstrap UI - options in DynamicRadioGroupModel are displayed vertically

### ISSUE THREAD

**Issue by jogelin** [udos86/ng2-dynamic-forms#356]
Hello,

As you can see [HERE](https://plnkr.co/edit/Fvt7W6SLQY9iMoWzhh5s?p=preview), the options are displayed vertically which is not the way of [ng-bootstrap](https://ng-bootstrap.github.io/#/components/buttons), they are displayed horizontally.

It's caused by the `display: inline-flex;` property on the css class:
```
.btn-group, .btn-group-vertical {
    position: relative;
    display: -webkit-inline-box;
    display: -webkit-inline-flex;
    display: -ms-inline-flexbox;
    display: inline-flex;
    vertical-align: middle;
}
```

It's probably a class that you are using for all DynamicRadioGroupModel  ?

**Comment by udos86** [comment]
@jogelin Thanks for reporting this!

However I'm not actively applying the class `btn-group` in the template file. Maybe it's because I'm using a `fieldset` at the moment as container for the radio buttons?

The NG Bootstrap UI template is still pretty new so I'm thankful for all improvements.

**Comment by jogelin** [comment]
Indeed it's caused by the `fieldset`... Simply replace it by a div and it works
