### ISSUE TITLE
NG Bootstrap UI - cannot apply a class on the DynamicRadioGroupModel options

### ISSUE THREAD

**Issue by jogelin** [udos86/ng2-dynamic-forms#357]
Hello,

As you can see [HERE](https://plnkr.co/edit/Fvt7W6SLQY9iMoWzhh5s?p=preview), the class `btn-outline-primary` is not applied on the control options.

I think in this case, the class should be applied on the `label` field which is representing the option:
```
<fieldset *ngSwitchCase="7" ngbRadioGroup ...>
    <legend *ngIf="model.legend" [innerHTML]="model.legend"></legend>

    <label *ngFor="let option of model.options" class="btn btn-primary"> <-------APPLY THE CLASS HERE

        <input type="radio" ..../><span [innerHTML]="option.label"></span>
    </label>
</fieldset>
```

What do you think ?

**Comment by udos86** [comment]
@jogelin Yes, it think you found another weakness!

Maybe you'd like to improve the current template file on your own and provide a pull request?

**Comment by jogelin** [comment]
I would like to help with PR but:

- Impossible to install without kendo...why do you put libraries dependencies in the parent `package.json` ? It should be installed in each module no ?
- The travis build is failing because of kendo

**Comment by udos86** [comment]
@jogelin 

> why do you put libraries dependencies in the parent package.json

Because otherwise you're unable to make the sample application running via npm install. I haven't figured out a better solution for Kendo yet, although I'm aware that it's available open source.
