### ISSUE TITLE
NG Bootstrap UI - default selected value on the DynamicRadioGroupModel is not applied

### ISSUE THREAD

**Issue by jogelin** [udos86/ng2-dynamic-forms#358]
Hello,

As you can see [HERE](https://plnkr.co/edit/Fvt7W6SLQY9iMoWzhh5s?p=preview), the default value `false` is not applied.

**Comment by udos86** [comment]
@jogelin  Thanks for providing sample code!

I'm not 100% percent sure but this may probably be caused by your boolean values. I'll have to check but spontaneously I'd recommend using string values instead.

**Comment by jogelin** [comment]
@udos86 Indeed, it works with string value
