### ISSUE TITLE
Question: how to set library specific attributes of a control ?

### ISSUE THREAD

**Issue by SebLz** [udos86/ng2-dynamic-forms#359]
Hello,

I'm using ng2-dynamic-forms to build a form with kendo-ui dropdownlists.
Kendo ddls can have a filter when the attribute [filterable] is set to true (http://www.telerik.com/kendo-angular-ui/components/dropdowns/dropdownlist/filtering/).
Of course, this is something specific to the kendo control and DynamicSelectModel does not have such a property.
Is it possible to set this kind of attribute and while still using a dynamic model ?

Best regards,
Sébastien.

**Comment by udos86** [comment]
@SebLz First of thanks for trying out the Kendo UI package!

As you already pointed out the `filterable` property cannot be set at the moment when using a dynamic model. 

However this would make a nice enhancement in a future patch version. I'll check it.

**Comment by udos86** [comment]
@SebLz I've added commit 9e67f22 which will add this feature in the next patch version update.

**Comment by udos86** [comment]
@SebLz Ok, I checked this. 

Implementing this feature causes some effort. It actually demands that options should be set via Observables (see #165). Then the Kendo component could track changes on the dynamic source model to keep it's filterable data array in sync. I'll keep an eye on it.

**Comment by SebLz** [comment]
@udos86 Thanks for your replies and for this nice library. I'll follow the upcoming updates :).
