### ISSUE TITLE
Cannot bind dropdown list value to a non primitive type with kendo-ui

### ISSUE THREAD

**Issue by SebLz** [udos86/ng2-dynamic-forms#362]
Hello,

When you select a label in a DynamicSelectModel, the associated value can be either a primitive type (string, number, null) or a complex type (any object).

The Kendo-Ui implementation of ng2-dynamic-form only allows to return primitive types using this:
http://www.telerik.com/kendo-angular-ui/components/dropdowns/dropdownlist/value-binding/#toc-primitive-values-from-object-fields

If we have a model form such as DynamicSelectModel<MyComplexObject>[], you will have an error at runtime when you select something in the dropdownlist ("Expected initial value of primitive type"). This is normal since in the current code, the field "[valuePrimitive]" is always set to true: https://github.com/udos86/ng2-dynamic-forms/blob/master/modules/ui-kendo/src/dynamic-form-kendo.component.html#L155.

Best regards,
Sébastien.

**Comment by udos86** [comment]
@SebLz Thanks for your message! Could you provide a sample model?

Until now I've not been aware that the primitive binding can cause problems since `DynamicSelectModel` expects `DynamicFormOption[]` as options which are bound under the hood.

**Comment by SebLz** [comment]
@udos86 :
Here is how i initialize my form model (starting from a const myObject1FormModel):
`ngOnInit() {
        let options = sampleMyObject1s.map(v => {return {value: v, label: v.name}; }) as DynamicFormOption<MyObject1>[];
        this.formModel = myObject1FormModel;
        this.formModel.forEach(c => c.options = options);
    }`

For this to work with DynamicSelectControls and Kendo UI, I had to change [valuePrimitive] from "true" to "false" in https://github.com/udos86/ng2-dynamic-forms/blob/master/modules/ui-kendo/src/dynamic-form-kendo.component.html#L156. This is because I am not trying to return one of the property (that is [valueField]) of the object, but the whole object itself. This is again a behavior specific to Kendo UI.

**Comment by udos86** [comment]
@SebLz Thanks for giving some details on that!

I'll have to examine it further? Maybe you have a proposal on how to fix this?

**Comment by SebLz** [comment]
@udos86 unfortunately, I don't :(. Although I haven't compared with all the other UI components, I suspect this option "valuePrimitive" is kind of specific to KendoUI. Therefore I'm not too sure how to "generalize" this at the level of the DynamicSelectControl.
As a quick fix, I changed the default value of [valuePrimitive] in the template file because I believe it's more common/convenient to return the whole object than only one of its property. For the next update and until a better solution can be found, I suppose the value of [valuePrimitive] should be set to either true or false depending on what is the most used popular choice among KendoUI users.

**Comment by udos86** [comment]
@SebLz Ok, but isn't it possible for you to just set a primitive as `value` property?

```
let myOptions = [
    {
        label: "Option 1",
        value: "option-1",
    },
    {
        label: "Option 2",
        value: "option-2"
    },
    {
        label: "Option 3",
        value: "option-3"
    },
    {
        label: "Option 4",
        value: "option-4"
    }
];

new DynamicSelectModel<string>(
    {
        id: "kendoDropDownList",
        label: "Kendo DropDownList",
        options: myOptions
        value: myOptions[2].value
    }
)
```

Whenever another value is selected by the user you can then remap it to the original options object:
```
mySelectModel.valueChanges.subscribe(value => {
    let selectedOption = myOptions.filter(option => option.value === value);
});
```

Of course it's a little overhead but I can't see any further problems here.

**Comment by SebLz** [comment]
@udos86 You're right, it's probably the best solution thanks.
