### ISSUE TITLE
Running the Example -- out-of-date instructions

### ISSUE THREAD

**Issue by lukkuz** [udos86/ng2-dynamic-forms#363]
I cannot run examples as described in 'Running the Example` section since the instructions seems to be obsolete. There is no tsc script in package.json file. So my question is what is the correct way to run examples?

```
C:\devel\tmp\ng2-dynamic-forms>npm run tsc
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "tsc"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10

npm ERR! missing script: tsc
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\devel\tmp\ng2-dynamic-forms\npm-debug.log

```

**Comment by datencia** [comment]
Just the same over here. I did next steps to get it working:

**1. Clone the Git repository**:
```shell
$ git clone https://github.com/udos86/ng2-dynamic-forms.git
```

**2. Log in into your Telerik account (for Kendo UI)**:
```shell
$ npm login --registry=https://registry.npm.telerik.com/ --scope=@progress
```
> NPM will ask you for your Telerik account credentials and an email.
> This is necessary to install the kendo-ui packages.

**3. Install the npm dependencies**:
```shell
$ npm install
```

**4. Install example missing dependencies**:
```shell
$ npm install @ng2-dynamic-forms/ui-kendo @ng2-dynamic-forms/ui-ng-bootstrap --save
```
> I do not know why these packages are not listed in the `package.json` file.

**5. Transpile the TypeScript files**:
```shell
$ npm run compile:app:aot
$ npm run transpile:app:systemjs
```

**6. Run the sample application**:
```shell
$ npm start
```

I don't know if these are the right steps but it worked for me.

**Comment by udos86** [comment]
@lukkuz @datencia Thanks for reporting this! 

My mistake! I'll deliver an update as soon as possible.
