### ISSUE TITLE
Bugs in example

### ISSUE THREAD

**Issue by water42** [udos86/ng2-dynamic-forms#367]
- In `bootstrap-example.component.ts` `DynamicSelectModel` requires a type argument. Step 4 in "Running the example" fails because there are no type arguments
- `npm run transpile:app:systemjs` fails because of the single quotes around `common.js`:

`error TS6046: Argument for '--module' option must be: 'none', 'commonjs', 'amd',
 'system', 'umd', 'es6', 'es2015'.`

I fixed both of these locally but I'm not sure if the issues are OS specific or something

**Comment by udos86** [comment]
@water42 Should have been by latest commit...
