### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by skie** [udos86/ng2-dynamic-forms#37]
I'm including "@ng2-dynamic-forms/core": "1.0.0-alpha.8"

On build i have next error.
[default] ./node_modules/@ng2-dynamic-forms/core/src/service/dynamic-form.service.d.ts:2:34
Cannot find module './dynamic-form.model'.

So I checked npm cache package file npm-cache/@ng2-dynamic-forms/core/1.0.0-alpha.8/package.tgz
so inside of it we have src/service/dynamic-form.service.d.ts and it starts from next lines.
import { FormBuilder } from "@angular/forms";
import { DynamicFormModel } from "./dynamic-form.model";

But correct path to dynamic-form.model should be ../model/dynamic-form.model
and for example dynamic-form-control.component.d.ts has it.

Also I have error that already solved by pull request i sent today.
getting error "Type 'void' is not assignable to type 'FormGroup'" for code " this.form = this.dynamicFormService.createFormGroup(this.dynamicFormModel);" where "form: FormGroup;"

**Comment by udos86** [comment]
should be fixed in alpha.9 #38 

Thanks for your contribution!
