### ISSUE TITLE
Error about 'typeof Observable

### ISSUE THREAD

**Issue by rainstormza** [udos86/ng2-dynamic-forms#372]
![image](https://cloud.githubusercontent.com/assets/4003032/26489057/01b981f4-4230-11e7-8be4-0eb8cc40dd4f.png)

my step 

ng new project
`npm install @ng2-dynamic-forms/core --save`
`npm install @ng2-dynamic-forms/ui-bootstrap --save`

import { ReactiveFormsModule } from "@angular/forms";
import { DynamicFormsCoreModule } from "@ng2-dynamic-forms/core";
import { DynamicFormsBootstrapUIModule } from "@ng2-dynamic-forms/ui-bootstrap";

imports: [
        DynamicFormsCoreModule.forRoot(), 
        DynamicFormsBootstrapUIModule, 
        ReactiveFormsModule
        // ...all remaining imports
    ],

ng serve

Did I miss something ?

**Comment by udos86** [comment]
@rainstormza Thanks for reporting this!

Trying to deliver a bugfix as soon as possible.
