### ISSUE TITLE
Is that will passible set value when init the DynamicFormControlModel

### ISSUE THREAD

**Issue by lvdream** [udos86/ng2-dynamic-forms#374]
Here is detail

i will get the Rest-Data from server, and the sample data will be JSON-Object, ex "{xx:'22',yy:'tt'}", and i want to set those object into the DynamicXX, it will be `new DynamicInputModel({

    id: "mmCode",
    label: "mmCode",
    placeholder: "mmCode",
    value: obj.xx
    validators: {
      required: null,
      maxLength: 25
    }
  } `

so do you any solution in the case, or any example for me, thanks

**Comment by udos86** [comment]
@lvdream see [here](https://github.com/udos86/ng2-dynamic-forms#json-export-and-import)

**Comment by lvdream** [comment]
Hi Bro
i had check your reference, but i think it is not right formatter which i want to.
just want post data will be like 
`{"basicGroupInput":"55","basicGroupInput1":"3","basicGroupInput2":null,"basicGroupInput3":null,"basicGroupInput4":"1"}`
which converted in this way
`JSON.stringify(this.formGroup.value)`.

i will get data from Rest-Url, and the response data will be the same formatter.
`JSON.stringify(this.formModel)` will generate huge data, most of them is useless in this case when i post them to the Server side, so that is my requirement, do you have any ideas, thanks a lot :)

**Comment by udos86** [comment]
@lvdream Sorry there's no automation for this. You'd have to merge objects manually.
