### ISSUE TITLE
Rearrange controls using drag and drop

### ISSUE THREAD

**Issue by anikets43** [udos86/ng2-dynamic-forms#376]
Is it possible to incorporate rearrangement of controls using drag and drop and also json gets shuffled accordingly?

**Comment by udos86** [comment]
@anikets43 `DynamicFormService` offers functions to move form controls of a `FormGroup` or a `FormArray`. However drag & drop is currently not supported.

**Comment by SamuelMarks** [comment]
Any chance we can reopen this issue?

Would be a great enhancement 👍

**Comment by udos86** [comment]
@SamuelMarks Hi Samuel!

> Any chance we can reopen this issue?

I'm sorry, but there are currently no plans to support this.
