### ISSUE TITLE
FormArray fields value updating

### ISSUE THREAD

**Issue by garnikmkrtchyan** [udos86/ng2-dynamic-forms#378]
Hi
I have some problems when try to use FormArray functionality.

![issue](https://cloud.githubusercontent.com/assets/13833124/26633204/b74b7760-4623-11e7-82c3-c11848b5a09b.jpg)

In each row I have 2 select boxes, and the options of second select box depends on first select box value.
I found the solution of this problem. After onChange() action in first select box I remove the appropriate row from **arrayModel**, change the **createGroup** method implementation and insert the row in old place. Now the problems.

1. I don't know which row select box value changed. I can't pass the row number to my method.
2. Because of **problem 1** I decide remove all rows where select box Id and Value equal to $event.model ID and Value. after that I try to return old values to my fields like this, and nothing happened.
`
(this.arrayModel.groups[rowNum].group[itemVal] as DynamicFormValueControlModel<string>).valueUpdates.next(array[+itemVal]);`

When I try after this line of code recreate FormGroup and ArrayControl, like this:
`this.formGroupGrid = this.formService.createFormGroup(this.formModelGrid);
this.arrayControl = <FormArray> this.formGroupGrid.get(RlappConstants.gridName);`
I get an error 

I can give you plunker example upon your request.

P.S
Thanks for great library )

**Comment by udos86** [comment]
@garnikmkrtchyan Thanks for your message!

After reading through your issue my conclusion is that adding additional information to the `change` event for `FormArray` controls would solve your problem, right?

**Comment by garnikmkrtchyan** [comment]
It will solve my problem partially. Even if I know which row I must replace, the valueUpdateing functionality doesn't work in this case.

**Comment by udos86** [comment]
I think it would solve your problem as long as you avoid recreating the `FormGroup` again because I assume this leads to a mess of lost references.

You already figured out correctly how to update the value of a `FormArray` control:
`this.arrayModel.get(1).get(0).valueUpdates.next("new value");
`

So if we extend the `change` event by adding a `context` information from which you can read the row index you could directly call `valueUpdates`.

**Comment by garnikmkrtchyan** [comment]
Thanks for your answer @udos86 . 
I can give you some additional info about this issue, that may help you later.

After creating a FormArray (that contain only one row), I call Initialize method to fill it from my dataset. All this work fine, row after row it create and fill my grid. 

But if I try later update some rows values by same mechanism, I get errors. From that errors I understand, that inner structure of FormArray was broken, and some references contain wrong (maybe old) values. 

That's all about this. Now my problem solved by another way, and I hope that you can provide a more simple mechanism to valueUpdating.

**Comment by udos86** [comment]
@garnikmkrtchyan Ok!

Nevertheless `1.4.12` will deliver some enhancement for `DynamicFormControlEvent`.
