### ISSUE TITLE
model-based error messaging with kendo control

### ISSUE THREAD

**Issue by SebLz** [udos86/ng2-dynamic-forms#386]
Hello,

When I try to use the model-based error messaging for a kendo control (same code as [https://github.com/udos86/ng2-dynamic-forms#validation-messaging](url) but with dynamic-form-kendo-control) , I get the following error at runtime:

> bootstrap error Error: Template parse errors:
> Can't bind to 'hasErrorMessaging' since it isn't a known property of 'dynamic-form-kendo-control'.

A quick look at the code shows that dynamic-form-kendo.component does simply not seem to implement it (contrary to dynamic-form-bootstrap.component).
Is there any reason for this or would it be possible to add that feature for kendo control too ?

**Comment by udos86** [comment]
@SebLz 

The reason why error messaging currently is not working in Kendo UI components is that Progress does not give any information on this so far. I'll take care of it.
