### ISSUE TITLE
DynamicSelectModel does not mark "false" on a yes/no <select>

### ISSUE THREAD

**Issue by renatoaraujoc** [udos86/ng2-dynamic-forms#388]
Hello @udos86,

I've just upgraded to Angular 4.1.3 and your library is on 1.4.11.

A **new bug** was introduced wheres the following code does not work:

```
// The <option value="false">No</option> does not get selected here.
let tehBoolean: boolean = false;
new DynamicSelectModel({
        id: 'someCoolSelectBro',
        required: true,
        options: [true, false].map(v => ({ value: v, label: v ? 'Yes' : 'No' })),
        value: tehBoolean
});
```

Could you please check it?

Thank you!

**Comment by udos86** [comment]
@renatoaraujoc Practically, you're right!

However my recommendation in general is to not use boolean values in conjunction with option controls. Insert `"false"` instead of `false`.

**Comment by renatoaraujoc** [comment]
Hello @udos86,

It'd be hackish to use "false" instead of false itself, it defeats the generic purpose of the model itself.

The (boolean) false was working correctly on earlier versions. Are you planning on a fix for this?

Thank you!

**Comment by udos86** [comment]
@renatoaraujoc I don't know what to fix here. Options are bound via `ngValue` under the hood and Angular has not documented any changes on this topic lately. What UI package are you using?

> It'd be hackish to use "false" instead of false itself

From a UX point of view it seems hackish to use a select menu for an either/or decision.

**Comment by renatoaraujoc** [comment]
Hello again @udos86,

I've searched for the issue, did look at your code which renders the <select> tags and found that this would work:

```
// myVar is a class property and switch() does this.myVar = !myVar;
// both <select>s below will work.
<select [(ngModel)]="myVar">
<select [(value)]="myVar">
            <option value="false">false</option>
            <option value="true">true</option>
</select>
<a class="btn btn-primary" (click)="switch()">switch</a>
```

You can test your code yourself and see that working with booleans this way works as expected.
And yes, I have a requirement where the Yes/No has to be in a select (not radio).

Can we work out a solution for this where people willing to use booleans on <select> tags?

Thank you again,

Renato

**Comment by renatoaraujoc** [comment]
```
<select [(value)]="myVar">
            <option value="false">false</option>
            <option value="true">true</option>
</select>
<a class="btn btn-primary" (click)="switch()">switch</a>
```

**Comment by udos86** [comment]
@renatoaraujoc Sorry but ng2 Dynamic Forms purely relies on ReactiveFormsModule, so `[(ngModel)]` is no solution here.
