### ISSUE TITLE
Angular 4 support

### ISSUE THREAD

**Issue by 99sono** [udos86/ng2-dynamic-forms#394]
HI,

I was about to test this library, but it seems that currently only angular 2 is supported.

If you're working with the latest angular release:
`npm install @angular/cli `

And then start a new angular project ... you are working with angular 4.

In this case, the first step of installing the base library for dynamic forms, as per the guide works fine.
The problem comes up when you install the sub-module for bootstrap.

In this case you shall get the warning:
 ```
@ng2-dynamic-forms/ui-bootstrap@1.4.12
└── UNMET PEER DEPENDENCY angular2-text-mask@^8.0.1

```
Any suggestion on this?

Many thanks.

**Comment by udos86** [comment]
@99sono 

Everything's working fine with latest `@angular 4.2.1`

`angular2-text-mask` is a new dependency introduced by `1.4.12` in order to support text masks (see #379).

**Comment by 99sono** [comment]
Why then, do I get this error when doing npm install unmet peer dependency when trying to install the binding to boostrap? 

The base dynamic form package installs fine, but not the extensions to work with boostrap.

Do you have an Idea?

**Comment by udos86** [comment]
You need to manually install the peer dependency angular2-text-mask
