### ISSUE TITLE
UI NG Bootrstrap : Cannot find module 'angular2-text-mask'

### ISSUE THREAD

**Issue by jogelin** [udos86/ng2-dynamic-forms#398]
`node_modules/@ng2-dynamic-forms/ui-ng-bootstrap/src/ui-ng-bootstrap.module.ts (6,32): Cannot find module 'angular2-text-mask'.`

It seems that the module @ng2-dynamic-forms/ui-ng-bootstrap use the 'angular2-text-mask' library but it doesn't specify this library in the dependencies:

```
  "peerDependencies": {
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/common": "^4.0.0",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.26",
    "@ng2-dynamic-forms/core": "^1.4.12",
    "bootstrap": "^4.0.0-alpha.6",
    "rxjs": "^5.2.0"
  }
```

**Comment by udos86** [comment]
@jogelin 

Yep, thank for reporting this! Will be fixed with the next patch.

You can read about the text mask feature [here](https://github.com/udos86/ng2-dynamic-forms#text-masks).

**Comment by timmyrosen** [comment]
I'm having the same issue with the ui-ionic module.

**Comment by udos86** [comment]
@timmyrosen Hi!

Mmh, is the package really properly installed? 

It's a peer dependency - you need to manually install it.

**Comment by timmyrosen** [comment]
@udos86 Yeah I figured, it works now after I installed it, but the thing is i'm not using it. Do I have to install it even if I don't need it?

**Comment by udos86** [comment]
@timmyrosen 

> Do I have to install it even if I don't need it?

Unfortunately, yes, you have.

Since Angular does not support any kind of dynamic module imports this has to be done at compile time.

In your case this generates some overhead, I'm afraid.

Sorry!

**Comment by xjose97x** [comment]
I believe it would be better to have this mentioned earlier in the readme.
Had a hard time figuring out this was a needed dependency.

**Comment by alex-eri** [comment]
"@ng-dynamic-forms/core": "^5.4.6",
    "@ng-dynamic-forms/ui-material": "^5.4.6",

Same error

**Comment by idilshod87** [comment]
@alex-eri 
try npm install angular2-text-mask --save
