### ISSUE TITLE
Cannot find module 'protractor'

### ISSUE THREAD

**Issue by garnikmkrtchyan** [udos86/ng2-dynamic-forms#402]
Hi. I try to update library version to 1.4.12, but in the end I get an error. 
Error at D:/Projects/XXXXX/node_modules/@ng2-dynamic-forms/core/src/service/dynamic-form.service.ts:49:23: Cannot find module 'protractor'.

**Comment by udos86** [comment]
@garnikmkrtchyan Thanks for reporting this!

Somehow this import accidentally slipped in. I'll deliver a patch this weekend.
