### ISSUE TITLE
Type 'MdFormControlType' is not assignable to type 'string'

### ISSUE THREAD

**Issue by kbchandiran** [udos86/ng2-dynamic-forms#405]
Hi,
i am using angular 4.2.3 and material 2.0.0-beta.6 and i follow your instruction and compare with you demo but i get this error:

ERROR 
/node_modules/@ng2-dynamic-forms/ui-material/src/dynamic-form-material.component.ts (35,13): In 'const' enum declarations member initializer must be constant expression.

Type 'MdFormControlType' is not assignable to type 'string'.

Can you please help me? Is it the angular or material version?
Thanks

**Comment by kilroy05** [comment]
Looks like it's broken (version 1.4.14) for me as well
If you downgrade to 1.4.12, you should be fine

**Comment by kbchandiran** [comment]
@kilroy05 what i should downgrade to 1.4.12?

**Comment by kilroy05** [comment]
ng2-dynamic-forms
and what ever you are using - dynamic-form-material in your case

**Comment by kbchandiran** [comment]
@kilroy05 Thank a lot!! it's working fine.

**Comment by kilroy05** [comment]
No worries, glad it  works

**Comment by udos86** [comment]
@kbchandiran There'll be a patch tonight for this

@kilroy05 Thanks for helping out

**Comment by kilroy05** [comment]
@udos86 my pleasure. thanks for making this package available. saved me a lot of work :)
