### ISSUE TITLE
Cross field validation for input group

### ISSUE THREAD

**Issue by chintan11192** [udos86/ng2-dynamic-forms#406]
Is it possible to implement a cross field validation, like FROM date and TO date, or minimum and maximum amount range, where amount entered in min and amount entered in max should be greater than min.
I have attached few screenshots of where I need to add custom validations.

![date](https://user-images.githubusercontent.com/20302569/27281385-480e09f4-5509-11e7-84a1-f1bbe8f32cd5.PNG)
![amount](https://user-images.githubusercontent.com/20302569/27281384-480cf276-5509-11e7-91be-6cd8e1cb89cb.PNG)

**Comment by udos86** [comment]
@chintan11192 Sorry, you'd have to manually implement such a validation. 

BTW: Lately Angular introduced `min` and `max` validators. You can use these out of the box.
