### ISSUE TITLE
Error while compiling with angular 4

### ISSUE THREAD

**Issue by drik** [udos86/ng2-dynamic-forms#409]
[ERROR] Error at D:/SURVEYOR/surveyor-web/node_modules/@ng2-dynamic-forms/ui-bootstrap/src/dynamic-form-bootstrap.component.ts:21:13: In 'const' enum declarations member initializer must be constant expression.
[ERROR] Error at D:/SURVEYOR/surveyor-web/node_modules/@ng2-dynamic-forms/ui-bootstrap/src/dynamic-form-bootstrap.component.ts:22:16: In 'const' enum declarations member initializer must be constant expression.
[ERROR] Error at D:/SURVEYOR/surveyor-web/node_modules/@ng2-dynamic-forms/ui-bootstrap/src/dynamic-form-bootstrap.component.ts:23:13: In 'const' enum declarations member initializer must be constant expression.
[ERROR] Error at D:/SURVEYOR/surveyor-web/node_modules/@ng2-dynamic-forms/ui-bootstrap/src/dynamic-form-bootstrap.component.ts:24:13: In 'const' enum declarations member initializer must be constant expression.
[ERROR] Error at D:/SURVEYOR/surveyor-web/node_modules/@ng2-dynamic-forms/ui-bootstrap/src/dynamic-form-bootstrap.component.ts:25:18: In 'const' enum declarations member initializer must be constant expression.
[ERROR] Error at D:/SURVEYOR/surveyor-web/node_modules/@ng2-dynamic-forms/ui-bootstrap/src/dynamic-form-bootstrap.component.ts:26:14: In 'const' enum declarations member initializer must be constant expression.
[ERROR] Error at D:/SURVEYOR/surveyor-web/node_modules/@ng2-dynamic-forms/ui-bootstrap/src/dynamic-form-bootstrap.component.ts:27:16: In 'const' enum declarations member initializer must be constant expression.
[ERROR] Error at D:/SURVEYOR/surveyor-web/node_modules/@ng2-dynamic-forms/ui-bootstrap/src/dynamic-form-bootstrap.component.ts:36:14: Class 'DynamicFormBootstrapComponent' incorrectly extends base class 'DynamicFormControlComponent'.
[ERROR]   Types of property 'type' are incompatible.
[ERROR]     Type 'BootstrapFormControlType' is not assignable to type 'string'.
[ERROR] error Command failed with exit code 1.
[INFO] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[ERROR] error Command failed with exit code 1.
[INFO] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[ERROR] error Command failed with exit code 1.
[INFO] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by udos86** [comment]
@drik I'll deliver a patch as quick as possible

**Comment by drik** [comment]
It's working now. COOL
