### ISSUE TITLE
Kendo Cannot read property 'startsWith'

### ISSUE THREAD

**Issue by stekontar** [udos86/ng2-dynamic-forms#411]
I just update the modules of core + kendo ui and i am getting the following error
ERROR TypeError: Cannot read property 'startsWith' of null
  at DynamicFormKendoComponent.webpackJsonp.../../../../@ng2-dynamic-forms/ui-kendo/bundles/ui-kendo.es.js.DynamicFormKendoComponent.setTemplates 

any suggestions

**Comment by udos86** [comment]
@stekontar Thanks for reporting this! There'll be a fix in the next version update.

**Comment by udos86** [comment]
fixed in `1.4.16`
