### ISSUE TITLE
(New on v1.4.1) Error: customValidator is not provided via NG_VALIDATORS or NG_ASYNC_VALIDATORS

### ISSUE THREAD

**Issue by rahul-winner** [udos86/ng2-dynamic-forms#417]
@udos86 & Team. 

Although it looks very much related to this issue #271 . 
However, I'm getting this error even in development build. On investigation, I noticed that the method "getCustomValidatorFn" of DynamicFormService is getting 'this.NG_VALIDATORS' as null. Consequently, it does not even check whether custom validator functions exists or not and eventually fails. 

Please take a look on below image which shows the stack trace on debugger.

**Note:** I'm using ng2-dynamic-forms version : 1.4.4

![image](https://user-images.githubusercontent.com/4982751/27495239-bbcd95d6-586e-11e7-84d5-a7acea365bf3.png)

I'm not sure if I'm missing something terribly here. Or if there is any known problem.

This is blocking our development as that custom validator is needed for a business validation. Kindly let me know if you need elaboration. 

I'll be glad to get any kind of help.

Thanks a lot !!

**Comment by udos86** [comment]
@rahul-winner 

I could not verify any new bug here. 

You can check the sample application in this repository as well as my new [alternate sample](https://github.com/udos86/ng-forms-workshop).

Did you provide your validator function in  your app module like this?

```
  providers: [
    { provide: NG_VALIDATORS, useValue: myCustomValidator, multi: true },
  ]
```

**Comment by rahul-winner** [comment]
thanks @udos86 
It helped. I haven't added validator function in app module. I've added the function to app module and my validator stats working. 

By the way I've couple of follow up queries:

- Why do we need to add validator function to add module. I could not see any such instruction in [this ](https://blog.thoughtram.io/angular/2016/03/14/custom-validators-in-angular-2.html) blog as well. Is this needed only for forms using 'ng2-dynamic-forms'??

- I tried adding the validator function to my lazily loaded (sub module) module and it didn't work. I could make it only when I add the function to app (root) module. I am not able to understand why it didn't work with lazily loaded modules. 

Answers to above queries will help me to understand dynamic forms better. 

Thanks a lot !

**Comment by udos86** [comment]
@rahul-winner These are good questions

> Why do we need to add validator function to add module. I could not see any such instruction in this blog as well. Is this needed only for forms using 'ng2-dynamic-forms'?

Indeed, when using Reactive Forms (which ng2 Dynamics Forms relies on under the hood) there's no need to provide a validator function via `NG_VALIDATORS`. 

However to provide JSON export for validators, ng2 Dynamic Forms let's you define a validator just by it's function name. In order to recreate that model now from JSON the function name needs to be matched agains some global injection token. That's why I utilize `NG_VALIDATORS` and Angulars multi provider mechanism here.

> I tried adding the validator function to my lazily loaded (sub module) module and it didn't work. I could make it only when I add the function to app (root) module. I am not able to understand why it didn't work with lazily loaded modules.

Since `DynamicFormService` is provided `forRoot()` all `NG_VALIDATORS` need to be provided on root level as well.

**Comment by rahul-winner** [comment]
Thanks a lot @udos86 for insight. It was helpful.

Nevertheless, I'd like to share one more observation. I noticed that that custom validator does not get invoked when I provide 'null' against it [like it worked for 'required' validator] in model something like below

```
{
            id: "config",
            label: "Config",
            validators: {
                required: null,
                **customCacheConfigValidator : null**
            },
            errorMessages: {
                required: "Field is required",
                customCacheConfigValidator : "Please provide valid value for cache config."
            }
        }
```

What do you say? Am I missing anything here? Or custom validator has to be provided with some non-null value for dynamic form model. 

Thanks. Rahul
