### ISSUE TITLE
review accessibility

### ISSUE THREAD

**Issue by udos86** [udos86/ng2-dynamic-forms#42]

**Comment by bbarry** [comment]
A few things I notice (not particularly focusing on testing this and haven't really studied the code to understand how the various UI versions are related; these are just the things that annoy me when using a typical form) from the demo site:

* clicking on select label should focus select dropdown
* clicking on input label should focus on input
* clicking on checkbox group should focus first checkbox in group (or perhaps cycle: check/uncheck/reset to original state for whole group?)
* clicking on individual checkbox label should check/uncheck box
* clicking on radio group label should focus current active radio option
* clicking on text area label should focus text area
* clicking on array model group input label should focus first/last/first empty (not sure which)? input
* clicking on add item in group input should focus newly added input
* in an group input input, pressing tab to new item button/link then pressing space should focus newly added input

demo should show validation states visually somehow also

On the bright side, tab works pretty good to move around.

**Comment by udos86** [comment]
@bbarry Thanks for your contribution.

> clicking on select label should focus select dropdown
> clicking on input label should focus on input
> clicking on checkbox group should focus first checkbox in group (or perhaps cycle: check/uncheck/reset to original state for whole group?)
> clicking on individual checkbox label should check/uncheck box
> clicking on radio group label should focus current active radio option
> clicking on text area label should focus text area
> clicking on array model group input label should focus first/last/first empty (not sure which)? input
> clicking on add item in group input should focus newly added input

The flaw of not selecting a form control when clicking on it's label arises from the fact that no `id` attributes are bound to the html elements at the moment. This is necessary in order to not create semantically wrong markup when using form arrays. Otherwise there potentially would exist multiple form controls with the same id value. I haven't a better solution to this right now.

> demo should show validation states visually somehow also

The importance of showing validation messages and how this should be done is explained in detail in [`README.md`](https://github.com/udos86/ng2-dynamic-forms#validation-messaging). However it is not part of the actual library.

**Comment by bbarry** [comment]
Reviewing the markup for the individual checkboxes, I believe removing the `for` attribute would be sufficient (a label surrounding a single input is historically adequate for semantically associating them).
w3.org agrees: https://www.w3.org/WAI/tutorials/forms/labels/#associating-labels-implicitly

**Comment by udos86** [comment]
@bbarry Alright, thanks!

**Comment by udos86** [comment]
@bbarry There'll be a solution for focusing the controls when clicking the labels, as well!
