### ISSUE TITLE
Dropdown field with surrounding text

### ISSUE THREAD

**Issue by kahboom** [udos86/ng2-dynamic-forms#421]
The following would be a use case: `Check for the following only if text matches ['all','any'] of the following: <input>`, where `['all','any']` is an array for a dropdown and `<input>` is a text field. I'm likely going to have to put this into a single group.

Any idea how to do this?

**Comment by kahboom** [comment]
In other words, how can I use ng2-dynamic-forms to create complex filter forms?

**Comment by udos86** [comment]
@kahboom Hi! 

I'm not sure if I fully understand your use case.

I guess you already had a look at the chapter on (`Related Form Controls`)[https://github.com/udos86/ng2-dynamic-forms#related-form-controls].

What exactly do you mean by complex filter form?

**Comment by kahboom** [comment]
Thanks for the prompt response @udos86 ! I was looking for a way to implement something like this using Bootstrap styling (including inline forms, groups, etc) and the ability to add field groups dynamically:

<img width="892" alt="screenshot 2017-07-11 15 16 39" src="https://user-images.githubusercontent.com/3844502/28086136-f9e5d230-664b-11e7-948e-42da1805a8cd.png">

It looks like ng2-dynamic-forms does handle this, although I'd need to see how to use Bootstrap styling proprely. It turns out it's a project-specific thing (the project I'm working on) that limits my ability to do that, so I'll need to refactor that in the future. Since I'm short on time I think for this specific form I'll just use regular forms and keep using ng2-dynamic-forms for all other forms in the project though. Again, many thanks! 👍

**Comment by udos86** [comment]
@kahboom Great to hear! Thanks for using the lib!

**Comment by kahboom** [comment]
Okay, reopening for a quick, related question, since I decided to go back to using ng2-dynamic-forms after all for this filter lol.. I have something like this at the moment, using ui-bootstrap:

<img width="1305" alt="screenshot 2017-07-18 17 00 46" src="https://user-images.githubusercontent.com/3844502/28340288-291beed6-6bdd-11e7-8179-486e31a6f912.png">

I would like to wrap the "of the following" text in the top form group to be inline with the select model (if you see the screenshot of the design I posted above, it's number 2 of the fields), so that it's not _within_ the field. Is this possible to do with the model file, or what would you suggest?

It uses the following model:

```
export const BASIC_FILTER_MODEL = [
  new DynamicFormGroupModel({
    id: 'filterSettingsGroup',
    group: [
      new DynamicSelectModel<string>(
        {
          id: 'matchSelect',
          label: 'Continue only if incoming data match ',
          options: Observable.of([
            {
              label: 'ALL of the following',
              value: 'all',
            },
            {
              label: 'ANY of the following',
              value: 'any',
            },
          ]),
          value: 'all',
        },
        {
          element: {
            //container: 'form-group',
            label: 'control-label pull-left',
          },
          grid: {
            control: 'col-xs-3',
          },
        },
      ),
    ],
  }),

  new DynamicFormGroupModel({
    id: 'rulesGroup',
    group: [
      new DynamicFormArrayModel(
        {
          id: 'rulesFormArray',
          initialCount: 5,
          groupFactory: () => {
            return [
              new DynamicInputModel(
                {
                  //hint: 'Just a sample help text',
                  id: 'dataToBeFiltered',
                  maxLength: 51,
                  placeholder: 'Status.Text',
                  suffix: 'Browse...', // This is just a suffix; this whole field needs to change
                  /*
                  validators: {
                    required: null,
                    maxLength: 5,
                  },
                  errorMessages: {
                    //required: '{{ label }} is required',
                    required: 'Please select data to filter',
                    maxLength: 'Max character count is 5',
                  },
                  */
                },
                {
                  element: {
                    container: 'form-group col-xs-3',
                    //label: 'control-label',
                  },
                  grid: {
                    control: 'input-group',
                    //errors: 'col-xs-offset-3 col-xs-3',
                  },
                },
              ),
              new DynamicSelectModel<string>(
                {
                  id: 'conditions',
                  options: Observable.of([
                    {
                      label: 'Contains',
                      value: 'contains',
                    },
                    {
                      label: 'Does Not Contain',
                      value: 'does-not-contain',
                    },
                    {
                      label: 'Matches Regex',
                      value: 'matches-regex',
                    },
                    {
                      label: 'Does Not Match Regex',
                      value: 'does-not-match-regex',
                    },
                    {
                      label: 'Starts With',
                      value: 'starts-with',
                    },
                    {
                      label: 'Ends With',
                      value: 'ends-with',
                    },
                  ]),
                  value: 'contains',
                },
                {
                  element: {
                    container: 'form-group col-xs-3',
                    label: 'control-label',
                  },
                  grid: {
                    control: 'input-group',
                  },
                },
              ),
              new DynamicInputModel(
                {
                  id: 'valueToCheckFor',
                  placeholder: 'e.g. Red Hat',
                },
                {
                  grid: {
                    container: 'input-group',
                  },
                },
              ),
            ];
          },
        },
        {
          element: {
            container: 'form-inline form-array',
          },
          grid: {
            //control: 'col-xs-12',
          },
        },
      ),
    ],
  }),
];
```

With the following HTML:

```
<form [formGroup]="formGroup">
        <dynamic-form-bootstrap-control *ngFor="let controlModel of basicFilterModel"
                                        [group]="formGroup"
                                        [model]="controlModel"
                                        (blur)="onBlur($event)"
                                        (change)="onChange($event)"
                                        (focus)="onFocus($event)">
          <ng-template modelId="rulesFormArray"
                       let-context="context"
                       let-index="index">
            <div class="pull-right">
              <button type="button"
                      class="btn btn-danger btn-sm rounded"
                      (click)="remove(context, index)">&#10005;
              </button>
              <button type="button"
                      class="btn btn-default btn-sm rounded"
                      (click)="move(context, index, -1)">&#9650;
              </button>
              <button type="button"
                      class="btn btn-default btn-sm rounded"
                      (click)="move(context, index, 1)">&#9660;
              </button>
              <button type="button"
                      class="btn btn-success btn-sm rounded"
                      (click)="insert(context, index + 1)">&#43;
              </button>
            </div>
          </ng-template>
        </dynamic-form-bootstrap-control>
      </form>
```

Also, any general suggestions you can provide would be very helpful. Doing a demo using your wonderful library this Friday. :) Thanks again.

**Comment by kahboom** [comment]
And, yes, I need to update that prefix input field to instead be a file uploader :joy:. Really leaving things for last minute here.

**Comment by kahboom** [comment]
I had a few other questions, which of course I can't think of at the moment. One was that for some reason, those buttons that appear (the up/down, add, remove buttons for each row) only appear when the mouse clicks anywhere on the page, or focuses on the form. I will do some debugging on this, but was wondering if you had any ideas off the top of your head as to why this could be happening. Thanks in advance!

**Comment by udos86** [comment]
@kahboom Thanks for your kind words!

In order to place your text inline with but outside the actual select control I'd suggest that you simply use a custom template:
```
<ng-template modelId="matchSelect">

    <p class="col-sm-2">of the following</p>

</ng-template>
```

Unfortunately I cannot verify your rendering issues in my samples. @rernens reported some similar problems (see #431) but at the moment I'm not able to reconstruct that behavior.

**Comment by kahboom** [comment]
Thank you @udos86! Especially for the quick response. Regarding that last point, I think it's an inheritance issue with events not propagating properly, likely unrelated to the lib, but will report back if I find anything. I'll give your suggestion for custom templates a shot today.

**Comment by udos86** [comment]
@kahboom That's great! I appreciate any help here. Good Luck!
