### ISSUE TITLE
using ng2-dynamic-forms with ngx-translate for multilingual forms

### ISSUE THREAD

**Issue by rernens** [udos86/ng2-dynamic-forms#422]
I am working on a multilingual application and am using ngx-translate for that.

Before I start looking into the code, is there a simple way to use the ngx-translate pipe in conjuction with ng2-dynamic-forms for labels, placeholder and messages ?

**Comment by udos86** [comment]
@rernens Hi!

Thanks for bringing this up.

At the moment there's no support for the translate pipe in dynamic template files. 

You would have to provide translation when creating your form model. 

But I haven't dived deep enough into ngx-translate to evaluate a better solution. I will soon.

**Comment by rernens** [comment]
@udos86 

Thanks for your response. 
I will look into something and see if I can use the ngx-translate service to address this requirement and will let you know.

**Comment by kuwas** [comment]
Would be great if pipes can be supported. ngx-translate translates using observables, doing it programmatically would require stitching together the observable responses with the form models before forms can be rendered and/or updated. It would also require the same mechanisms to be rerun when the user changes the language. Not exactly ideal.

**Comment by kuwas** [comment]
Heres what I did to get all of this working correctly.

1. Provide a language stream as the source
1a. Use the existing onLangChange stream from ngx-translate
1b. Use your own stream such as from Redux or ngrx and sync it with ngx-translate (what I used)
2. Construct your form in a form stream. In my case, my translations come from ngrx
```
this.form$ = this.store
  .select('translate', 'lang')
  .filter(o => (o !== undefined && o !== null))
  .map(o => {
    return [
      new DynamicInputModel({
        id: 'test',
        label: translate.test.label
      })
    ];
  })
  .map(o => ({ model: o, group: null }))
  .map(o => {
    o.group = this.formService.createFormGroup(o.model as any);
    return o;
  })
  ;
```
3. Bind your form stream in your view
```
<div *ngIf="(forms$ | async) as form">
  <form [formGroup]="form.group">
    <dynamic-form-ng-bootstrap-control *ngFor="let control of form.model" [group]="form.group"
 [model]="control" >
    </dynamic-form-ng-bootstrap-control>
  </form>
</div>
```

**Comment by udos86** [comment]
@kuwas Thanks for providing you solution!

**Comment by danimt** [comment]
I was looking for a solution to this lack to support for pipes inside labels and didn't quite like the option provided here.

My solution was to get translation directly from the `TranslateService`
```js
const translations = this.translate.translations[this.translate.currentLang];
```

And then when building your model, just access the key directly from the object.
```js
new DynamicSelectModel<string>({
  id: 'myId',
  label: translations['my-translation-key']
})
```
Then, in the place where you have instantiated the form, just assign the model again
```js
// Simplified example
export class MyComponent {
  public formGroup: FormGroup;
  public formModel: DynamicFormControlModel[];

  constructor(
    private route: ActivatedRoute,
    private formBuilder: MyComponentFormBuilder,
    private translate: TranslateService
  ) {
    this.setForm();

    this.translate.onLangChange.subscribe(() => this.setForm());
  }

  setForm() {
    // Attention, this formBuilder is not part of ng-dynamic-forms, it's my proxy class
    this.formModel = this.formBuilder.model;
    this.formGroup = this.formBuilder.createFormGroup();
  }
}
``` 

Context classes
```js
// Simplified examples
export class MyComponentFormBuilder extends DynamicFormBuilder {
  constructor(
    formService: DynamicFormService,
    private translate: TranslateService
  ) {
    super(formService);
  }

  get model() {
    const translations = this.translate.translations[this.translate.currentLang];

    return [

      new DynamicSelectModel<string>({
        id: 'myId',
        label: translations['my-translation-key']
      })

    ];
  }

}

export class DynamicFormBuilder {
  protected formGroup: FormGroup;
  public formModel: DynamicFormControlModel[];

  constructor(private formService: DynamicFormService) { }

  protected get model() {
    return [];
  }

  public createFormGroup(): FormGroup {
    this.formModel = this.formService.fromJSON(JSON.stringify(this.model));
    this.formGroup = this.formService.createFormGroup(this.formModel);

    return this.formGroup;
  }
}
```
