### ISSUE TITLE
Error building the demo app

### ISSUE THREAD

**Issue by datencia** [udos86/ng2-dynamic-forms#423]
On a freshly cloned repo, after `$ npm install`, when I run `$ npm run build:modules` I get these errors:

![image](https://user-images.githubusercontent.com/18591213/27655521-f79c527a-5c45-11e7-8fc4-7ee4e69cc0da.png)

After diving a bit on google, I've found this [issue](https://github.com/Microsoft/TypeScript/issues/16593) on typescript. It is related with TS 2.4.1 and RxJS 5.4.1 (latest).

After removing the carets from the next dependencies:

```
    "ionic-angular": "3.4.2"
    "rxjs": "5.4.1"
    "typescript": "2.3.4"
```

Everything is back to normal.

I suggest to remove all carets (^) from package.json dependencies to pin all dependencies to their exact version and avoid these kinds of errors in the future.

**Comment by udos86** [comment]
@datencia 

My suggestion here would be that you upgrade to npm5 (if possible) and make use of the new `package-lock.json`.

**Comment by datencia** [comment]
Thx. It's working now. I didn't know about the new npm version. My fault! ;)

**Comment by udos86** [comment]
@datencia No problem, have fun!
