### ISSUE TITLE
Custom Validators with Production build are not working : TypeError: v is not a function

### ISSUE THREAD

**Issue by rahul-winner** [udos86/ng2-dynamic-forms#424]
@udos86 

I've already raised the issue #417. After your suggestion I'm able to work my custom validator. However, now I'm facing problem with production build which is reported with #271 

I've also tried your workaround/solution [ref : [commit](https://github.com/udos86/ng2-dynamic-forms/commit/aaff8ec74e10e25767542777fd05a3cd3afe494d)] by having a property with same function name, however it also didn't work. With this, I got error : **TypeError: v is not a function**

Could you please help me out and suggest me what should be the definition of validator so that it can work in both environments dev as well prod.

Thanks a lot !
Rahul

**Comment by udos86** [comment]
@rahul-winner 

As described in chapter on [`Custom Validators`](https://github.com/udos86/ng2-dynamic-forms#custom-validators) you should exclude validator function names from mangling.

**Comment by rahul-winner** [comment]
Thanks @udos86 

We are using Angular CLI in our project. To exclude a file from mangling in Angular CLI setup, we will need to eject and then customize the webpack.config. As per discussion within, we kept it as last choice. 

Do you think if there could be any other way? 

I'll also try by extending FormService and probably let you know.

Also, in following up to this #417 issue, could you please why custom validator does not work when we provide 'null' against it in model. 

Thanks a lot !

**Comment by rahul-winner** [comment]
@udos86 

I am able to make it work by extending the DynamicFormService and overriding the 'getCustomValidatorFn' method, and then passing on my custom validator function. Look at this.

What is your opinion? 

![image](https://user-images.githubusercontent.com/4982751/27739609-d4130af0-5dcc-11e7-967f-61faf08584e1.png)


I believe you should device some solution to this problem so that people can use custom validators even with production build. Production build is very much obvious and not everyone be comfotable with ejecting Angular CLI config to configure webpack.

**One simple solution** could be to let people override the method 'getCustomValidatorFn' (or you may have any other method name) and provide their own function. 

Thanks. Rahul

**Comment by udos86** [comment]
@rahul-winner Thanks for your proposal!

I'm aware of CLI's lack of custom mangling options (see https://github.com/angular/angular-cli/pull/5192).  

All in all it's not that easy. In order to provide JSON export/import and easy declaration a validator has to be referenced by it's function name. It's the only property that a validator can be safely identified by. When mangled this information is	irretrievably lost.

I'll make this a high priority issue but I can't promise a flawless solution on this.

**Comment by udos86** [comment]
@rahul-winner 

Ok, so my favorite approach to this would be to provide an alternate syntax for  defining validators on a dynamic form model like this:

```
customValidator: {
   name: customValidator.name,
   param: null
}
```

**Comment by udos86** [comment]
@rahul-winner 

Ok, implementation's ready now and will be released this weekend!

Please have a look at [updated docs](https://github.com/udos86/ng2-dynamic-forms/tree/development#custom-validators).

**Comment by rahul-winner** [comment]
Thanks ton @udos86 .. Waiting for it.

**Comment by rahul-winner** [comment]
Thanks a ton @udos86 
I've updated to 1.4.17 and now custom validators worked like charm..
