### ISSUE TITLE
model.cls.grid/element.* classes for radio feels weird

### ISSUE THREAD

**Issue by renatoaraujoc** [udos86/ng2-dynamic-forms#425]
Hello @udos86,

Considering how you render the radio groups, its being impossible to display the radios inline using `form-horizontal` or `form`.

What I want to achieve:
![captura de tela 2017-06-29 as 17 47 19](https://user-images.githubusercontent.com/358128/27709584-08dca7ee-5cf3-11e7-8a6d-e8b291b2b705.png)
![captura de tela 2017-06-29 as 18 01 27](https://user-images.githubusercontent.com/358128/27710135-03285bde-5cf5-11e7-97d1-1b209b68651e.png)

How's your code nowadays:
![captura de tela 2017-06-29 as 17 49 19](https://user-images.githubusercontent.com/358128/27709661-4e86ea52-5cf3-11e7-82d3-225c3cfa1c45.png)

`model.cls.element` on the code above is only seen on the input itself. But what if i wanted to provide a class for the `div.radio` and make it `<div class="radio-inline"></div>`?

This seems the "correct" solution for me (at least the way I understand your library so far)
![captura de tela 2017-06-29 as 18 04 01](https://user-images.githubusercontent.com/358128/27710236-5cef9d44-5cf5-11e7-866c-bb0529970940.png)

Thank you!

Renato

**Comment by udos86** [comment]
@renatoaraujoc Thanks for reporting this template weakness!

I'll have a look on how to fix this.

**Comment by renatoaraujoc** [comment]
Yo @udos86,

Thanks for replying!

To further guide you thru my use case, I'll provide a screenshot.
![captura de tela 2017-07-01 as 21 01 27](https://user-images.githubusercontent.com/358128/27766247-aa532824-5ea0-11e7-9ae8-26a7bf9a54c3.png)

I simply can't inline the radios.

Also, it'd be major cool if you could revamp your template customization (the model.cls.*.* classes) guide in since its one of the most important parts of this framework tbh.

Thank you!

**Comment by udos86** [comment]
@renatoaraujoc 

Ok, there'll probably be a template update in `1.4.18`:

```
<fieldset *ngSwitchCase="5" role="radiogroup"
          [attr.tabindex]="model.tabIndex"
          [dynamicId]="bindId && model.id"
          [name]="model.name"
          (change)="onValueChange($event)">

    <legend *ngIf="model.legend" [innerHTML]="model.legend"></legend>

    <div *ngFor="let option of model.options$ | async" class="radio" [ngClass]="model.cls.element.control">

        <label>

            <input type="radio"
                   [formControlName]="model.id"
                   [name]="model.name"
                   [value]="option.value"
                   (blur)="onFocusChange($event)"
                   (focus)="onFocusChange($event)"/><span [innerHTML]="option.label"></span></label>
    </div>

</fieldset>
```

You can then overwrite the styles from Bootstrap `.radio` class. 

In fact you could have done that already: `[role="radiogroup"] .radio { display: inline }`

**Comment by renatoaraujoc** [comment]
@udos86,

Wouldn't be better to just:

`[ngClass]="model.cls.element.control || 'radio'"`, so we can leave the radio class as the default? And dont forget to remove the `class="radio"`...

And yea, could actually go the other way, but feels hackish when actually ngClass is there for this purpose (and the radio-inline/checkbox-inline as well)

Renato

**Comment by udos86** [comment]
@renatoaraujoc You've got a point there. I'll modify it.
