### ISSUE TITLE
Two custom validators

### ISSUE THREAD

**Issue by RafaelTCostella** [udos86/ng2-dynamic-forms#427]
Hey guys, I'm facing one problem in my project. I need to declare two custom validators, so inside my @NgModule, I have something like this:

```
providers: [
    {
      provide: NG_VALIDATORS,
      useValue: sameDateValidator,
      multi: true
    },
    {
      provide: NG_VALIDATORS,
      useValue: closesAfterOpeningValidator,
      multi: true
    }
  ]
```
This raises an error: Uncaught (in promise): TypeError: Cannot read property 'hasOwnProperty' of null TypeError: Cannot read property 'hasOwnProperty' of null.

After digging some time in the code I think that I found the problem, so I will submit one Pull Request that I believe that fix the problem, is that right?

Thanks for the lib! :beers:

**Comment by udos86** [comment]
@RafaelTCostella Hi! Thanks for your contribution!

Please watch out for next patch version `1.4.17`.

I'm aware that the current custom validator processing has some flaws depending on the project environment.

However this should finally be over with the latest code improvements. 

You can already have a look at the [updated docs](https://github.com/udos86/ng2-dynamic-forms/tree/development#custom-validators).
