### ISSUE TITLE
Form Layout using cls.element/cls.grid not fully working with Material

### ISSUE THREAD

**Issue by rernens** [udos86/ng2-dynamic-forms#429]
I tried to implement adding classes to form elements using 

```
{
   grid: {
     container: 'classA classB'
  }
}
```
but has not found any markup added while this works just fine with boostrap

Unless I am missing the point, customizing the appearance of Material controls does not work using the grid configuration.

**Comment by rernens** [comment]
@udos86 
I have made further try and mistake approaches and found out that the sole part of a component, when using Material, that can be styled is the container if using

{
 element: {
  container: 'classA classB'
 }
}

also found out that the MdDatepicker component style is not properly applied : error message does not appear in warn color and is not sized and placed properly  compared to the other input componen and hint is not shown

**Comment by rernens** [comment]
@udos86 

Further investigation shows that in order to allow custom  styling using cls.element.container and cls.element.control, customization of one Material class is required 

```
.mat-input-container {
  width: 100%;
  margin-top: 0.5rem;
}
```

Nevertheles, proper styling of datepicker seems not feasible. Errors messages do not size and position properly as in standard material design.

**Comment by udos86** [comment]
@rernens Thanks for your investigations!

At the moment I'm not sure how to handle grid classes in Material UI template.

Material's Grid List to me does not provide a grid system that could be operated via CSS.

What do you think?

**Comment by rernens** [comment]
@udos86 

Il think you are right. 

Il am so far combining boostrap grid system with material design forms elements to achieve what il want.

Given your cls.element... customization ability and some minor changes to mat-design classes, I am able to achieve what I want with two minor exceptions : select and datepicker.

Size and placement of the placeholder as as the error messages when data is entered are inconsistent with other input elements

Il might be a material design issue though and I will investigate that further.

I am also experiencing another issue with datepicker : the calendar icon cannot be disabled by you element disabling process. The input element is disabled but the icon is not allowing people to update a datepicker.

Also use of ng-template behave strangely : a click is required on the element to make the custom code appear in the form.

**Comment by rernens** [comment]
@udos86 

Pursuing investigations on your customization ability using cls.element and cls.grid, it looks line it is not possible to assign css classes to a group in an array generated by the createGroup function.

Could that be possible ?

**Comment by udos86** [comment]
@rernens 

>  it looks like it is not possible to assign css classes to a group in an array generated by the createGroup function.

In fact, you can. Use the `group` property name to assign CSS classes to form array groups.

**Comment by rernens** [comment]
@udos86 

I thought i might be the way to do it when I saw the group and host cls property showing up in 1.4.17.

Did try it both in element and grid but the class does not show up attached to the <div role="group"> !

**Comment by udos86** [comment]
@rernens 

> What is the host used for ? I have not been able to figure out what it can be used for.

It can be used when working with nested form groups or form arrays. 

ng2 Dynamic Forms resolves nested form structures recursively. 

So whenever a dynamic form control component is rendered inside another one, `host` classes are appended to the inner, nested component.
