### ISSUE TITLE
custom templates not initially rendered after form is dynamically built

### ISSUE THREAD

**Issue by rernens** [udos86/ng2-dynamic-forms#431]
Angular version 4.2.5 and ng2-dynamic-forms 1.4.17

I an using custom templates with ui-material to insert buttons controlling insertion and deletion of array model as per documentation.

Found out that the additional dom elements that are added by the ng-template(s) are not rendered initially after the form is built : elements are not showing up in the dom.

After any change event, such as a click on any element of the form, the ng-template elements show up and work as expected.

Am i missing something or is it a bug related to ui-material

**Comment by udos86** [comment]
@rernens I'll have to verify the next couple of days if this is a bug

**Comment by rernens** [comment]
@udos86 thanks, waiting to hear from you.

**Comment by udos86** [comment]
@rernens 

Alright, I made some tests now and I cannot verify a bug here.

In the sample application when adding  a custom `<ng-template>`  for a form array everything is rendered flawless.

Could you provide sample code?

**Comment by rernens** [comment]
@udos86

I still have the same problem.

Meanwhile I have been able to circumvent the problem in changing the way the buttons are shown :
the form is initially disabled and the button hidden than the form is changed to edit mode, enabling all fields and showing the buttons that appear properly.

This is a circumvention.

 I will build a plunkr as soon as possible.

Thanks.

**Comment by udos86** [comment]
@rernens 

I guess I ultimately found a way to recreate this error when using `ChangeDetectionStrategy.OnPush`.

There'll be a fix for this in `1.4.23`.
