### ISSUE TITLE
Complex Nested Array Forms Control

### ISSUE THREAD

**Issue by kuwas** [udos86/ng2-dynamic-forms#434]
# Problem

I'm not sure if I just havent found the correct way to do this, but heres the problem I'm having.

1. Must have complex nested form arrays
2. Must have add/remove array groups via the view
3. Attempt to add or remove groups within the nested array

At this step I'm not sure how I can obtain the `FormArray` control, since its path is `formGroup1.formGroupArray1[0].formGroupArrayGroup1.formGroupArrayGroupArray1`, the `formGroup.get()` simply will not work.

## Sample Model

```
export const FORM: Array<DynamicFormControlModel> = [

  new DynamicFormGroupModel({
    id: "formGroup1",
    legend: "Form Group 1",
    group: [

      new DynamicFormArrayModel({
        id: "formGroupArray1",
        legend: "Form Group Array 1",
        initialCount: 1,
        createGroup: () => {
          return [

            new DynamicFormGroupModel({
              id: "formGroupArrayGroup1",
              legend: "Form Group Array Group 1",
              group: [

                new DynamicFormArrayModel({
                  id: "formGroupArrayGroupArray1",
                  legend: "Form Group Array Group Array 1",
                  initialCount: 1,
                  createGroup: () => {
                    return [

                      new DynamicInputModel({
                        id: "input1",
                        label: "Input 1"
                      })

                    ];
                  }
                })

              ]
            })

          ];
        }
      })

    ]
  }),

];
```

## Sample Template

```
<form [formGroup]="formGroup">
  <dynamic-form-basic-control *ngFor="let controlModel of formModel" 
                              [group]="formGroup" 
                              [model]="controlModel">
    <ng-template modelType="ARRAY" let-context="context" let-index="index">
      <button type="button" (click)="removeItem(index, context)">Remove Item</button>
      <button type="button" (click)="insertItem(index +1, context)">Add Item</button>
    </ng-template>    
  </dynamic-form-basic-control>
</form>
```
- - -

#  Suggestion

Since the every `FormGroup` control is available to the `formService.createFormGroup` when it first creates the `formGroup` instance, maybe it will make sense to inject the control to its corresponding model instance, such as `DynamicFormArrayModel`, `DynamicFormGroupModel`, `DynamicInputModel`, etc?

So you can simply do something like this:

```
removeItem(index: number, context: DynamicFormArrayModel) {
  this.formService.removeFormArrayGroup(index, context.control, context);
}   
```

Thanks

**Comment by bappy004** [comment]
possible duplicate of [https://github.com/udos86/ng2-dynamic-forms/issues/414/](https://github.com/udos86/ng2-dynamic-forms/issues/414) ?

**Comment by kuwas** [comment]
Duplicate of https://github.com/udos86/ng2-dynamic-forms/issues/414
