### ISSUE TITLE
One form with two UI library

### ISSUE THREAD

**Issue by zimdero** [udos86/ng2-dynamic-forms#435]
Hello, thank you for this package it is awesome!
But I have one question can I use one form with two different UI library
EX: select input from kendo UI but the other inputs with bootstrap UI
Thanks!

**Comment by udos86** [comment]
@zimdero Thanks for your kind words!

> can I use one form with two different UI library

Yes, it's possible. 

However you would have to include a little logic to use both `<dynamic-form-kendo-control>` and `<dynamic-form-bootstrap-control>` in your `<form>` element.
