### ISSUE TITLE
DynamicSelectModel does not disable on control.disabledUpdates.next(true)

### ISSUE THREAD

**Issue by renatoaraujoc** [udos86/ng2-dynamic-forms#438]
Hello @udos86, me again hehe

According to your README, we can programmatically disable controls by calling `control.disabledUpdates.next(true)`, which does *not* work for `DynamicSelectModel`.
I've also verified that `control.disabled = true` or `control._disabled = true` also do not work.

The following code works though:
```
new DynamicSelectModel({
        id: 'selectId',
        label: 'A label',
        options: [],
        disabled: true
}, {});
```

Am I doing something wrong or could you maybe check this?

Thank you!

**Comment by udos86** [comment]
@renatoaraujoc Hi!

I cannot verify this. Everything seems to be working fine in the sample application.

You need to call `disabledUpdates.next(true)` on the model instance.

**Comment by renatoaraujoc** [comment]
@udos86,

Yeah, I'm actually doing `this.dynamicFormService.findById("aSelect", this.formModel).disabledUpdates.next(true);` (which correctly returns a `DynamicFormControlModel`) and it's not disabling the `DynamicSelectModel` when `disabledUpdates.next(true)` is called...

I'm using the latest version as well.

Well, idk what to do then...

Thank you!

**Comment by renatoaraujoc** [comment]
For some reason I closed the issue, reopening...

**Comment by udos86** [comment]
@renatoaraujoc 

Where / When are you calling on `disabledUpdates.next(true)`?

In my current tests I'm disabling a control when clicking on a button and it's working flawless.

**Comment by renatoaraujoc** [comment]
@udos86,

According to my last comment, try calling `disabledUpdates.next(true)` as soon as you insert a model, like this: 
```
this.dynamicFormService.addFormGroupControl(this.formGroup, this.formModel, new DynamicSelectModel({
    id: 'aSelect',
    options: []
}));
this.dynamicFormService.findById("aSelect", this.formModel).disabledUpdates.next(true);
```
It will not work unless you wait a tick by wrapping `this.dynamicFormService.findById("aSelect", this.formModel).disabledUpdates.next(true);` inside a setTimeout().

**Comment by udos86** [comment]
@renatoaraujoc 

Ok, but that's just the way Angular works.

Why would you add a new (default enabled) model and immediately afterwards disabled it? Why not directly setting `disabled:true` on the configuration object as you pointed out in your initial post.

I think we can close this issue as it is no misbehavior of ng2 Dynamic Forms.
