### ISSUE TITLE
Not loading CSS

### ISSUE THREAD

**Issue by dnyaneshwaruttarwar** [udos86/ng2-dynamic-forms#439]
Hi All,

I have created the project using `ng new demoApp` and installed the ng2-Dynamic-forms primeng, but CSS is not getting applied please check the below screenshot

![image](https://user-images.githubusercontent.com/16442210/28237683-e3eee2c2-6962-11e7-8078-87d4c8f7411e.png)

**Comment by udos86** [comment]
@dnyaneshwaruttarwar 

You always need to manually insert the stylesheet where appropriate for your application (global or component-specific)
