### ISSUE TITLE
Checkboxgroupmodel with option

### ISSUE THREAD

**Issue by 123Rahul** [udos86/ng2-dynamic-forms#440]
hi,

Why can't we have DynamicCheckboxGroupModel with options like DynamicSelectModel instead of DynamicCheckboxModel?
Is there any particular reason for implementing it this way?

**Comment by udos86** [comment]
@123Rahul 

The use of a `DynamicCheckboxGroupModel` is to render a group of checkboxes (a quite common use case.

If you want to combine several form controls of a different kind use a `DynamicFormGroupModel` instead.

**Comment by 123Rahul** [comment]
I got it what you are saying but what I wanted to suggest is-
Wouldn't it be good idea to treat DynamicCheckboxGroup as a separate control instead of making it a group.
It might make things quite easy. It can then be used almost similar to DynamicSelect with multiple checked allowed to be true.

**Comment by udos86** [comment]
@123Rahul 

> Wouldn't it be good idea to treat DynamicCheckboxGroup as a separate control instead of making it a group

Creating new form controls is beyond the scope of ng2 Dynamic Forms. That's a common misconception about the lib.
