### ISSUE TITLE
DropDown Select input : Server Side Options

### ISSUE THREAD

**Issue by stekontar** [udos86/ng2-dynamic-forms#442]
**Question** 
In lot of cases  option values for a dropdown list are not static.
Is there a way to get them from a service during form initialization or in any other way?
Currently I just add an "src" attribute in **DynamicSelectModelConfig** (core > src > model > select > dynamic-select.model.ts) in which I set the preferred url and I call a service which return a promise in order to get the values.

Thanks in advance,
S.

**Comment by udos86** [comment]
@stekontar Hi!

> Is there a way to get them from a service during form initialization or in any other way?

I'm not sure if this helps, but the `options` property also accepts an `Rx.Observable`.

**Comment by stekontar** [comment]
Thank you for your response. 
I ll try it and keep you posted.
Regards,
S.

**Comment by dasaki-gr** [comment]
I have make this [plunker](https://embed.plnkr.co/gAuEzUfW7XwoRxhEYPQt/) 
In **material.component.ts** you can see how i change **DynamicSelectModel** options 
in line 46   this.selectControl.options = this.changeOptionsService.newOptions();

**Comment by SudeshAK** [comment]
@dasaki-gr Hi 
In your example how to set option "New Option 3"  as selected in the dropdown? (currently 'Select an option' is selected by default)
