### ISSUE TITLE
Custom hint template or some hook to allow for trusted HTML

### ISSUE THREAD

**Issue by gashcrumb** [udos86/ng2-dynamic-forms#444]
Hey there!  First off, awesome library we're using it in a bunch of stuff here.

So I have one problem that the `hint` for fields in our forms is a value coming back from the server and I want to be able to dynamically truncate it with a 'Read More' link.  I was hoping to maybe add a little directive in the hint field but basically ran into this:

https://stackoverflow.com/questions/31548311/angular-2-html-binding

as the string gets sanitized, stripping out any potentially unsafe HTML.  It'd be awesome if there was a way to either trust the hint string or supply a custom template for a field's hint section.  Thanks!

**Comment by gashcrumb** [comment]
Think we might be considering implementing a UI component, which would give us a nice direct way to make this and other customizations, so this could wind up being a non-issue

**Comment by udos86** [comment]
@gashcrumb Hi! Thanks for your nice message!

Under the hood `hint` is bound via `[innerHTML]`, so this actually works:

`hint: "<a href='https://www.google.com'>Test</a>"`

However if this fails in your use case I'd encourage you to implement your own UI component as I wouldn't want to open any potential security leak here.

**Comment by gashcrumb** [comment]
Sorry, meant to follow up on this before, we definitely went for our own UI component instead, so I think this is all set.  Thanks!
