### ISSUE TITLE
Add array values dynamically

### ISSUE THREAD

**Issue by Darkheir** [udos86/ng2-dynamic-forms#446]
Hi, I have some trouble to add values to an ArrayField.

I'm doing the following:

```javascript
let model = this.formService.findById(attribute, this.formModel);
let arrayControl = this.formGroup.get(attribute) as FormArray;
let i = 0;
for (let value of arrayValues){
    this.formService.addFormArrayGroup(arrayControl, model);
    let input = model.get(i).group[0] as DynamicInputModel;
    input.valueUpdates.next(value);
    i++;
}
```

As the result I have only the first value of the array that is set and I don't understand why !

**Comment by udos86** [comment]
@Darkheir Hi! 

There's something going on here I cannot fully explain. It's got something do to with change detection and asynchronism. 

So this should litte change should make your code work:
```
for (let value of arrayValues){
    this.formService.addFormArrayGroup(arrayControl, model);
    let input = model.get(i).group[0] as DynamicInputModel;
    setTimeout(() => input.valueUpdates.next(value), 0);
    i++;
}
```

**Comment by renatoaraujoc** [comment]
@udos86,

This is the same "bug" I told you on #438 , you cannot add anything to the model and call anything that modifies the control itself on the next line (like valuesUpdates, etc), you have to wrap it in a setTimeout() call. This further confirms my bug report (or maybe its a limitation from Angular4 itself) that you closed.

**Comment by Darkheir** [comment]
Thanks, this works !
