### ISSUE TITLE
DatePicker for ng-bootstrap component

### ISSUE THREAD

**Issue by dingoogle** [udos86/ng2-dynamic-forms#447]
Hi udos86, 

This is an awesome projects! Thanks for your efforts! 
I'm wondering whether we could use a popup ngb-datepicker. Looks only base datepicker has been implemented in dynamic-form-ng-bootstrap.component.html as below.

...
Calendar = 2, //"CALENDAR",
Checkbox = 3, //"CHECKBOX",
DatePicker = 4, //"DATEPICKER",
...

`<ngb-datepicker *ngSwitchCase="2"
                            [disabled]="model.disabled"
                            [dynamicId]="bindId && model.id"
                            [formControlName]="model.id"
                            [maxDate]="model.max"
                            [minDate]="model.min"
                            [ngClass]="[model.cls.element.control]"
                            [startDate]="model.focusedDate"></ngb-datepicker>
`

There's only switch case "2" but no "2" in the source code. It will be grade if we could use a full-version datepicker in this project.

**Comment by udos86** [comment]
@dingoogle Hi! Thanks for your message!

You're right about the current state of datepicker support in ng-bootstrap.

> I'm wondering whether we could use a popup ngb-datepicker.

I'll make this a high priority feature request for the next version!

**Comment by dingoogle** [comment]
@udos86 Great! Thanks for your response.
