### ISSUE TITLE
How to using filterable in DynamicSelectModel: ui-primeNg

### ISSUE THREAD

**Issue by rodolfocop** [udos86/ng2-dynamic-forms#448]
Hi, I'm using Dynamic Select Model, but it does not work, could anyone help me with this?

`const item= new DynamicSelectModel<string>(
          {
            id: 1215,
            label: model.DisplayText,
            options: builderOptions(model.Options),
            placeholder: 'Municipios',
            filterable:  true

         },
          {
            element: {
              label: 'control-label'
            },
            grid: {
              container: 'col-md-6 dynamic-container',
              control: 'dynamic-input',
              label: 'dynamic-label'
            }
          });`

**Comment by udos86** [comment]
@rodolfocop Thanks for your question!

At the moment filtering on dropdown is not yet supported in Prime NG UI template. 

I'll try to deliver that feature with the next patch version!

**Comment by rodolfocop** [comment]
Thanks for the answer. 
I am waiting for the update and congratulations it this component.

**Comment by drkhannah** [comment]
is filtering available yet? I'm trying to add "filter": true, to my json but its not adding the filter to a PrimeNG multiselect
