### ISSUE TITLE
Require suggestion on implementing a multi step - dynamic form

### ISSUE THREAD

**Issue by anupavanm** [udos86/ng2-dynamic-forms#450]
I would like to implement a multi step - dynamic from where i will have the elements stored in JSON format in database. 
This structured will be produced by a form builder UI.
The structure is a follows:
## form -> sections -> sub-sections ->  items
Example : 
_An Health Care Assessment form will have the following **Sections**:_
**Client Information
Contact Information
Demographics
Lab Information
Insurance Information**
_Each Section might have subsections like:_
**Contact Information** will have Phone numbers and **Address ( Residential & Mailing)**
_Each Subsection will have many items like:_
**Residential Address** will have **country, state, street, zip** etc..

The **count of  items** in the form may vary between **100 - 150**
Obviously, I should split these sections into different views, and make workflow drive these, moving from one section to other section.
Any suggestion on implementing a solution this type  of problem with this library would be helpful.

**Comment by udos86** [comment]
@anupavanm Hi!

Of course there's `DynamicFormGroupModel`to structure your form and create nested form groups. 

Beyond that I think you'll have to bring in some Angular core features to provide a good user experience. What about using aux routes to implement a multi-step form?
