### ISSUE TITLE
Any Possibility of Implementing Multiselect with Prime ng

### ISSUE THREAD

**Issue by babburi** [udos86/ng2-dynamic-forms#451]
Hi,

Could you please provide Multiselect option for Select tag with Prime Ng?

<a>https://www.primefaces.org/primeng/#/multiselect</a> 

Regards,
Hari.

**Comment by udos86** [comment]
@babburi It's [already](https://github.com/udos86/ng2-dynamic-forms/tree/master/modules/ui-primeng) in there...
