### ISSUE TITLE
Custom validation using multiple form fields

### ISSUE THREAD

**Issue by dasaki-gr** [udos86/ng2-dynamic-forms#452]
Is it possible to make  **custom validation using multiple form fields**  with ng2 dynamic forms?
Like example from this site: [https://bertrandg.github.io/angular2-forms-form-group-validation/](https://bertrandg.github.io/angular2-forms-form-group-validation/) ?

**Comment by dasaki-gr** [comment]
I have test ng2 dynamic forms with ui-material in this [plunker](https://embed.plnkr.co/gAuEzUfW7XwoRxhEYPQt/)
I have made a custom validator with name **areaValidator** to check if areaInput values is between [0-50000Ha]

The question is how to validate subareaInput to check values less than areaInput?

**Comment by renatoaraujoc** [comment]
This is a good question.

Maybe the DynamicFormService could be injected into the customValidator so a findById can be used to perform this subArea check... but let's see what @udos86 think about this...

**Comment by udos86** [comment]
@dasaki-gr 

The form group validator feature of `ReactiveFormsModule` shown in the article is provided by `DynamicFormGroupModel`.

So I'd recommend that you wrap the involved form controls into a `DynamicFormGroupModel`  and just apply your validator function via `validator` or `asyncValidator` property ([see API docs](http://ng2-dynamic-forms.udos86.de/docs/classes/_core_src_model_form_group_dynamic_form_group_model_.dynamicformgroupmodel.html#validator)).

**Comment by udos86** [comment]
@dasaki-gr 

If you don't want to use a `DynamicFormGroupModel` you can also apply the validator directly when creating the form group via `DynamicFormService` as shown in [my other sample](https://github.com/udos86/ng-forms-workshop/blob/master/snapshots/app/dynamic-form/5/dynamic-form.component.ts).

**Comment by dasaki-gr** [comment]
Thank you for your response.
I try it but i couldn't understand how asyncvalidation works with dynamic form group
I couldn't find an example with asyncvalidator as Property of DynamicFormControlModel.
I have make this [plunker](https://embed.plnkr.co/gAuEzUfW7XwoRxhEYPQt/) but i can't make it works and check area group validation (i try to console.log some message with areaGroupValidator)
I use NG_ASYNC_VALIDATORS but something i can't catch ????

Regards,
S.

**Comment by dasaki-gr** [comment]
Thank's to [Avnesh Shakya](https://stackoverflow.com/users/2042251/avnesh-shakya) i find answer:
At DynamicFormGroupModel properties we must set:

    asyncValidator : {areaGroupValidator:areaGroupValidator}

and at areaGroupValidator function we must return function like:

    export function areaGroupValidator() {
    return function(formGroup: FormGroup): Promise<ValidationErrors | null> {
      let TotalArea = formGroup.controls.areaInput.value;
      let SubArea = formGroup.controls.subAreaInput.value
      if (SubArea > TotalArea) {
         return new Promise((resolve, reject) => {
            resolve({areaGroupValidator: true});
        }); 
      } else {
        return new Promise((resolve, reject) => {
            resolve(null);
        });
      }
  }
You can see result at this [plunker](https://embed.plnkr.co/gAuEzUfW7XwoRxhEYPQt/)
