### ISSUE TITLE
Feature Request: form layout components

### ISSUE THREAD

**Issue by ticxx** [udos86/ng2-dynamic-forms#454]
Hello
We want to use layout components like wells, panels, cards or tabs to structure forms. So it would be nice to have something like a DynamicContainerModel. Possible properties are: id, title, ... DynamicFormControlComponent[]. The template could be very minimal and then overwritten by a local template. Do you think it is ok to add such a feature to the lib? thanks

**Comment by udos86** [comment]
@ticxx 

Naturally there are some predetermined limitations to customizing layouts when using a dynamic forms approach. Your requirements are beyond that scope, sorry! 

I'd recommend that you create your own custom UI template here and connect it to a `DynamicFormControlComponent`.

**Comment by ticxx** [comment]
@udos86 
I had some time and implemented experimental support for cards and tabs at ng-bootstrap. If you have time and interest, check the fork. https://github.com/ticxx/ng-dynamic-forms
regards ticxx

**Comment by udos86** [comment]
@ticxx Thanks for letting me know! I'll have a look!
