### ISSUE TITLE
Radio Group in ngBootstrap-UI doesn't work

### ISSUE THREAD

**Issue by albwe** [udos86/ng2-dynamic-forms#457]
Hey!

You are not able to select an option visually and it doesn't change value in model either.
Occured in my local project and in your live preview (http://ng2-dynamic-forms.udos86.de/example/index.aot.html#/example-ng-bootstrap) as well.

**Comment by udos86** [comment]
@albwe Thanks for reporting this!

I'll have to examine this to deliver a bugfix with the next patch version update.
