### ISSUE TITLE
`findById` method not working for AOT

### ISSUE THREAD

**Issue by kahboom** [udos86/ng2-dynamic-forms#458]
Works fine in JIT builds, but when using AOT, I get a runtime exception. I don't have direct access to the build configuration since I am using angular-cli, so I can't exclude it from mangling. I also really want to avoid using `ng eject` as that can get messy pretty quickly, and is quite hacky.

What I'm trying to do: The reason I am having this issue is because I'm trying to create a new group from outside of the `*ngFor` iterator (because it's just a simple 'Add New Group' link that calls a method).

This is the HTML:

```
<div class="overflow-hidden content-margin basic-filter-form-container"
         *ngIf="formGroup">

      <form [formGroup]="formGroup"
            class="basic-filter-form">

        <syndesis-form-control *ngFor="let controlModel of basicFilterModel"
                               [group]="formGroup"
                               [model]="controlModel"
                               (change)="onChange($event)">

          <ng-template modelId="rulesFormArray"
                       let-context="context"
                       let-index="index">

            <div class="pull-right rule-buttons">
              <a *ngIf="index !== 0"
                 class="fa fa-trash-o"
                 (click)="remove(context, index)">
              </a>
            </div>

          </ng-template>
        </syndesis-form-control>
      </form>

// This is calling a method from outside of the iterator, to add a new group to that array
      <a (click)="add()"
         class="add-rule">+ Add another rule
      </a>
    </div>
```

The method that gets called from within the same component:

```
  basicFilterModel: DynamicFormControlModel[] = BASIC_FILTER_MODEL;
  formGroup: FormGroup;
  predicateControl: FormControl;
  predicateModel: DynamicInputModel;
  rulesArrayControl: FormArray;
  rulesArrayModel: DynamicFormArrayModel;

  constructor(public currentFlow: CurrentFlow,
              public integrationSupport: IntegrationSupportService,
              private formService: DynamicFormService) {
  }

ngOnInit() {
    const prevStep = this.currentFlow.getPreviousConnection(this.position);

    this.integrationSupport.getFilterOptions(prevStep.connection.id, prevStep.action.id).toPromise().then((resp: any) => {});

    this.formGroup = this.formService.createFormGroup(this.basicFilterModel);

    this.predicateControl = this.formGroup.get('filterSettingsGroup').get('predicate') as FormControl;
    this.predicateModel = this.formService.findById('predicate', this.basicFilterModel) as DynamicInputModel;

// Originally defined here, I comment this out and then just get null from the 'add()' function, or undefined if I try to store as a const
    this.rulesArrayControl = this.formGroup.get('rulesGroup').get('rulesFormArray') as FormArray;
    this.rulesArrayModel = this.formService.findById('rulesFormArray', this.basicFilterModel) as DynamicFormArrayModel;
  }

add() {
    this.rulesArrayControl = this.formGroup.get('rulesGroup').get('rulesFormArray') as FormArray;
    this.rulesArrayModel = this.basicFilterModel[1] as DynamicFormArrayModel;

// The following returns `null` if I do not alter above as I have.
    console.log('this.rulesArrayControl: ' + this.rulesArrayControl);
    console.log('this.rulesArrayModel: ' + JSON.stringify(this.rulesArrayModel));
    this.formService.addFormArrayGroup(this.rulesArrayControl, this.rulesArrayModel);
  }
```

As you can see above, I tried the following alternative of directly accessing the object in the array within the invoked `add` function, rather than traversing the DOM with an element selector, which seems to have kind of worked, but there is some hacking to be done, as it still does not work and renders a different type of error.

```
vendor.a528da5….bundle.js:148 ERROR TypeError: e.addGroup is not a function
```

<img width="1331" alt="screenshot 2017-07-31 18 26 48" src="https://user-images.githubusercontent.com/3844502/28801087-dd40119a-761d-11e7-9bc3-f10e9d06b6d8.png">

I've also tried adding `"types" : ["node"]` to my `tsconfig.json` as suggested in this issue: https://github.com/udos86/ng2-dynamic-forms/issues/276

I think I can use a custom template, but am still trying to figure out how, and am not sure how happy I am with that solution. Any suggestions would be greatly appreciated!

**Comment by udos86** [comment]
@kahboom Hi! It's great to see you using the lib!

From my experience I don't think that AoT is causing your errors here. 

Lately, I had to deal with AoT on several occasions at work and I cannot confirm any mangling problems.

In fact, no property names of a `DynamicFormControlModel` are affected by mangling when using CLI with `--prod` `--aot` flags. 

I made a quick CLI test trying to recreate that misbehavior (by calling the same methods you described) but everything's working flawless.

The [live demo ](http://ng2-dynamic-forms.udos86.de/example/index.aot.html) also is manually built ahead of time via [ngc](https://github.com/udos86/ng2-dynamic-forms/blob/master/tsconfig.app.ngc.json) and I never had to deal with any kind of mangling issues.

> The reason I am having this issue is because I'm trying to create a new group from outside of the *ngFor iterator

Actually this should be perfectly fine.

How do you trigger your AoT build? 

Sorry, it's hard to tell from afar...

**Comment by udos86** [comment]
@kahboom 

I'm using [this](https://github.com/udos86/ng-forms-workshop) sample app for testing CLI compatibility.

**Comment by gashcrumb** [comment]
Just for followup, we got around this issue by creating our own `findById` function like:

https://github.com/syndesisio/syndesis-ui/blob/master/src/app/integrations/edit-page/step-configure/filter-steps/basic-filter.model.ts#L12-L32

not sure about minification, we tend to lag on versions a bit, maybe there's a more recent change that sorted this perhaps...

**Comment by udos86** [comment]
@gashcrumb Thanks for letting me know!
