### ISSUE TITLE
Access Material UI native methodes and properties 

### ISSUE THREAD

**Issue by dgouissem** [udos86/ng2-dynamic-forms#459]
Hello,

Good job, I'm wondering how can i access to  Material UI  native methodes and properties when using  the dynamic forms?

Thanks and regards.

**Comment by udos86** [comment]
@dgouissem Hi!

> Good job

Thanks!

> I'm wondering how can i access to Material UI native methodes and properties when using the dynamic forms?

Every single `DynamicFormMaterialComponent` has a (public) property `mdViewChild` which references the native Material UI component being used.

**Comment by dgouissem** [comment]
Thank you for the quick response, could you please provide me an example how we can use it?

kind regards,

**Comment by udos86** [comment]
@dgouissem 

Use `@ViewChildren` to obtain references to the `DynamicFormControlComponent`s:

```ts
@ViewChildren(DynamicMaterialFormControlComponent) components: QueryList<DynamicMaterialFormControlComponent>;

ngAfterViewInit() {
    console.log(this.components.first.mdViewChild);
}
```

**Comment by dgouissem** [comment]
thank you @udos86
