### ISSUE TITLE
File upload on material

### ISSUE THREAD

**Issue by pmartella** [udos86/ng2-dynamic-forms#460]
Hi, 
looking at the documentation it's stated that 

> file upload controls can be achieved using a DynamicInputModel with inputType: "file"

.
I tried to add the following control to the DynamicFormControlModel,

```
new DynamicInputModel ({
        id: 'materialFileUpload',
        label: 'upload file',
        inputType: 'file'
    })
```

but I get the following error.

```
ERROR Error: Input type "file" isn't supported by md-input-container.
    at getMdInputContainerUnsupportedTypeError (material.es5.js:14915)
    at MdInputDirective.webpackJsonp.../../../material/@angular/material.es5.js.MdInputDirective._validateType (
```

It seems that this kind of input is currently not supported by Angular Material (https://github.com/angular/material2/blob/master/src/lib/input/input-container.ts #MD_INPUT_INVALID_TYPES).

Do you have any suggestion about the preferred way to emulate this kind of control and integrate it in your library?
Thank you in advance.

**Comment by udos86** [comment]
@pmartella Hi! Thanks for your question!

> Do you have any suggestion about the preferred way to emulate this kind of control and integrate it in your library?

I'm sorry, as long as Material does not provide file upload support this just won't work.

The only thing I can suggest to you here is to create your own custom template for `DynamicFormMaterialComponent`.
