### ISSUE TITLE
How can we achieve Panel hierarchy with this library using Kendo UI + bootstarp

### ISSUE THREAD

**Issue by ranag14** [udos86/ng2-dynamic-forms#461]
My problem is to implement a vertical layout group inside the horizontal layout using dynamic forms. 
How can we have a hierarchy paneling?

**Comment by udos86** [comment]
@ranag14 

Use a combination of nested form groups and apply CSS classes for horizontally / vertically structuring your form controls (see this [simple sample model](https://github.com/udos86/ng-forms-workshop/blob/master/src/app/dynamic-form/dynamic-form.model.ts)).
