### ISSUE TITLE
Checkbox Indeterminate state

### ISSUE THREAD

**Issue by amit-kadam** [udos86/ng2-dynamic-forms#466]
Hi team,

We are using ng2-dynamic forms component and for check boxes we are looking to use 'Indeterminate' state. However once we touch checkbox we can't get back to indeterminate state. 

Can we have rotational states? indeterminate ->checked -> unchecked -> indeterminate -> so on

Thanks!!!

**Comment by udos86** [comment]
@amit-kadam Thanks for your message!

I will add indeterminate support for UI templates (where possible) in `1.4.24`.

At the moment  

> Can we have rotational states? indeterminate ->checked -> unchecked -> indeterminate -> so on

No sorry, you'll have to use `indeterminate` property of `DynamicCheckboxModel` then

**Comment by amit-kadam** [comment]
Thanks @udos86 !

We are using indeterminate property of DynamicCheckboxModel . Initially it displays check box in indeterminate state it can not be go back to indeterminate state once user touches . It only checked or unchecked state. Hence just checking if we can have rotational states? indeterminate ->checked -> unchecked -> indeterminate -> so on

https://css-tricks.com/indeterminate-checkboxes/

**Comment by udos86** [comment]
@amit-kadam 

> Hence just checking if we can have rotational states? indeterminate ->checked -> unchecked -> indeterminate -> so on

It's a common misconception that it's the scope of Ng2 Dynamic Forms to provide custom behavior to arbitrary form controls.
