### ISSUE TITLE
Custom Validator for Input File

### ISSUE THREAD

**Issue by maxf64** [udos86/ng2-dynamic-forms#469]
Hi,

First of all, thanks for the library, it's awesome and so helpful.

I'm trying to implement a required validation for an input type="file", however since the 'value' property is not the one being used in this case, but instead the 'files' one, I can't seem to find a way to implement a custom validator for that. 
The FormGroup doesn't even show the file currently selected within the input

Any suggestions ?
Thanks

**Comment by udos86** [comment]
@maxf64

> First of all, thanks for the library, it's awesome and so helpful. 

Thank you very much and thanks for reporting this!

I've never added a required validator to a file input so far. I'll have to dive deeper into this and check some Angular samples for this.

I'll let you know. If you'd like to help you're welcome to contribute some code.

**Comment by udos86** [comment]
@maxf64 

After a short research I found out that [currently](https://github.com/angular/angular/issues/7341) there's simply no `ControlValueAccessor` for file inputs in Angular. 

That's why validation won't work for file inputs at the moment.

**Comment by maxf64** [comment]
@udos86 
Thanks for that, it confirms what I was pretty much expecting. Guess we'll have to wait on the Angular people for that one.
Thanks again for the library, it's been really useful, and I'll definitely push some code when I make some changes that could be useful to everyone.

Cheers
