### ISSUE TITLE
Webpack support.

### ISSUE THREAD

**Issue by skie** [udos86/ng2-dynamic-forms#47]
If I use webpack there is issue with templates loading.
to make component usable I have to copy templates (in case of bootstrap module it is dynamic-form-bootstrap.component.html) to the root of my application.

Webpack use require statement to load templates and only in this case it parses such files.

Request: make plugin flexible and works both with systemjs like now and allow to use it with webpack.

**Comment by udos86** [comment]
Thanks for your request. Will try to take care of this as soon as possible!

**Comment by udos86** [comment]
Will be fixed in beta.3 via inline templates
