### ISSUE TITLE
Update Options with Provider in DynamicSelectModel under DynamicFormArrayModel

### ISSUE THREAD

**Issue by forestgun** [udos86/ng2-dynamic-forms#470]
Hi, this is a question. I can not understand how to access the Options of a SelectModel when it is in a FormArrayModel. Manipulating the ArrayModel I was able to change the Options of the first group, but when dynamically adding another group the Options of the new SelectModel comes with the default options and not the options. Received from the provider.
Please help.

My model:

import {
    DynamicFormControlModel,
    DynamicFormArrayModel,
    DynamicCheckboxModel,
    DynamicCheckboxGroupModel,
    DynamicDatePickerModel,
    DynamicInputModel,
    DynamicRadioGroupModel,
    DynamicSelectModel,
    DynamicSliderModel,
    DynamicSwitchModel,
    DynamicTextAreaModel,
} from "@ng2-dynamic-forms/core";

export const SesionFormModel: DynamicFormControlModel[] = [

    new DynamicFormArrayModel({

        id: "myFormArray",
        initialCount: 1,
        groupFactory: () => {
            return [
                new DynamicSelectModel<string>({
                    id: "idTareas",
                    //label: "Tarea",
                    multiple: false,
                    options: [
                        {
                            label: "Option 1",
                            value: "option-1",
                        },
                        {
                            label: "Option 2",
                            value: "option-2"
                        },
                        {
                            label: "Option 3",
                            value: "option-3"
                        },
                        {
                            label: "Option 4",
                            value: "option-4"
                        }
                    ],
                    placeholder: "Select an option"
                }),
                new DynamicInputModel({
                    id: "iddescripcion",
                    label: "Descripcion"
                }),
                new DynamicInputModel({
                    id: "idorden",
                    label: "Orden",
                    mask: [ /[1-9]/ ],
                    validators: {
                        required: null 
                    },
                    errorMessages: {
                        required: "{{label}} is required."
                    }
                }),
                new DynamicInputModel({
                    id: "idvalor",
                    label: "Valor"
                }),
                new DynamicCheckboxModel({
                    id: "idevaluar",
                    label: "Evaluacion"
                })                
            ];
        }
    })

];

**Comment by udos86** [comment]
@forestgun Hi!

> but when dynamically adding another group the Options of the new SelectModel comes with the default options and not the options. Received from the provider.

Works as designed!

If you'd like to populate a dynamic form array group with your latest options you'd need to reference it like this:

```
let myOptions = [
    {
        label: "Option 1",
        value: "option-1"
    },
    {
        label: "Option 2",
        value: "option-2"
    },
    {
        label: "Option 3",
        value: "option-3"
    },
];

new DynamicFormArrayModel({

    id: "myFormArray",
    initialCount: 1,
    groupFactory: () => {
        return [
            new DynamicSelectModel<string>({
                id: "idTareas",
                options: myOptions
           })
       ]
    }
}) 
```

**Comment by udos86** [comment]
closed due to inactivity
