### ISSUE TITLE
Error Messages on FormGroup Validation

### ISSUE THREAD

**Issue by KingdaCrash** [udos86/ng2-dynamic-forms#475]
Hi there,

I am running into problems using custom validators on a DynamicFormGroupModel. I am using the following construct:

```
this.passwordField = new DynamicInputModel({
      id: 'password',
      label: 'Password',
      inputType: 'password',
      validators: {
        required: null,
        minLength: this.pwLength
      }
    });
    this.passwordRetypeField = new DynamicInputModel({
      id: 'passwordRetype',
      label: 'Retype Password',
      inputType: 'password',
      validators: {
        required: null,
        minLength: this.pwLength
      }
    });
this.passwordSetterGroup = new DynamicFormGroupModel({
      id: 'passwordSetterGroup',
      legend: 'Set your password',
      group: [
        this.passwordField,
        this.passwordRetypeField,
      ],
      validator: {matchingPasswords: null, validators: null},
      errorMessages: {
        noMatchingPasswords: 'Passwords need to match',
      }
    });
```

My validator is the following:

```
import { FormControl } from '@angular/forms';
export function matchingPasswords(control: FormControl): {[s: string]: boolean} {
    const password = control.get('password');
    const confirmPassword = control.get('passwordRetype');
    if (password.value !== confirmPassword.value) {
      console.log('passwords do NOT match');
      return {
        'noMatchingPasswords': true
      };
    } else {
        console.log('passwords match');
      return null;
    }
  }
```

The validation is working great so far and I am not able to save the form without matching passwords. However, any validation fail on inner fields (password fields) leads to an empty errorMessage on the formGroup. The use case for this error is: I am typing in less than 8 characters in both password fields, but both fields are matching. Hence, the custom validation succeeds. This results in an empty error box displayed for the form. 

What do I have to do, to get rid of this error box, or alternatively: display the inner error?

Thanks in advance and have a great day!

**Comment by udos86** [comment]
@KingdaCrash Hi, thanks for reporting this!

Please give me a couple of days to recreate that use case in my sample app.

There really could be some unexpected behavior.

**Comment by udos86** [comment]
@KingdaCrash After some research I can confirm this is a bug. 

Error Messages are not shown for `FormGroup`s at the moment. 

I'm already working on a patch.

**Comment by udos86** [comment]
Bug is caused by the this current Angular behavior: 
https://github.com/angular/angular/issues/10530
