### ISSUE TITLE
Is it possible to use this with out installing as module

### ISSUE THREAD

**Issue by krischandra** [udos86/ng2-dynamic-forms#476]
Hello,
I want to implement this in real time project. So they don't allow me to install as module. Please help me if i can use this as module by creating one folder.
Thanks in advance.

**Comment by udos86** [comment]
@krischandra Hi!

I've never really tried that out but you could load the `*.umd` bundle files for Core and UI pacakge directly via `<script>` tag into your HTML file and see what happens.

**Comment by udos86** [comment]
closed due to inactivity
