### ISSUE TITLE
Controls validation question

### ISSUE THREAD

**Issue by skie** [udos86/ng2-dynamic-forms#48]
Can you provide sample may be in example apphow to use validators with dynamic forms.
So how to extend base form markup to display diferent validation messages. 

For example i tried with field having Validators.required attached to text field
and put `<div *ngIf="control.dirty && !controlvalid">Invalid</div>` inside the template before `<span *ngIf="model.help" class="help-block">{{model.help}}</span>`
So I getting message in case field empty, but I asking if there more generic solution and how it was planned by developer.

**Comment by skie** [comment]
What if model.help (could be another name too) is not a string but function that generates validation messages. This way message generation for validators could be moved on model cofiguration level.

**Comment by udos86** [comment]
Once again thanks for your contribution!

I thought about this topic a lot and came to the conclusion that including some sort of validation message system would be beyond the scope and make the library much more complex than it should be.

Instead  I would recommend the following solution:

(1) Create a custom validation message component which accepts `Control` input: 
```ts 
import {Component, Input} from "angular2/core";
import {FormControl} from "angular2/forms";

@Component({

    moduleId: module.id,
    selector: "validation-message",
    templateUrl: "./validation-message.html"
})

export class ValidationMessage {

    @Input() control: FormControl;

    constructor () {}
}
```

(2) Create the template file your component:_
```ts
<span *ngIf="control && control.hasError('required') && control.touched">Field is required</span>
<span *ngIf="control && control.hasError('invalidCharacters') && control.touched">Field has invalid characters</span>
```

(3) Add the component right after the `DynamicFormControl` in your custom form template and bind the internal `Control` reference via local template variable:

```ts
<form [formGroup]="form">

    <div *ngFor="let controlModel of dynamicFormModel.items" class="form-row">

        <dynamic-form-basic-control [form]="form" [model]="controlModel" #ref></dynamic-form-basic-control>
                
        <validation-message [control]="ref.control"></validation-message>

    </div>

</form>
```

Please let me know if this is a valid solution for you.

**Comment by skie** [comment]
Yes, that's works really good. I see a lot of sense to put this example into documentation.

**Comment by udos86** [comment]
Ok great! Will add it to the documentation!
