### ISSUE TITLE
error whilst transpiling the code ..

### ISSUE THREAD

**Issue by hitesh97** [udos86/ng2-dynamic-forms#482]
Hi There,

First of all, thanks for updating the code so soon.. it was great to see you respond very quickly.

The code now builds on first two steps but gives error on 'npm run transpile:app:systemjs' step.

Please see the error below.. it seems that previous step was meant to create a '.ngfactory' file but hasnt created it ..and hence the file is not found.

Please let me know, if you can point me to the right direction? 

----------------------------------------------------------------------------------------------------------

PS C:\Workspace\Hitesh\ng2-dynamic-forms> npm run transpile:app:systemjs

> ng2-dynamic-forms@1.4.26 transpile:app:systemjs C:\Workspace\Hitesh\ng2-dynamic-forms
> tsc -p tsconfig.app.json -m commonjs

example/app/main.aot.ts(3,36): error TS2307: Cannot find module '../aot/example/app/app.module.ngfactory'.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "ru
" "transpile:app:systemjs"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! ng2-dynamic-forms@1.4.26 transpile:app:systemjs: `tsc -p tsconfig.app.json -m commonjs`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the ng2-dynamic-forms@1.4.26 transpile:app:systemjs script 'tsc -p tsconfig.app.json -m commonjs'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ng2-dynamic-forms package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc -p tsconfig.app.json -m commonjs
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng2-dynamic-forms
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ng2-dynamic-forms
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\khatrih\AppData\Roaming\npm-cache\_logs\2017-08-31T13_19_27_923Z-debug.log

**Comment by hitesh97** [comment]
Found the issue.. 

there is a step missing in between 3 & 4 in the readme.



3. Build the library:

npm run build:modules

_3.5. compile source in AOT 

npm run compile:app:aot_

4. Transpile the source code:

npm run transpile:app:systemjs

**Comment by udos86** [comment]
@hitesh97

I'll comment out the content of `main.aot.ts` by default to avoid this build error in the future.
