### ISSUE TITLE
  " Prime Input "the dropdown list show empty  in the live demo of  "PrimeNG UI"

### ISSUE THREAD

**Issue by jaxiell** [udos86/ng2-dynamic-forms#486]
in the live demo of  "PrimeNG UI", " Prime Input "control dropdown list show empty while showing the list panel.

**Comment by udos86** [comment]
@jaxiell Thanks for reporting this!

Could likely be a library bug.

**Comment by jaxiell** [comment]
@udos86  I found you fix the dropdownlist for "Prime Input". However, "Prime Select" will be affected by this change and it will display Object Object.  Could you please fix that as well?
