### ISSUE TITLE
ui-material validation group/array

### ISSUE THREAD

**Issue by stekontar** [udos86/ng2-dynamic-forms#490]
Hi @udos86 ,
I see that library supports group validation as it presented in Bootstarp example. 
I m trying to use it with material-ui form without success. 
should I do something specific?
the goal is to show toast general error message when some group is not valid 
and when an array does not have the min/max elements

Regards,
S.

`
export const EXAMPLE_MODEL = [

    new DynamicFormGroupModel({

        id: "testFormGroup1",
        legend: "Form Group 1",
        validator: {
            required: null
        },
        errorMessages: {
            required: "error on {{ id }}"
        },
        group: [

            new DynamicInputModel(
                {
                    id: "testInput",
                    label: "testInput1",
                    validators: {
                        required: null,
                        maxLength: 5
                    },
                    errorMessages: {
                        required: "{{ label }} is required",
                        maxLength: "Max character count is 5"
                    }
                }
            )
        ]
    }),

    new DynamicFormGroupModel({

        id: "testFormGroup2",
        legend: "Form Group 2",
        group: [

            new DynamicFormArrayModel(
                {
                    id: "testFormArray",
                    label: "Form Array",
                    validator: {
                        required: null,
                        maxLength: 5
                    },
                    errorMessages: {
                        required: "error on {{ id }}"
                        maxLength: "Max character count is 5"
                    },
                    groupFactory: () => {
                        return [
                            new DynamicInputModel(
                                {
                                    id: "testInput",
                                    label: "testInput1",
                                    validators: {
                                        required: null,
                                        maxLength: 5
                                    },
                                    errorMessages: {
                                        required: "{{ label }} is required",
                                        maxLength: "Max character count is 5"
                                    }
                                }
                            )
                        ];
                    },
                }
            )
        ]
    });
];
`

**Comment by udos86** [comment]
@stekontar Thanks for your issue!

There'll be a significant update concerning this in `1.4.28`.

I'll probably release it tomorrow.

**Comment by udos86** [comment]
@stekontar 

As of `1.4.29 it's working fine.

Have a look at the updated [sample](http://ng2-dynamic-forms.udos86.de/sample/index.aot.html#/material-sample-form).
