### ISSUE TITLE
Pagination Support

### ISSUE THREAD

**Issue by enyachoke** [udos86/ng2-dynamic-forms#56]
Am working on a project with some pretty long paginated json forms.  I can easily convert the forms to a similar metadata. One thing am trying to figure out is how to do pagination. Any ideas?
Here is an example project of what am trying to achieve https://github.com/enyachoke/angular2-formentry.

**Comment by udos86** [comment]
Hi! I would create a nested form group for every page and the do pagination with a library like [**this**](https://github.com/michaelbromley/ng2-pagination).

In ng2 Dynamic Forms Beta.6 there'll be support for nested form groups!

**Comment by enyachoke** [comment]
@udos86  That is great I will wait for it before giving it a try to see if it meets my requirements. Great work.

**Comment by udos86** [comment]
@enyachoke Thanks! Give it a try. Published beta.6 a couple of minutes ago. Good luck!
