### ISSUE TITLE
provide Redux support and example

### ISSUE THREAD

**Issue by udos86** [udos86/ng2-dynamic-forms#76]

**Comment by udos86** [comment]
postponed to post 1.0.0 release

**Comment by abdulhaq-e** [comment]
Would @ngrx/store do?

**Comment by udos86** [comment]
@abdulhaq-e I hope so! Unfortunately I just did not have the time so far, to dive deeper into ngrx.

**Comment by abdulhaq-e** [comment]
Hello @udos86.

First, I would like to thank you for this library. They say that code is poetry and I dare say this was like reading a great poem! Very well structured and very clean code.

Regarding this issue, I have used this library in my own ngrx app and it works fantastically (apart from issue #155). Right now, I cannot think of a way how this library can offer more support to redux/ngrx except for examples. I might come up with something else as I use it more. 

I will be glad to provide the examples. How would you like them to be? Just in the docs or an actual full working example etc...?

**Comment by udos86** [comment]
@abdulhaq-e Wow, thanks for nice message! Great to hear that it's working in your ngrx app! It would be fantastic if you could provide a Redux example. I'm not very familiar with Redux so I would really appreciate your expertise.

**Comment by stekontar** [comment]
@abdulhaq-e any update on this?
Regards,
S.

**Comment by nikolasleblanc** [comment]
I have this working with [angular-redux/form](https://github.com/angular-redux/form) right now. Essentially you just need to get angular-redux/form setup, and then "connect" your ng2-dynamic-form:

    <form connect="dynamicForm" [formGroup]="someFormGroup">
      <dynamic-form-bootstrap-control
        *ngFor="let controlModel of formModel"
        [group]="someFormGroup"
        [model]="controlModel">
      </dynamic-form-bootstrap-control>
    </form>

**Comment by udos86** [comment]
@nikolasleblanc Thanks for sharing your knowledge!
