### ISSUE TITLE
rename CheckboxModelConfig to match convention

### ISSUE THREAD

**Issue by philrowan-mtb** [udos86/ng2-dynamic-forms#78]
Hello,

Been working with this package for just under a week now and I'm digging it. Wrote a custom UI module to deal with some additional input types we needed. So first I want to say thanks.

Now the issue:
It seems like **CheckboxModelConfig** should be **DynamicCheckboxModelConfig** to match the convention used for the other input model and config types.

Cheers

**Comment by udos86** [comment]
@philrowan-mtb Cool, thanks for your contribution! Of course you're right! Will be fixed with next version.

**Comment by udos86** [comment]
fixed in 2179553
