### ISSUE TITLE
Support validators for groups 

### ISSUE THREAD

**Issue by teabaggs** [udos86/ng2-dynamic-forms#79]
It is not well documented but it is possible to attach a validator to a FormGroup. Particularly useful for the checkbox group to require at least one checkbox in the group be checked. See this [SO post](http://stackoverflow.com/questions/37395599/angular2-best-way-to-use-formbuilder-validators-required-with-a-checkbox-group) for context.

**Comment by udos86** [comment]
Nice proposal! Will add it as soon as possible...

**Comment by udos86** [comment]
@teabaggs Thanks for your contribution again!

**Comment by udos86** [comment]
There's a bug in the current implementation. Will be fixed in beta.13
